---
permalink: audit/audit-messages-main.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message 
summary: Descrições detalhadas das mensagens de auditoria retornadas pelo sistema estão listadas nas seções a seguir.  Cada mensagem de auditoria é listada primeiro em uma tabela que agrupa mensagens relacionadas pela classe de atividade que a mensagem representa.  Esses agrupamentos são úteis tanto para entender os tipos de atividades que são auditadas quanto para selecionar o tipo desejado de filtragem de mensagens de auditoria. 
---
= Descrições de mensagens de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descrições detalhadas das mensagens de auditoria retornadas pelo sistema estão listadas nas seções a seguir.  Cada mensagem de auditoria é listada primeiro em uma tabela que agrupa mensagens relacionadas pela classe de atividade que a mensagem representa.  Esses agrupamentos são úteis tanto para entender os tipos de atividades que são auditadas quanto para selecionar o tipo desejado de filtragem de mensagens de auditoria.

As mensagens de auditoria também são listadas em ordem alfabética por seus códigos de quatro caracteres.  Esta lista alfabética permite que você encontre informações sobre mensagens específicas.

Os códigos de quatro caracteres usados neste capítulo são os valores ATYP encontrados nas mensagens de auditoria, conforme mostrado na seguinte mensagem de exemplo:

[listing, subs="specialcharacters,quotes"]
----
2014-07-17T03:50:47.484627
\[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][*ATYP\(FC32\):SYSU*][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Para obter informações sobre como definir níveis de mensagens de auditoria, alterar destinos de log e usar um servidor syslog externo para suas informações de auditoria, consultelink:../monitor/configure-audit-messages.html["Configurar mensagens de auditoria e destinos de log"]
