---
permalink: audit/audit-log-file-rotation.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file, audit.log, audit.log file, rotation, save, autosave, auto save, auto-save 
summary: Os arquivos de logs de auditoria são salvos no diretório /var/local/log de um nó de administração. Os arquivos de log de auditoria ativos são chamados audit.log. 
---
= Rotação do arquivo de log de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os arquivos de logs de auditoria são salvos em um nó de administração `/var/local/log` diretório. Os arquivos de log de auditoria ativos são nomeados `audit.log` .


NOTE: Opcionalmente, você pode alterar o destino dos logs de auditoria e enviar informações de auditoria para um servidor syslog externo. Os logs locais dos registros de auditoria continuam sendo gerados e armazenados quando um servidor syslog externo é configurado. Ver link:../monitor/configure-audit-messages.html["Configurar mensagens de auditoria e destinos de log"] .

Uma vez por dia, o ativo `audit.log` o arquivo é salvo e um novo `audit.log` o arquivo é iniciado.  O nome do arquivo salvo indica quando ele foi salvo, no formato `_yyyy-mm-dd.txt_` .  Se mais de um log de auditoria for criado em um único dia, os nomes dos arquivos usarão a data em que o arquivo foi salvo, anexada por um número, no formato `_yyyy-mm-dd.txt.n_` .  Por exemplo, `2018-04-15.txt` e `2018-04-15.txt.1` são o primeiro e o segundo arquivos de log criados e salvos em 15 de abril de 2018.

Após um dia, o arquivo salvo é compactado e renomeado, no formato `_yyyy-mm-dd.txt.gz_` , que preserva a data original. Com o tempo, isso resulta no consumo de armazenamento alocado para logs de auditoria no nó de administração. Um script monitora o consumo de espaço do log de auditoria e exclui os arquivos de log conforme necessário para liberar espaço no `/var/local/log` diretório.  Os logs de auditoria são excluídos com base na data em que foram criados, sendo os mais antigos excluídos primeiro. Você pode monitorar as ações do script no seguinte arquivo: `/var/local/log/manage-audit.log` .

Este exemplo mostra o ativo `audit.log` arquivo, arquivo do dia anterior(`2018-04-15.txt` ), e o arquivo compactado do dia anterior(`2018-04-14.txt.gz` ).

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----