---
permalink: audit/cbse-object-send-end.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBSE, Object Send End 
summary: Quando a transferência de um bloco de conteúdo de um nó para outro é concluída, esta mensagem é emitida pela entidade de origem. 
---
= CBSE: Fim do envio de objeto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando a transferência de um bloco de conteúdo de um nó para outro é concluída, esta mensagem é emitida pela entidade de origem.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
CNID
 a| 
Identificador de conexão
 a| 
O identificador exclusivo da sessão/conexão nó a nó.



 a| 
CBDI
 a| 
Identificador de bloco de conteúdo
 a| 
O identificador exclusivo do bloco de conteúdo que está sendo transferido.



 a| 
CTDR
 a| 
Direção de transferência
 a| 
Indica se a transferência CBID foi iniciada por push ou pull:

PUSH: A operação de transferência foi solicitada pela entidade remetente.

PULL: A operação de transferência foi solicitada pela entidade receptora.



 a| 
CTSR
 a| 
Entidade de origem
 a| 
O ID do nó da origem (remetente) da transferência CBID.



 a| 
CTDS
 a| 
Entidade de Destino
 a| 
O ID do nó do destino (receptor) da transferência CBID.



 a| 
CTSS
 a| 
Iniciar contagem de sequência
 a| 
Indica a contagem de sequência na qual a transferência começou.



 a| 
CTAS
 a| 
Contagem real da sequência final
 a| 
Indica a última contagem de sequência transferida com sucesso.  Se a Contagem de Sequência Final Real for a mesma que a Contagem de Sequência Inicial e o Resultado da Transferência não for bem-sucedido, nenhum dado foi trocado.



 a| 
RSLT
 a| 
Resultado da transferência
 a| 
O resultado da operação de transferência (da perspectiva da entidade remetente):

SUCS: Transferência concluída com sucesso; todas as contagens de sequência solicitadas foram enviadas.

CONL: conexão perdida durante a transferência

CTMO: tempo limite de conexão durante estabelecimento ou transferência

UNRE: ID do nó de destino inacessível

CRPT: transferência encerrada devido ao recebimento de dados corrompidos ou inválidos

|===
Esta mensagem de auditoria significa que uma operação de transferência de dados de nó para nó foi concluída.  Se o resultado da transferência for bem-sucedido, a operação transfere dados de "Contagem de sequência inicial" para "Contagem de sequência final real".  Os nós de envio e recebimento são identificados por seus IDs de nó.  Essas informações podem ser usadas para rastrear o fluxo de dados do sistema e para localizar, tabular e analisar erros.  Quando combinado com mensagens de auditoria de armazenamento, também pode ser usado para verificar contagens de réplicas.
