---
permalink: audit/client-read-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client read, S3SL, SGET, SHEA, WGET, WHEA, S3, swift 
summary: As mensagens de auditoria de leitura do cliente são registradas quando um aplicativo cliente S3 faz uma solicitação para recuperar um objeto. 
---
= O cliente leu mensagens de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens de auditoria de leitura do cliente são registradas quando um aplicativo cliente S3 faz uma solicitação para recuperar um objeto.

[cols="1a,3a,1a,1a"]
|===
| Código | Descrição | Usado por | Ver 


 a| 
S3SL
 a| 
Solicitação S3 Select: Registra uma conclusão depois que uma solicitação S3 Select é retornada ao cliente.  A mensagem S3SL pode incluir detalhes da mensagem de erro e do código de erro.  A solicitação pode não ter sido bem-sucedida.
 a| 
Cliente S3
 a| 
link:s3-select-request.html["S3SL: Solicitação de seleção S3"]



 a| 
SGET
 a| 
S3 GET: Registra uma transação bem-sucedida para recuperar um objeto ou listar os objetos em um bucket.

*Observação:* Se a transação operar em um sub-recurso, a mensagem de auditoria incluirá o campo S3SR.
 a| 
Cliente S3
 a| 
link:sget-s3-get.html["SGET: S3 OBTER"]



 a| 
KARITÉ
 a| 
S3 HEAD: Registra uma transação bem-sucedida para verificar a existência de um objeto ou bucket.
 a| 
Cliente S3
 a| 
link:shea-s3-head.html["SHEA: CABEÇA S3"]



 a| 
WGET
 a| 
Swift GET: Registra uma transação bem-sucedida para recuperar um objeto ou listar os objetos em um contêiner.
 a| 
Cliente Swift
 a| 
link:wget-swift-get.html["WGET: GET rápido"]



 a| 
WHEA
 a| 
Swift HEAD: Registra uma transação bem-sucedida para verificar a existência de um objeto ou contêiner.
 a| 
Cliente Swift
 a| 
link:whea-swift-head.html["WHEA: CABEÇA Rápida"]

|===