---
permalink: audit/gtst-grid-task-started.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTST, Grid Task Started 
summary: Esta mensagem de auditoria indica que o serviço CMN começou a processar a tarefa de grade especificada.  A mensagem de auditoria segue imediatamente a mensagem Grid Task Submitted para tarefas de grade iniciadas pelo serviço interno Grid Task Submission e selecionadas para ativação automática.  Para tarefas de grade enviadas para a tabela Pendente, esta mensagem é gerada quando o usuário inicia a tarefa de grade. 
---
= GTST: Tarefa de grade iniciada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta mensagem de auditoria indica que o serviço CMN começou a processar a tarefa de grade especificada.  A mensagem de auditoria segue imediatamente a mensagem Grid Task Submitted para tarefas de grade iniciadas pelo serviço interno Grid Task Submission e selecionadas para ativação automática.  Para tarefas de grade enviadas para a tabela Pendente, esta mensagem é gerada quando o usuário inicia a tarefa de grade.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
TSID
 a| 
ID da tarefa
 a| 
Este campo identifica exclusivamente uma tarefa de grade gerada e permite que a tarefa seja gerenciada ao longo de seu ciclo de vida.

*Observação:* O ID da tarefa é atribuído no momento em que uma tarefa de grade é gerada, não no momento em que ela é enviada.  É possível que uma determinada tarefa de grade seja enviada várias vezes e, nesse caso, o campo ID da tarefa não é suficiente para vincular exclusivamente as mensagens de auditoria Enviadas, Iniciadas e Encerradas.



 a| 
RSLT
 a| 
Resultado
 a| 
O resultado.  Este campo tem apenas um valor:

* SUCS: A tarefa de grade foi iniciada com sucesso.


|===