---
permalink: audit/lkdm-leaked-object-cleanup.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LKDM, Leaked Object Cleanup 
summary:  
---
= LKDM: Limpeza de Objetos Vazados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta mensagem é gerada quando um pedaço vazado é limpo ou excluído.  Um pedaço pode ser parte de um objeto replicado ou de um objeto codificado para eliminação.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
CLOC
 a| 
Localização do pedaço
 a| 
O caminho do arquivo do pedaço vazado que foi excluído.



 a| 
CTYP
 a| 
Tipo de pedaço
 a| 
Tipo de pedaço:

`ec: Erasure-coded object chunk`

`repl: Replicated object chunk`



 a| 
LTYP
 a| 
Tipo de vazamento
 a| 
Os cinco tipos de vazamentos que podem ser detectados:

`object_leaked: Object doesn’t exist in the grid`

`location_leaked: Object exists in the grid, but found location doesn’t belong to object`

`mup_seg_leaked: Multipart upload was stopped or not completed, and the segment/part was left out`

`segment_leaked: Parent UUID/CBID (associated container object) is valid but doesn't contain this segment`

`no_parent: Container object is deleted, but object segment was left out and not deleted`



 a| 
CTIM
 a| 
Tempo de criação do bloco
 a| 
Horário em que o pedaço vazado foi criado.



 a| 
UUID
 a| 
Identificador Universalmente Único
 a| 
O identificador do objeto ao qual o pedaço pertence.



 a| 
CBDI
 a| 
Identificador de bloco de conteúdo
 a| 
CBID do objeto ao qual o pedaço vazado pertence.



 a| 
CSIZ
 a| 
Tamanho do conteúdo
 a| 
O tamanho do pedaço em bytes.

|===