---
permalink: audit/orlm-object-rules-met.html 
sidebar: sidebar 
keywords: audit message, ORLM, Object Rules Met, ilm rule 
summary: Esta mensagem é gerada quando o objeto é armazenado e copiado com sucesso, conforme especificado pelas regras do ILM. 
---
= ORLM: Regras de Objeto Atendidas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta mensagem é gerada quando o objeto é armazenado e copiado com sucesso, conforme especificado pelas regras do ILM.


NOTE: A mensagem ORLM não é gerada quando um objeto é armazenado com sucesso pela regra padrão Fazer 2 Cópias se outra regra na política usar o filtro avançado Tamanho do Objeto.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
CONSTRUIR
 a| 
Cabeçalho de balde
 a| 
Campo ID do bucket.  Usado para operações internas.  Aparece somente se STAT for PRGD.



 a| 
CBDI
 a| 
Identificador de bloco de conteúdo
 a| 
O CBDID do objeto.



 a| 
CSIZ
 a| 
Tamanho do conteúdo
 a| 
O tamanho do objeto em bytes.



 a| 
LOCS
 a| 
Locais
 a| 
O local de armazenamento de dados de objetos dentro do sistema StorageGRID .  O valor para LOCS é "" se o objeto não tiver localizações (por exemplo, ele foi excluído).

CLEC: para objetos codificados por eliminação, o ID do perfil de codificação por eliminação e o ID do grupo de codificação por eliminação que são aplicados aos dados do objeto.

CLDI: para objetos replicados, o ID do nó LDR e o ID do volume do local do objeto.

CLNL: ID do nó ARC da localização do objeto se os dados do objeto estiverem arquivados.



 a| 
CAMINHO
 a| 
Balde/Chave S3
 a| 
O nome do bucket S3 e o nome da chave S3.



 a| 
RSLT
 a| 
Resultado
 a| 
O resultado da operação ILM.

SUCS: A operação ILM foi bem-sucedida.



 a| 
REGRA
 a| 
Etiqueta de regras
 a| 
O rótulo legível dado à regra ILM aplicada a este objeto.



 a| 
SEGC
 a| 
UUID do contêiner
 a| 
UUID do contêiner para o objeto segmentado.  Este valor só estará disponível se o objeto for segmentado.



 a| 
SGCB
 a| 
CBDID do contêiner
 a| 
CBID do contêiner para o objeto segmentado.  Este valor está disponível somente para objetos segmentados e multipartes.



 a| 
ESTATÍSTICA
 a| 
Status
 a| 
O status da operação do ILM.

CONCLUÍDO: As operações do ILM contra o objeto foram concluídas.

DFER: O objeto foi marcado para futura reavaliação do ILM.

PRGD: O objeto foi excluído do sistema StorageGRID .

NLOC: Os dados do objeto não podem mais ser encontrados no sistema StorageGRID .  Esse status pode indicar que todas as cópias dos dados do objeto estão ausentes ou danificadas.



 a| 
UUID
 a| 
Identificador Universalmente Único
 a| 
O identificador do objeto dentro do sistema StorageGRID .



 a| 
VSID
 a| 
ID da versão
 a| 
O ID da versão de um novo objeto criado em um bucket versionado.  Operações em buckets e objetos em buckets não versionados não incluem este campo.

|===
A mensagem de auditoria ORLM pode ser emitida mais de uma vez para um único objeto.  Por exemplo, ele é emitido sempre que ocorre um dos seguintes eventos:

* As regras do ILM para o objeto são satisfeitas para sempre.
* As regras do ILM para o objeto são satisfeitas para esta época.
* As regras do ILM excluíram o objeto.
* O processo de verificação em segundo plano detecta que uma cópia dos dados do objeto replicado está corrompida.  O sistema StorageGRID executa uma avaliação do ILM para substituir o objeto corrompido.


.Informações relacionadas
* link:object-ingest-transactions.html["Transações de ingestão de objetos"]
* link:object-delete-transactions.html["Transações de exclusão de objetos"]

