---
permalink: audit/sdel-s3-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SDEL, S3 DELETE 
summary: Quando um cliente S3 emite uma transação DELETE, uma solicitação é feita para remover o objeto ou bucket especificado.  Esta mensagem é emitida pelo servidor se a transação for bem-sucedida. 
---
= SDEL: S3 EXCLUIR
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um cliente S3 emite uma transação DELETE, uma solicitação é feita para remover o objeto ou bucket especificado, ou para remover um sub-recurso de bucket/objeto.  Esta mensagem é emitida pelo servidor se a transação for bem-sucedida.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
CBDI
 a| 
Identificador de bloco de conteúdo
 a| 
O identificador exclusivo do bloco de conteúdo solicitado.  Se o CBID for desconhecido, este campo será definido como 0.  Operações em buckets não incluem este campo.



 a| 
CNCH
 a| 
Cabeçalho de Controle de Consistência
 a| 
O valor do cabeçalho de solicitação HTTP Consistency-Control, se presente na solicitação.



 a| 
CNID
 a| 
Identificador de conexão
 a| 
O identificador exclusivo do sistema para a conexão TCP/IP.



 a| 
CSIZ
 a| 
Tamanho do conteúdo
 a| 
O tamanho do objeto excluído em bytes.  Operações em buckets não incluem este campo.



 a| 
DMRK
 a| 
Excluir ID da versão do marcador
 a| 
O ID da versão do marcador de exclusão criado ao excluir um objeto de um bucket versionado.  Operações em buckets não incluem este campo.



 a| 
GFID
 a| 
ID de conexão da federação de grade
 a| 
O ID de conexão da federação de grade associada a uma solicitação de exclusão de replicação entre grades.  Incluído somente em logs de auditoria na grade de destino.



 a| 
GFSA
 a| 
ID da conta de origem da Federação de Grade
 a| 
O ID da conta do locatário na grade de origem para uma solicitação de exclusão de replicação entre grades.  Incluído somente em logs de auditoria na grade de destino.



 a| 
HTRH
 a| 
Cabeçalho de solicitação HTTP
 a| 
Lista de nomes e valores de cabeçalhos de solicitações HTTP registrados, conforme selecionados durante a configuração.

 `X-Forwarded-For`é incluído automaticamente se estiver presente na solicitação e se o `X-Forwarded-For` valor é diferente do endereço IP do remetente da solicitação (campo de auditoria SAIP).

`x-amz-bypass-governance-retention`é incluído automaticamente se estiver presente na solicitação.



 a| 
MTME
 a| 
Última hora modificada
 a| 
O registro de data e hora do Unix, em microssegundos, indicando quando o objeto foi modificado pela última vez.



 a| 
RSLT
 a| 
Código de resultado
 a| 
Resultado da transação DELETE.  O resultado é sempre:

SUCS: Bem-sucedido



 a| 
S3AI
 a| 
ID da conta do locatário S3 (remetente da solicitação)
 a| 
O ID da conta do locatário do usuário que enviou a solicitação.  Um valor vazio indica acesso anônimo.



 a| 
S3AK
 a| 
ID da chave de acesso S3 (remetente da solicitação)
 a| 
O ID da chave de acesso S3 com hash para o usuário que enviou a solicitação.  Um valor vazio indica acesso anônimo.



 a| 
S3BK
 a| 
Balde S3
 a| 
O nome do bucket S3.



 a| 
S3KY
 a| 
Chave S3
 a| 
O nome da chave S3, sem incluir o nome do bucket.  Operações em buckets não incluem este campo.



 a| 
S3SR
 a| 
Sub-recurso S3
 a| 
O bucket ou sub-recurso do objeto que está sendo operado, se aplicável.



 a| 
SACC
 a| 
Nome da conta do locatário S3 (remetente da solicitação)
 a| 
O nome da conta do locatário do usuário que enviou a solicitação.  Vazio para solicitações anônimas.



 a| 
SAIP
 a| 
Endereço IP (remetente da solicitação)
 a| 
O endereço IP do aplicativo cliente que fez a solicitação.



 a| 
SBAC
 a| 
Nome da conta do locatário S3 (proprietário do bucket)
 a| 
O nome da conta do locatário do proprietário do bucket.  Usado para identificar acesso anônimo ou entre contas.



 a| 
SBAI
 a| 
ID da conta do locatário S3 (proprietário do bucket)
 a| 
O ID da conta do locatário do proprietário do bucket de destino.  Usado para identificar acesso anônimo ou entre contas.



 a| 
SGRP
 a| 
Site (Grupo)
 a| 
Se presente, o objeto foi excluído no site especificado, que não é o site onde o objeto foi ingerido.



 a| 
SUSR
 a| 
URN do usuário S3 (remetente da solicitação)
 a| 
O ID da conta do locatário e o nome de usuário do usuário que faz a solicitação.  O usuário pode ser um usuário local ou um usuário LDAP. Por exemplo:  `urn:sgws:identity::03393893651506583485:root`

Vazio para solicitações anônimas.



 a| 
TEMPO
 a| 
Tempo
 a| 
Tempo total de processamento da solicitação em microssegundos.



 a| 
TLIP
 a| 
Endereço IP do balanceador de carga confiável
 a| 
Se a solicitação foi roteada por um balanceador de carga confiável da Camada 7, o endereço IP do balanceador de carga.



 a| 
UUDM
 a| 
Identificador universalmente exclusivo para um marcador de exclusão
 a| 
O identificador de um marcador de exclusão.  As mensagens do log de auditoria especificam UUDM ou UUID, onde UUDM indica um marcador de exclusão criado como resultado de uma solicitação de exclusão de objeto, e UUID indica um objeto.



 a| 
UUID
 a| 
Identificador Universalmente Único
 a| 
O identificador do objeto dentro do sistema StorageGRID .



 a| 
VSID
 a| 
ID da versão
 a| 
O ID da versão específica de um objeto que foi excluído.  Operações em buckets e objetos em buckets não versionados não incluem este campo.

|===