---
permalink: audit/spos-s3-post.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SPOS, S3 POST 
summary: Quando um cliente S3 emite uma solicitação de objeto POST, esta mensagem é emitida pelo servidor se a transação for bem-sucedida. 
---
= SPOS: POSTAGEM S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um cliente S3 emite uma solicitação de objeto POST, esta mensagem é emitida pelo servidor se a transação for bem-sucedida.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
CBDI
 a| 
Identificador de bloco de conteúdo
 a| 
O identificador exclusivo do bloco de conteúdo solicitado.  Se o CBID for desconhecido, este campo será definido como 0.



 a| 
CNCH
 a| 
Cabeçalho de Controle de Consistência
 a| 
O valor do cabeçalho de solicitação HTTP Consistency-Control, se presente na solicitação.



 a| 
CNID
 a| 
Identificador de conexão
 a| 
O identificador exclusivo do sistema para a conexão TCP/IP.



 a| 
CSIZ
 a| 
Tamanho do conteúdo
 a| 
O tamanho do objeto recuperado em bytes.



 a| 
HTRH
 a| 
Cabeçalho de solicitação HTTP
 a| 
Lista de nomes e valores de cabeçalhos de solicitações HTTP registrados, conforme selecionados durante a configuração.

 `X-Forwarded-For`é incluído automaticamente se estiver presente na solicitação e se o `X-Forwarded-For` valor é diferente do endereço IP do remetente da solicitação (campo de auditoria SAIP).

(Não esperado para SPOS).



 a| 
RSLT
 a| 
Código de resultado
 a| 
Resultado da solicitação RestoreObject.  O resultado é sempre:

SUCS: Bem-sucedido



 a| 
S3AI
 a| 
ID da conta do locatário S3 (remetente da solicitação)
 a| 
O ID da conta do locatário do usuário que enviou a solicitação.  Um valor vazio indica acesso anônimo.



 a| 
S3AK
 a| 
ID da chave de acesso S3 (remetente da solicitação)
 a| 
O ID da chave de acesso S3 com hash para o usuário que enviou a solicitação.  Um valor vazio indica acesso anônimo.



 a| 
S3BK
 a| 
Balde S3
 a| 
O nome do bucket S3.



 a| 
S3KY
 a| 
Chave S3
 a| 
O nome da chave S3, sem incluir o nome do bucket.  Operações em buckets não incluem este campo.



 a| 
S3SR
 a| 
Sub-recurso S3
 a| 
O bucket ou sub-recurso do objeto que está sendo operado, se aplicável.

Defina como "selecionar" para uma operação S3 Select.



 a| 
SACC
 a| 
Nome da conta do locatário S3 (remetente da solicitação)
 a| 
O nome da conta do locatário do usuário que enviou a solicitação.  Vazio para solicitações anônimas.



 a| 
SAIP
 a| 
Endereço IP (remetente da solicitação)
 a| 
O endereço IP do aplicativo cliente que fez a solicitação.



 a| 
SBAC
 a| 
Nome da conta do locatário S3 (proprietário do bucket)
 a| 
O nome da conta do locatário do proprietário do bucket.  Usado para identificar acesso anônimo ou entre contas.



 a| 
SBAI
 a| 
ID da conta do locatário S3 (proprietário do bucket)
 a| 
O ID da conta do locatário do proprietário do bucket de destino.  Usado para identificar acesso anônimo ou entre contas.



 a| 
SRCF
 a| 
Configuração de sub-recursos
 a| 
Restaurar informações.



 a| 
SUSR
 a| 
URN do usuário S3 (remetente da solicitação)
 a| 
O ID da conta do locatário e o nome de usuário do usuário que faz a solicitação.  O usuário pode ser um usuário local ou um usuário LDAP. Por exemplo:  `urn:sgws:identity::03393893651506583485:root`

Vazio para solicitações anônimas.



 a| 
TEMPO
 a| 
Tempo
 a| 
Tempo total de processamento da solicitação em microssegundos.



 a| 
TLIP
 a| 
Endereço IP do balanceador de carga confiável
 a| 
Se a solicitação foi roteada por um balanceador de carga confiável da Camada 7, o endereço IP do balanceador de carga.



 a| 
UUID
 a| 
Identificador Universalmente Único
 a| 
O identificador do objeto dentro do sistema StorageGRID .



 a| 
VSID
 a| 
ID da versão
 a| 
O ID da versão específica de um objeto que foi solicitado.  Operações em buckets e objetos em buckets não versionados não incluem este campo.

|===