---
permalink: audit/srem-object-store-remove.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SREM, Object Store Remove 
summary: Esta mensagem é emitida quando o conteúdo é removido do armazenamento persistente e não está mais acessível por meio de APIs regulares. 
---
= SREM: Remoção de armazenamento de objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta mensagem é emitida quando o conteúdo é removido do armazenamento persistente e não está mais acessível por meio de APIs regulares.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
CBDI
 a| 
Identificador de bloco de conteúdo
 a| 
O identificador exclusivo do bloco de conteúdo excluído do armazenamento permanente.



 a| 
RSLT
 a| 
Código de resultado
 a| 
Indica o resultado das operações de remoção de conteúdo.  O único valor definido é:

SUCS: Conteúdo removido do armazenamento persistente

|===
Esta mensagem de auditoria significa que um determinado bloco de conteúdo foi excluído de um nó e não pode mais ser solicitado diretamente.  A mensagem pode ser usada para rastrear o fluxo de conteúdo excluído dentro do sistema.
