---
permalink: audit/system-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, system, ECOC, ETAF, GNRG, GNUR, GTED, GTST, GTSU, LLST, OLST, SADD, SADE, SVRF, SVRU, SYSD, SYST, SYSU, VLST 
summary: 'As mensagens de auditoria pertencentes à categoria de auditoria do sistema são usadas para eventos relacionados ao próprio sistema de auditoria, estados de nós de grade, atividade de tarefas em todo o sistema (tarefas de grade) e operações de backup de serviço.' 
---
= Mensagens de auditoria do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens de auditoria pertencentes à categoria de auditoria do sistema são usadas para eventos relacionados ao próprio sistema de auditoria, estados de nós de grade, atividade de tarefas em todo o sistema (tarefas de grade) e operações de backup de serviço.

[cols="1a,2a,1a"]
|===
| Código | Título e descrição da mensagem | Ver 


 a| 
ECMC
 a| 
Fragmento de dados codificado por apagamento ausente: indica que um fragmento de dados codificado por apagamento ausente foi detectado.
 a| 
link:ecmc-missing-erasure-coded-data-fragment.html["ECMC: Fragmento de dados codificado por apagamento ausente"]



 a| 
CEC
 a| 
Fragmento de dados corrompido com codificação de eliminação: indica que um fragmento de dados corrompido com codificação de eliminação foi detectado.
 a| 
link:ecoc-corrupt-erasure-coded-data-fragment.html["ECOC: Fragmento de dados codificados por apagamento corrompidos"]



 a| 
ETAF
 a| 
Falha na autenticação de segurança: uma tentativa de conexão usando o Transport Layer Security (TLS) falhou.
 a| 
link:etaf-security-authentication-failed.html["ETAF: Falha na autenticação de segurança"]



 a| 
GNRG
 a| 
Registro GNDS: Um serviço atualiza ou registra informações sobre si mesmo no sistema StorageGRID .
 a| 
link:gnrg-gnds-registration.html["GNRG: Registro GNDS"]



 a| 
GNUR
 a| 
Cancelamento de registro do GNDS: um serviço cancelou seu registro no sistema StorageGRID .
 a| 
link:gnur-gnds-unregistration.html["GNUR: Cancelamento de registro do GNDS"]



 a| 
GTED
 a| 
Tarefa de grade encerrada: o serviço CMN concluiu o processamento da tarefa de grade.
 a| 
link:gted-grid-task-ended.html["GTED: Tarefa de grade encerrada"]



 a| 
GTST
 a| 
Tarefa de grade iniciada: o serviço CMN começou a processar a tarefa de grade.
 a| 
link:gtst-grid-task-started.html["GTST: Tarefa de grade iniciada"]



 a| 
GTSU
 a| 
Tarefa de grade enviada: uma tarefa de grade foi enviada ao serviço CMN.
 a| 
link:gtsu-grid-task-submitted.html["GTSU: Tarefa de grade enviada"]



 a| 
LLST
 a| 
Localização perdida: esta mensagem de auditoria é gerada quando uma localização é perdida.
 a| 
link:llst-location-lost.html["LLST: Localização Perdida"]



 a| 
OLST
 a| 
Objeto perdido: um objeto solicitado não pode ser localizado no sistema StorageGRID .
 a| 
link:olst-system-detected-lost-object.html["OLST: Sistema detectou objeto perdido"]



 a| 
SADD
 a| 
Desativar auditoria de segurança: o registro de mensagens de auditoria foi desativado.
 a| 
link:sadd-security-audit-disable.html["SADD: Desativação de auditoria de segurança"]



 a| 
SADE
 a| 
Habilitar auditoria de segurança: o registro de mensagens de auditoria foi restaurado.
 a| 
link:sade-security-audit-enable.html["SADE: Habilitar Auditoria de Segurança"]



 a| 
SVRF
 a| 
Falha na verificação do Object Store: um bloco de conteúdo falhou nas verificações.
 a| 
link:svrf-object-store-verify-fail.html["SVRF: Falha na verificação do armazenamento de objetos"]



 a| 
SVRU
 a| 
Object Store Verify Unknown: Dados de objeto inesperados detectados no armazenamento de objetos.
 a| 
link:svru-object-store-verify-unknown.html["SVRU: Verificação de armazenamento de objeto desconhecido"]



 a| 
SYSD
 a| 
Parada do nó: um desligamento foi solicitado.
 a| 
link:sysd-node-stop.html["SYSD: Parada do nó"]



 a| 
SISTEMA
 a| 
Parada de nó: um serviço iniciou uma parada normal.
 a| 
link:syst-node-stopping.html["SYST: Parada do nó"]



 a| 
SYSU
 a| 
Início do nó: um serviço foi iniciado; a natureza do desligamento anterior é indicada na mensagem.
 a| 
link:sysu-node-start.html["SYSU: Início do nó"]

|===