---
permalink: audit/using-audit-explain-tool.html 
sidebar: sidebar 
keywords: storagegrid, audit, tool, audit-explain, audit explain, translate audit messages, translate messages, translate audit message, translate message 
summary: Você pode usar a ferramenta audit-explain para traduzir as mensagens de auditoria no log de auditoria para um formato fácil de ler. 
---
= Use a ferramenta audit-explain
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `audit-explain` ferramenta para traduzir as mensagens de auditoria no log de auditoria para um formato fácil de ler.

.Antes de começar
* Você temlink:../admin/admin-group-permissions.html["permissões de acesso específicas"] .
* Você deve ter o `Passwords.txt` arquivo.
* Você deve saber o endereço IP do nó de administração primário.


.Sobre esta tarefa
O `audit-explain` A ferramenta, disponível no nó de administração principal, fornece resumos simplificados das mensagens de auditoria em um log de auditoria.


NOTE: O `audit-explain` A ferramenta destina-se principalmente ao uso pelo suporte técnico durante operações de solução de problemas.  Processamento `audit-explain` consultas podem consumir uma grande quantidade de energia da CPU, o que pode afetar as operações do StorageGRID .

Este exemplo mostra a saída típica do `audit-explain` ferramenta.  Esses quatrolink:sput-s3-put.html["CUSPIR"] mensagens de auditoria foram geradas quando o locatário do S3 com ID de conta 92484777680322627870 usou solicitações S3 PUT para criar um bucket chamado "bucket1" e adicionar três objetos a esse bucket.

[listing]
----
SPUT S3 PUT bucket bucket1 account:92484777680322627870 usec:124673
SPUT S3 PUT object bucket1/part1.txt tenant:92484777680322627870  cbid:9DCB157394F99FE5 usec:101485
SPUT S3 PUT object bucket1/part2.txt tenant:92484777680322627870  cbid:3CFBB07AB3D32CA9 usec:102804
SPUT S3 PUT object bucket1/part3.txt tenant:92484777680322627870  cbid:5373D73831ECC743 usec:93874
----
O `audit-explain` ferramenta pode fazer o seguinte:

* Processe logs de auditoria simples ou compactados. Por exemplo:
+
`audit-explain audit.log`

+
`audit-explain 2019-08-12.txt.gz`

* Processe vários arquivos simultaneamente. Por exemplo:
+
`audit-explain audit.log 2019-08-12.txt.gz 2019-08-13.txt.gz`

+
`audit-explain /var/local/log/*`

* Aceitar entrada de um pipe, o que permite filtrar e pré-processar a entrada usando o `grep` comando ou outros meios. Por exemplo:
+
`grep SPUT audit.log | audit-explain`

+
`grep bucket-name audit.log | audit-explain`



Como os logs de auditoria podem ser muito grandes e lentos para analisar, você pode economizar tempo filtrando as partes que deseja examinar e executando `audit-explain` nas partes, em vez do arquivo inteiro.

[NOTE]
====
O `audit-explain` a ferramenta não aceita arquivos compactados como entrada canalizada. Para processar arquivos compactados, forneça seus nomes de arquivo como argumentos de linha de comando ou use o `zcat` ferramenta para descompactar os arquivos primeiro. Por exemplo:

`zcat audit.log.gz | audit-explain`

====
Use o `help (-h)` opção para ver as opções disponíveis. Por exemplo:

`$ audit-explain -h`

.Passos
. Efetue login no nó de administração principal:
+
.. Digite o seguinte comando: `ssh admin@_primary_Admin_Node_IP_`
.. Digite a senha listada no `Passwords.txt` arquivo.
.. Digite o seguinte comando para alternar para root: `su -`
.. Digite a senha listada no `Passwords.txt` arquivo.
+
Quando você está logado como root, o prompt muda de `$` para `#` .



. Digite o seguinte comando, onde `/var/local/log/audit.log` representa o nome e o local do arquivo ou arquivos que você deseja analisar:
+
`$ audit-explain /var/local/log/audit.log`

+
O `audit-explain` A ferramenta imprime interpretações legíveis por humanos de todas as mensagens no arquivo ou arquivos especificados.

+

NOTE: Para reduzir o comprimento das linhas e facilitar a leitura, os registros de data e hora não são exibidos por padrão.  Se você quiser ver os carimbos de data/hora, use o carimbo de data/hora(`-t` ) opção.


