---
permalink: audit/wdel-swift-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WDEL, Swift DELETE 
summary: Quando um cliente Swift emite uma transação DELETE, uma solicitação é feita para remover o objeto ou contêiner especificado.  Esta mensagem é emitida pelo servidor se a transação for bem-sucedida. 
---
= WDEL: Swift EXCLUIR
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um cliente Swift emite uma transação DELETE, uma solicitação é feita para remover o objeto ou contêiner especificado.  Esta mensagem é emitida pelo servidor se a transação for bem-sucedida.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
CBDI
 a| 
Identificador de bloco de conteúdo
 a| 
O identificador exclusivo do bloco de conteúdo solicitado.  Se o CBID for desconhecido, este campo será definido como 0.  Operações em contêineres não incluem este campo.



 a| 
CSIZ
 a| 
Tamanho do conteúdo
 a| 
O tamanho do objeto excluído em bytes.  Operações em contêineres não incluem este campo.



 a| 
HTRH
 a| 
Cabeçalho de solicitação HTTP
 a| 
Lista de nomes e valores de cabeçalhos de solicitações HTTP registrados, conforme selecionados durante a configuração.

 `X-Forwarded-For`é incluído automaticamente se estiver presente na solicitação e se o `X-Forwarded-For` valor é diferente do endereço IP do remetente da solicitação (campo de auditoria SAIP).



 a| 
MTME
 a| 
Última hora modificada
 a| 
O registro de data e hora do Unix, em microssegundos, indicando quando o objeto foi modificado pela última vez.



 a| 
RSLT
 a| 
Código de resultado
 a| 
Resultado da transação DELETE.  O resultado é sempre:

SUCS: Bem-sucedido



 a| 
SAIP
 a| 
Endereço IP do cliente solicitante
 a| 
O endereço IP do aplicativo cliente que fez a solicitação.



 a| 
SGRP
 a| 
Site (Grupo)
 a| 
Se presente, o objeto foi excluído no site especificado, que não é o site onde o objeto foi ingerido.



 a| 
TEMPO
 a| 
Tempo
 a| 
Tempo total de processamento da solicitação em microssegundos.



 a| 
TLIP
 a| 
Endereço IP do balanceador de carga confiável
 a| 
Se a solicitação foi roteada por um balanceador de carga confiável da Camada 7, o endereço IP do balanceador de carga.



 a| 
UUID
 a| 
Identificador Universalmente Único
 a| 
O identificador do objeto dentro do sistema StorageGRID .



 a| 
WACC
 a| 
ID da conta Swift
 a| 
O ID de conta exclusivo, conforme especificado pelo sistema StorageGRID .



 a| 
WCON
 a| 
Contêiner Swift
 a| 
O nome do contêiner Swift.



 a| 
WOBJ
 a| 
Objeto Swift
 a| 
O identificador de objeto Swift.  Operações em contêineres não incluem este campo.



 a| 
WUSR
 a| 
Usuário da conta Swift
 a| 
O nome de usuário da conta Swift que identifica exclusivamente o cliente que realiza a transação.

|===