---
permalink: ubuntu/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: Você deve alocar volumes de armazenamento em bloco para cada host. 
---
= Configurar armazenamento do host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve alocar volumes de armazenamento em bloco para cada host.

.Antes de começar
Você revisou os seguintes tópicos, que fornecem as informações necessárias para realizar esta tarefa:

* link:storage-and-performance-requirements.html["Requisitos de armazenamento e desempenho"]
* link:node-container-migration-requirements.html["Requisitos de migração do contêiner de nó"]


.Sobre esta tarefa
Ao alocar volumes de armazenamento em bloco (LUNs) para hosts, use as tabelas em "Requisitos de armazenamento" para determinar o seguinte:

* Número de volumes necessários para cada host (com base no número e nos tipos de nós que serão implantados naquele host)
* Categoria de armazenamento para cada volume (ou seja, Dados do Sistema ou Dados do Objeto)
* Tamanho de cada volume


Você usará essas informações, bem como o nome persistente atribuído pelo Linux a cada volume físico ao implantar nós StorageGRID no host.


NOTE: Você não precisa particionar, formatar ou montar nenhum desses volumes; você só precisa garantir que eles estejam visíveis para os hosts.


NOTE: Somente um LUN de dados de objeto é necessário para nós de armazenamento somente de metadados.

Evite usar arquivos de dispositivos especiais "brutos"(`/dev/sdb` , por exemplo) ao compor sua lista de nomes de volumes.  Esses arquivos podem mudar durante as reinicializações do host, o que afetará a operação correta do sistema.  Se você estiver usando iSCSI LUNs e Device Mapper Multipathing, considere usar aliases multipath no `/dev/mapper` diretório, especialmente se sua topologia SAN incluir caminhos de rede redundantes para o armazenamento compartilhado.  Alternativamente, você pode usar os softlinks criados pelo sistema em `/dev/disk/by-path/` para seus nomes de dispositivos persistentes.

Por exemplo:

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
Os resultados serão diferentes para cada instalação.

Atribua nomes amigáveis ​​a cada um desses volumes de armazenamento em bloco para simplificar a instalação inicial do StorageGRID e os procedimentos futuros de manutenção.  Se você estiver usando o driver multipath do mapeador de dispositivos para acesso redundante a volumes de armazenamento compartilhado, poderá usar o `alias` campo em seu `/etc/multipath.conf` arquivo.

Por exemplo:

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
Usar o campo de alias dessa forma faz com que os aliases apareçam como dispositivos de bloco no `/dev/mapper` diretório no host, permitindo que você especifique um nome amigável e facilmente validado sempre que uma operação de configuração ou manutenção exigir a especificação de um volume de armazenamento em bloco.

Se você estiver configurando o armazenamento compartilhado para oferecer suporte à migração de nós do StorageGRID e usar o Device Mapper Multipathing, você pode criar e instalar um `/etc/multipath.conf` em todos os hosts co-localizados.  Apenas certifique-se de usar um volume de armazenamento do Docker diferente em cada host.  Usar aliases e incluir o nome do host de destino no alias para cada LUN de volume de armazenamento do Docker tornará isso fácil de lembrar e é recomendado.


NOTE: O suporte ao Docker como mecanismo de contêiner para implantações somente de software está obsoleto. O Docker será substituído por outro mecanismo de contêiner em uma versão futura.

.Informações relacionadas
* link:storage-and-performance-requirements.html["Requisitos de armazenamento e desempenho"]
* link:node-container-migration-requirements.html["Requisitos de migração do contêiner de nó"]

