---
permalink: ubuntu/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure Docker storage volume 
summary: Antes de instalar o Docker, talvez seja necessário formatar o volume de armazenamento do Docker e montá-lo em /var/lib/docker. 
---
= Configurar o volume de armazenamento do mecanismo de contêiner
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o mecanismo de contêiner (Docker ou Podman), talvez seja necessário formatar o volume de armazenamento e montá-lo.


NOTE: O suporte ao Docker como mecanismo de contêiner para implantações somente de software está obsoleto. O Docker será substituído por outro mecanismo de contêiner em uma versão futura.

.Sobre esta tarefa
Você pode pular essas etapas se planeja usar armazenamento local para o volume de armazenamento do Docker e tiver espaço suficiente disponível na partição do host que contém `/var/lib` .

.Passos
. Crie um sistema de arquivos no volume de armazenamento do Docker:
+
[listing]
----
sudo mkfs.ext4 docker-storage-volume-device
----
. Monte o volume de armazenamento do Docker:
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount docker-storage-volume-device /var/lib/docker
----
. Adicione uma entrada para docker-storage-volume-device em /etc/fstab.
+
Esta etapa garante que o volume de armazenamento será remontado automaticamente após a reinicialização do host.


