---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: Você deve instalar o StorageGRID em todos os hosts de grade Ubuntu ou Debian. Para obter uma lista de versões suportadas, use a NetApp Interoperability Matrix Tool. 
---
= Instalar Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar o StorageGRID em todos os hosts de grade Ubuntu ou Debian. Para obter uma lista de versões suportadas, use a NetApp Interoperability Matrix Tool.

.Antes de começar
Certifique-se de que seu sistema operacional atenda aos requisitos mínimos de versão do kernel do StorageGRID, conforme listado abaixo.  Use o comando `uname -r` para obter a versão do kernel do seu sistema operacional ou consulte o fornecedor do seu sistema operacional.

*Observação:* O suporte para as versões 18.04 e 20.04 do Ubuntu foi descontinuado e será removido em uma versão futura.

[cols="1a,2a,3a"]
|===
| Versão do Ubuntu | Versão mínima do kernel | Nome do pacote do kernel 


 a| 
18.04.6 (obsoleto)
 a| 
5.4.0-150-genérico
 a| 
linux-image-5.4.0-150-generic/bionic-updates,bionic-security,agora 5.4.0-150.167~18.04.1



 a| 
20.04.5 (obsoleto)
 a| 
5.4.0-131-genérico
 a| 
linux-image-5.4.0-131-generic/focal-updates, agora 5.4.0-131.147



 a| 
22.04.1
 a| 
5.15.0-47-genérico
 a| 
linux-image-5.15.0-47-generic/jammy-updates,jammy-security,agora 5.15.0-47.51



 a| 
24,04
 a| 
6.8.0-31-genérico
 a| 
linux-image-6.8.0-31-generic/noble, agora 6.8.0-31.31

|===
*Observação:* O suporte para o Debian versão 11 foi descontinuado e será removido em uma versão futura.

[cols="1a,2a,2a"]
|===
| Versão Debian | Versão mínima do kernel | Nome do pacote do kernel 


 a| 
11 (obsoleto)
 a| 
5.10.0-18-amd64
 a| 
linux-image-5.10.0-18-amd64/stable, agora 5.10.150-1



 a| 
12
 a| 
6.1.0-9-amd64
 a| 
linux-image-6.1.0-9-amd64/stable, agora 6.1.27-1

|===
.Passos
. Instale o Linux em todos os hosts de grade físicos ou virtuais de acordo com as instruções do distribuidor ou seu procedimento padrão.
+

NOTE: Não instale nenhum ambiente de área de trabalho gráfico. Ao instalar o Ubuntu, você deve selecionar *utilitários padrão do sistema*. É recomendável selecionar *Servidor OpenSSH* para habilitar o acesso SSH aos seus hosts Ubuntu. Todas as outras opções podem permanecer desmarcadas.

. Certifique-se de que todos os hosts tenham acesso aos repositórios de pacotes do Ubuntu ou Debian.
. Se a troca estiver habilitada:
+
.. Execute o seguinte comando: `$ sudo swapoff --all`
.. Remova todas as entradas de swap de `/etc/fstab` para persistir as configurações.
+

NOTE: Não desabilitar completamente a troca pode reduzir severamente o desempenho.




