---
permalink: ubuntu/understanding-apparmor-profile-installation.html 
sidebar: sidebar 
keywords: how to install AppArmor profile 
summary: Se você estiver operando em um ambiente Ubuntu autoimplantado e usando o sistema de controle de acesso obrigatório AppArmor, os perfis do AppArmor associados aos pacotes que você instala no sistema base podem ser bloqueados pelos pacotes correspondentes instalados com StorageGRID. 
---
= Entenda a instalação do perfil do AppArmor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver operando em um ambiente Ubuntu autoimplantado e usando o sistema de controle de acesso obrigatório AppArmor, os perfis do AppArmor associados aos pacotes que você instala no sistema base podem ser bloqueados pelos pacotes correspondentes instalados com StorageGRID.

Por padrão, os perfis do AppArmor são instalados para pacotes que você instala no sistema operacional base.  Quando você executa esses pacotes do contêiner do sistema StorageGRID , os perfis do AppArmor são bloqueados.  Os pacotes base DHCP, MySQL, NTP e tcdump entram em conflito com o AppArmor, e outros pacotes base também podem entrar em conflito.

Você tem duas opções para lidar com perfis do AppArmor:

* Desabilite perfis individuais para os pacotes instalados no sistema base que se sobrepõem aos pacotes no contêiner do sistema StorageGRID .  Quando você desabilita perfis individuais, uma entrada aparece nos arquivos de log do StorageGRID indicando que o AppArmor está habilitado.
+
Use os seguintes comandos:

+
[listing]
----
sudo ln -s /etc/apparmor.d/<profile.name> /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/<profile.name>
----
+
*Exemplo:*

+
[listing]
----
sudo ln -s /etc/apparmor.d/bin.ping /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/bin.ping
----
* Desabilite o AppArmor completamente.  Para o Ubuntu 9.10 ou posterior, siga as instruções na comunidade online do Ubuntu: https://help.ubuntu.com/community/AppArmor#Disable_AppArmor_framework["Desativar AppArmor"^] .  Desabilitar completamente o AppArmor pode não ser possível em versões mais recentes do Ubuntu.
+
Depois de desabilitar o AppArmor, nenhuma entrada indicando que o AppArmor está habilitado aparecerá nos arquivos de log do StorageGRID .


