---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: Você deve manter seu sistema StorageGRID e serviços relacionados atualizados para se defender contra ataques. 
---
= Diretrizes de reforço para atualizações de software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve manter seu sistema StorageGRID e serviços relacionados atualizados para se defender contra ataques.



== Atualizações para o software StorageGRID

Sempre que possível, você deve atualizar o software StorageGRID para a versão principal mais recente ou para a versão principal anterior.  Manter o StorageGRID atualizado ajuda a reduzir o tempo em que vulnerabilidades conhecidas ficam ativas e reduz a área geral da superfície de ataque.  Além disso, as versões mais recentes do StorageGRID geralmente contêm recursos de reforço de segurança que não estão incluídos nas versões anteriores.

Consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de Interoperabilidade da NetApp"^] (IMT) para determinar qual versão do software StorageGRID você deve usar.  Quando um hotfix é necessário, a NetApp prioriza a criação de atualizações para as versões mais recentes.  Alguns patches podem não ser compatíveis com versões anteriores.

* Para baixar os lançamentos e hotfixes mais recentes do StorageGRID , acesse https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Downloads da NetApp : StorageGRID"^] .
* Para atualizar o software StorageGRID , consulte olink:../upgrade/performing-upgrade.html["instruções de atualização"] .
* Para aplicar um hotfix, consulte olink:../maintain/storagegrid-hotfix-procedure.html["Procedimento de correção do StorageGRID"] .




== Atualizações para serviços externos

Serviços externos podem ter vulnerabilidades que afetam o StorageGRID indiretamente. Você deve garantir que os serviços dos quais o StorageGRID depende sejam mantidos atualizados. Esses serviços incluem LDAP, KMS (ou servidor KMIP), DNS e NTP.

Para obter uma lista de versões suportadas, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .



== Atualizações para hipervisores

Se os seus nós StorageGRID estiverem em execução no VMware ou em outro hipervisor, você deverá garantir que o software e o firmware do hipervisor estejam atualizados.

Para obter uma lista de versões suportadas, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .



== *Atualizações para nós Linux*

Se os seus nós StorageGRID estiverem usando plataformas host Linux, você deverá garantir que as atualizações de segurança e as atualizações do kernel sejam aplicadas ao sistema operacional host.  Além disso, você deve aplicar atualizações de firmware ao hardware vulnerável quando essas atualizações estiverem disponíveis.

Para obter uma lista de versões suportadas, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .
