---
permalink: network/admin-network-requirements.html 
sidebar: sidebar 
keywords: admin network requirements, guidelines for admin network, aesl 
summary: A rede de administração é opcional.  Se você planeja configurar uma rede de administração, siga estes requisitos e diretrizes. 
---
= Requisitos de rede de administração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A rede de administração é opcional.  Se você planeja configurar uma rede de administração, siga estes requisitos e diretrizes.

Os usos típicos da Rede de Administração incluem conexões de gerenciamento, AutoSupport, KMS e conexões com servidores críticos, como NTP, DNS e LDAP, se essas conexões não forem fornecidas pela Rede de Grade ou Rede de Cliente.


NOTE: A rede de administração e o AESL podem ser exclusivos para cada nó, desde que os serviços de rede e clientes desejados estejam acessíveis.


NOTE: Você deve definir pelo menos uma sub-rede na rede de administração para habilitar conexões de entrada de sub-redes externas.  Rotas estáticas são geradas automaticamente em cada nó para cada sub-rede no AESL.
