---
permalink: network/linux-deployments.html 
sidebar: sidebar 
keywords: linux network, container engine, red hat enterprise linux rhel network, ubuntu network 
summary: Para eficiência, confiabilidade e segurança, o sistema StorageGRID é executado no Linux como uma coleção de mecanismos de contêiner.  A configuração de rede relacionada ao mecanismo de contêiner não é necessária em um sistema StorageGRID . 
---
= Implantações Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para eficiência, confiabilidade e segurança, o sistema StorageGRID é executado no Linux como uma coleção de mecanismos de contêiner.  A configuração de rede relacionada ao mecanismo de contêiner não é necessária em um sistema StorageGRID .

Use um dispositivo não vinculado, como um par VLAN ou Ethernet virtual (veth), para a interface de rede do contêiner.  Especifique este dispositivo como a interface de rede no arquivo de configuração do nó.


CAUTION: Não use dispositivos de ligação ou ponte diretamente como interface de rede do contêiner.  Isso pode impedir a inicialização do nó devido a um problema no kernel com o uso do macvlan com dispositivos de ligação e ponte no namespace do contêiner.

Veja as instruções de instalação paralink:../rhel/index.html["Red Hat Enterprise Linux"] oulink:../ubuntu/index.html["Ubuntu ou Debian"] implantações.



== Configuração de rede do host para implantações de mecanismo de contêiner

Antes de iniciar a implantação do StorageGRID em uma plataforma de mecanismo de contêiner, determine quais redes (grade, administrador, cliente) cada nó usará.  Você deve garantir que a interface de rede de cada nó esteja configurada na interface de host virtual ou física correta e que cada rede tenha largura de banda suficiente.



=== Hosts físicos

Se você estiver usando hosts físicos para dar suporte a nós de grade:

* Certifique-se de que todos os hosts usem a mesma interface de host para cada interface de nó.  Essa estratégia simplifica a configuração do host e permite a migração futura de nós.
* Obtenha um endereço IP para o próprio host físico.
+

NOTE: Uma interface física no host pode ser usada pelo próprio host e por um ou mais nós em execução no host.  Todos os endereços IP atribuídos ao host ou nós usando esta interface devem ser exclusivos.  O host e o nó não podem compartilhar endereços IP.

* Abra as portas necessárias para o host.
* Se você pretende usar interfaces VLAN no StorageGRID, o host deve ter uma ou mais interfaces de tronco que forneçam acesso às VLANs desejadas.  Essas interfaces podem ser passadas para o contêiner do nó como eth0, eth2 ou como interfaces adicionais.  Para adicionar interfaces de tronco ou acesso, consulte o seguinte:
+
** *RHEL (antes de instalar o nó)*:link:../rhel/creating-node-configuration-files.html["Criar arquivos de configuração de nó"]
** *Ubuntu ou Debian (antes de instalar o nó)*:link:../ubuntu/creating-node-configuration-files.html["Criar arquivos de configuração de nó"]
** *RHEL, Ubuntu ou Debian (após instalar o nó)*:link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux: Adicionar interfaces de tronco ou acesso a um nó"]






=== Recomendações de largura de banda mínima

A tabela a seguir fornece as recomendações mínimas de largura de banda da LAN para cada tipo de nó do StorageGRID e cada tipo de rede.  Você deve provisionar cada host físico ou virtual com largura de banda de rede suficiente para atender aos requisitos mínimos agregados de largura de banda para o número total e o tipo de nós StorageGRID que você planeja executar naquele host.

[cols="1a,1a,1a,1a"]
|===
| Tipo de nó 3+| Tipo de rede 


 a| 
 a| 
Grade
 a| 
Administrador
 a| 
Cliente



 a| 
 a| 
*Largura de banda mínima da LAN*



 a| 
Administrador
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
1 Gbps



 a| 
Portal
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps



 a| 
Armazenar
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps



 a| 
Arquivo
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps

|===

NOTE: Esta tabela não inclui a largura de banda SAN, que é necessária para acessar o armazenamento compartilhado.  Se estiver usando armazenamento compartilhado acessado via Ethernet (iSCSI ou FCoE), você deverá provisionar interfaces físicas separadas em cada host para fornecer largura de banda SAN suficiente.  Para evitar a introdução de um gargalo, a largura de banda da SAN para um determinado host deve corresponder aproximadamente à largura de banda agregada da rede do nó de armazenamento para todos os nós de armazenamento em execução naquele host.

Use a tabela para determinar o número mínimo de interfaces de rede a serem provisionadas em cada host, com base no número e no tipo de nós StorageGRID que você planeja executar nesse host.

Por exemplo, para executar um nó de administração, um nó de gateway e um nó de armazenamento em um único host:

* Conecte as redes de grade e administração no nó de administração (requer 10 + 1 = 11 Gbps)
* Conecte a rede e as redes do cliente no nó de gateway (requer 10 + 10 = 20 Gbps)
* Conecte a rede de grade no nó de armazenamento (requer 10 Gbps)


Neste cenário, você deve fornecer um mínimo de 11 + 20 + 10 = 41 Gbps de largura de banda de rede, que pode ser atendida por duas interfaces de 40 Gbps ou cinco interfaces de 10 Gbps, potencialmente agregadas em troncos e então compartilhadas por três ou mais VLANs que transportam as sub-redes Grid, Admin e Client locais para o data center físico que contém o host.

Para algumas maneiras recomendadas de configurar recursos físicos e de rede nos hosts do seu cluster StorageGRID para se preparar para a implantação do StorageGRID , consulte o seguinte:

* link:../rhel/configuring-host-network.html["Configurar a rede do host (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html["Configurar a rede host (Ubuntu ou Debian)"]

