---
permalink: network/network-specific-requirements.html 
sidebar: sidebar 
keywords: network-specific requirements, network specific requirements, network requirements 
summary: Siga os requisitos para cada tipo de rede StorageGRID . 
---
= Requisitos específicos da rede
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga os requisitos para cada tipo de rede StorageGRID .



== Gateways e roteadores de rede

* Se definido, o gateway para uma determinada rede deve estar dentro da sub-rede da rede específica.
* Se você configurar uma interface usando endereçamento estático, deverá especificar um endereço de gateway diferente de 0.0.0.0.
* Se você não tiver um gateway, a melhor prática é definir o endereço do gateway como o endereço IP da interface de rede.




== Sub-redes


NOTE: Cada rede deve ser conectada à sua própria sub-rede que não se sobreponha a nenhuma outra rede no nó.

As seguintes restrições são aplicadas pelo Grid Manager durante a implantação.  Eles são fornecidos aqui para auxiliar no planejamento da rede de pré-implantação.

* A máscara de sub-rede para qualquer endereço IP de rede não pode ser 255.255.255.254 ou 255.255.255.255 (/31 ou /32 na notação CIDR).
* A sub-rede definida por um endereço IP de interface de rede e máscara de sub-rede (CIDR) não pode sobrepor a sub-rede de nenhuma outra interface configurada no mesmo nó.
* Não use sub-redes que contenham os seguintes endereços IPv4 para a Rede de Grade, Rede de Administração ou Rede de Cliente de qualquer nó:
+
** 192.168.130.101
** 192.168.131.101
** 192.168.130.102
** 192.168.131.102
** 198.51.100.2
** 198.51.100.4


+
Por exemplo, não use os seguintes intervalos de sub-rede para a Rede de Grade, Rede de Administração ou Rede de Cliente de nenhum nó:

+
** 192.168.130.0/24 porque este intervalo de sub-rede contém os endereços IP 192.168.130.101 e 192.168.130.102
** 192.168.131.0/24 porque este intervalo de sub-rede contém os endereços IP 192.168.131.101 e 192.168.131.102
** 198.51.100.0/24 porque este intervalo de sub-rede contém os endereços IP 198.51.100.2 e 198.51.100.4


* A sub-rede da rede de grade para cada nó deve ser incluída no GNSL.
* A sub-rede da rede de administração não pode sobrepor a sub-rede da rede de grade, a sub-rede da rede do cliente ou qualquer sub-rede no GNSL.
* As sub-redes no AESL não podem se sobrepor a nenhuma sub-rede no GNSL.
* A sub-rede da rede do cliente não pode sobrepor a sub-rede da rede da grade, a sub-rede da rede do administrador, nenhuma sub-rede no GNSL ou nenhuma sub-rede no AESL.




== Rede de grade

* No momento da implantação, cada nó da grade deve ser conectado à Rede da Grade e deve ser capaz de se comunicar com o Nó de Administração principal usando a configuração de rede especificada ao implantar o nó.
* Durante as operações normais da rede, cada nó da rede deve ser capaz de se comunicar com todos os outros nós da rede na rede.
+

NOTE: A rede Grid deve ser roteável diretamente entre cada nó.  A tradução de endereços de rede (NAT) entre nós não é suportada.

* Se a rede de grade consistir em várias sub-redes, adicione-as à Lista de sub-redes da rede de grade (GNSL).  Rotas estáticas são criadas em todos os nós para cada sub-rede no GNSL.
* Se a interface da Grid Network estiver configurada como um tronco para suportar interfaces VLAN, a VLAN nativa do tronco deverá ser a VLAN usada para o tráfego da Grid Network.  Todos os nós da grade devem ser acessíveis pela VLAN nativa do tronco.




== Rede de administração

A rede de administração é opcional.  Se você planeja configurar uma rede de administração, siga estes requisitos e diretrizes.

Os usos típicos da Rede de Administração incluem conexões de gerenciamento, AutoSupport, KMS e conexões com servidores críticos, como NTP, DNS e LDAP, se essas conexões não forem fornecidas pela Rede de Grade ou Rede de Cliente.


NOTE: A rede de administração e o AESL podem ser exclusivos para cada nó, desde que os serviços de rede e clientes desejados estejam acessíveis.


NOTE: Você deve definir pelo menos uma sub-rede na rede de administração para habilitar conexões de entrada de sub-redes externas.  Rotas estáticas são geradas automaticamente em cada nó para cada sub-rede no AESL.



== Rede de clientes

A Rede de Clientes é opcional.  Se você planeja configurar uma Rede de Cliente, observe as seguintes considerações.

* A Rede do Cliente foi projetada para suportar tráfego de clientes S3.  Se configurado, o gateway da rede do cliente se torna o gateway padrão do nó.
* Se você usar uma rede de cliente, poderá ajudar a proteger o StorageGRID de ataques hostis aceitando tráfego de cliente de entrada somente em pontos de extremidade do balanceador de carga configurados explicitamente. Ver link:../admin/configuring-load-balancer-endpoints.html["Configurar pontos de extremidade do balanceador de carga"] .
* Se a interface de rede do cliente estiver configurada como um tronco para oferecer suporte a interfaces VLAN, considere se é necessário configurar a interface de rede do cliente (eth2).  Se configurado, o tráfego da rede do cliente fluirá pela VLAN nativa do tronco, conforme configurado no switch.


.Informações relacionadas
link:../maintain/changing-nodes-network-configuration.html["Alterar configuração de rede do nó"]
