= Requisitos para buckets com bloqueio de objeto S3 habilitado
:allow-uri-read: 




== Requisitos para buckets com bloqueio de objeto S3 habilitado

* Se a configuração global do S3 Object Lock estiver habilitada para o sistema StorageGRID , você poderá usar o Tenant Manager, a Tenant Management API ou a S3 REST API para criar buckets com o S3 Object Lock habilitado.
* Se você planeja usar o S3 Object Lock, deverá habilitar o S3 Object Lock ao criar o bucket.  Não é possível habilitar o S3 Object Lock para um bucket existente.
* Quando o S3 Object Lock é habilitado para um bucket, o StorageGRID habilita automaticamente o controle de versão para esse bucket.  Não é possível desabilitar o bloqueio de objeto do S3 ou suspender o controle de versão do bucket.
* Opcionalmente, você pode especificar um modo de retenção padrão e um período de retenção para cada bucket usando o Tenant Manager, a Tenant Management API ou a S3 REST API.  As configurações de retenção padrão do bucket se aplicam somente a novos objetos adicionados ao bucket que não têm suas próprias configurações de retenção.  Você pode substituir essas configurações padrão especificando um modo de retenção e retenção até a data para cada versão do objeto quando ele for carregado.
* A configuração do ciclo de vida do bucket é suportada para buckets com o S3 Object Lock habilitado.
* A replicação do CloudMirror não é suportada para buckets com S3 Object Lock habilitado.




== Requisitos para objetos em buckets com bloqueio de objeto S3 habilitado

* Para proteger uma versão do objeto, você pode especificar configurações de retenção padrão para o bucket ou especificar configurações de retenção para cada versão do objeto.  As configurações de retenção no nível do objeto podem ser especificadas usando o aplicativo cliente S3 ou a API REST do S3.
* As configurações de retenção se aplicam a versões de objetos individuais.  Uma versão de objeto pode ter uma configuração de retenção até a data e uma configuração de retenção legal, uma mas não a outra, ou nenhuma delas.  Especificar uma configuração de retenção até a data ou de retenção legal para um objeto protege apenas a versão especificada na solicitação.  Você pode criar novas versões do objeto, enquanto a versão anterior do objeto permanece bloqueada.




== Ciclo de vida de objetos em buckets com bloqueio de objeto S3 habilitado

Cada objeto salvo em um bucket com o S3 Object Lock habilitado passa por estas etapas:

. *Ingestão de objetos*
+
Quando uma versão de objeto é adicionada ao bucket que tem o S3 Object Lock ativado, as configurações de retenção são aplicadas da seguinte maneira:

+
** Se as configurações de retenção forem especificadas para o objeto, as configurações no nível do objeto serão aplicadas.  Todas as configurações de bucket padrão são ignoradas.
** Se nenhuma configuração de retenção for especificada para o objeto, as configurações de bucket padrão serão aplicadas, se existirem.
** Se nenhuma configuração de retenção for especificada para o objeto ou o bucket, o objeto não será protegido pelo S3 Object Lock.


+
Se as configurações de retenção forem aplicadas, tanto o objeto quanto quaisquer metadados definidos pelo usuário do S3 serão protegidos.

. *Retenção e exclusão de objetos*
+
Várias cópias de cada objeto protegido são armazenadas pelo StorageGRID pelo período de retenção especificado.  O número exato e o tipo de cópias de objetos e os locais de armazenamento são determinados pelas regras de conformidade nas políticas ativas do ILM.  Se um objeto protegido pode ser excluído antes que sua data de retenção seja atingida depende do seu modo de retenção.

+
** Se um objeto estiver sob retenção legal, ninguém poderá excluí-lo, independentemente do seu modo de retenção.



