---
permalink: tenant/configuring-cloudmirror-replication.html 
sidebar: sidebar 
keywords: how to configure CloudMirror replication, replication xml 
summary: Você habilita a replicação do CloudMirror para um bucket criando um XML de configuração de replicação de bucket e usando o Tenant Manager para aplicar o XML ao bucket. 
---
= Configurar a replicação do CloudMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para habilitar a replicação do CloudMirror para um bucket, crie e aplique um XML de configuração de replicação de bucket válido.

.Antes de começar
* Os serviços da plataforma foram habilitados para sua conta de locatário por um administrador do StorageGRID .
* Você já criou um bucket para atuar como fonte de replicação.
* O ponto de extremidade que você pretende usar como destino para a replicação do CloudMirror já existe e você tem seu URN.
* Você pertence a um grupo de usuários que tem olink:tenant-management-permissions.html["Gerenciar todos os buckets ou permissão de acesso root"] .  Essas permissões substituem as configurações de permissão em políticas de grupo ou bucket ao configurar o bucket usando o Gerenciador de Tenants.


.Sobre esta tarefa
A replicação do CloudMirror copia objetos de um bucket de origem para um bucket de destino especificado em um endpoint.

Para obter informações gerais sobre a replicação de bucket e como configurá-la, consulte https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html["Documentação do Amazon Simple Storage Service (S3): Replicando objetos"^] .  Para obter informações sobre como o StorageGRID implementa GetBucketReplication, DeleteBucketReplication e PutBucketReplication, consulte olink:../s3/operations-on-buckets.html["Operações em baldes"] .


NOTE: A replicação do CloudMirror tem semelhanças e diferenças importantes com o recurso de replicação entre grades.  Para saber mais, consultelink:../admin/grid-federation-compare-cgr-to-cloudmirror.html["Comparar a replicação entre grades e a replicação do CloudMirror"] .

Observe os seguintes requisitos e características ao configurar a replicação do CloudMirror:

* Ao criar e aplicar um XML de configuração de replicação de bucket válido, ele deve usar o URN de um ponto de extremidade de bucket do S3 para cada destino.
* A replicação não é suportada para buckets de origem ou destino com o S3 Object Lock habilitado.
* Se você habilitar a replicação do CloudMirror em um bucket que contém objetos, os novos objetos adicionados ao bucket serão replicados, mas os objetos existentes no bucket não serão replicados.  Você deve atualizar os objetos existentes para acionar a replicação.
* Se você especificar uma classe de armazenamento no XML de configuração de replicação, o StorageGRID usará essa classe ao executar operações no ponto de extremidade S3 de destino.  O ponto de extremidade de destino também deve suportar a classe de armazenamento especificada.  Certifique-se de seguir todas as recomendações fornecidas pelo fornecedor do sistema de destino.


.Passos
. Habilite a replicação para seu bucket de origem:
+
** Use um editor de texto para criar o XML de configuração de replicação necessário para habilitar a replicação, conforme especificado na API de replicação do S3.
** Ao configurar o XML:
+
*** Observe que o StorageGRID suporta apenas a V1 da configuração de replicação.  Isso significa que o StorageGRID não suporta o uso do `Filter` elemento para regras e segue as convenções V1 para exclusão de versões de objetos.  Consulte a documentação da Amazon sobre configuração de replicação para obter detalhes.
*** Use o URN de um ponto de extremidade do bucket S3 como destino.
*** Opcionalmente, adicione o `<StorageClass>` elemento e especifique um dos seguintes:
+
****  `STANDARD`: A classe de armazenamento padrão.  Se você não especificar uma classe de armazenamento ao carregar um objeto, o `STANDARD` classe de armazenamento é usada.
**** `STANDARD_IA`: (Padrão - acesso pouco frequente.)  Use esta classe de armazenamento para dados que são acessados com menos frequência, mas que ainda exigem acesso rápido quando necessário.
**** `REDUCED_REDUNDANCY`: Use esta classe de armazenamento para dados não críticos e reproduzíveis que podem ser armazenados com menos redundância do que os `STANDARD` classe de armazenamento.


*** Se você especificar um `Role` no XML de configuração ele será ignorado.  Este valor não é usado pelo StorageGRID.
+
[listing]
----
<ReplicationConfiguration>
    <Role></Role>
    <Rule>
        <Status>Enabled</Status>
        <Prefix>2020</Prefix>
        <Destination>
           <Bucket>urn:sgws:s3:::2017-records</Bucket>
           <StorageClass>STANDARD</StorageClass>
         </Destination>
     </Rule>
</ReplicationConfiguration>
----




. Selecione *Exibir buckets* no painel ou selecione *ARMAZENAMENTO (S3)* > *Buckets*.
. Selecione o nome do bucket de origem.
+
A página de detalhes do bucket é exibida.

. Selecione *Serviços de plataforma* > *Replicação*.
. Marque a caixa de seleção *Ativar replicação*.
. Cole o XML de configuração de replicação na caixa de texto e selecione *Salvar alterações*.
+

NOTE: Os serviços da plataforma devem ser habilitados para cada conta de locatário por um administrador do StorageGRID usando o Grid Manager ou a API de gerenciamento de grade.  Entre em contato com o administrador do StorageGRID se ocorrer um erro ao salvar o XML de configuração.

. Verifique se a replicação está configurada corretamente:
+
.. Adicione um objeto ao bucket de origem que atenda aos requisitos de replicação, conforme especificado na configuração de replicação.
+
No exemplo mostrado anteriormente, os objetos que correspondem ao prefixo "2020" são replicados.

.. Confirme se o objeto foi replicado para o bucket de destino.
+
Para objetos pequenos, a replicação acontece rapidamente.





.Informações relacionadas
link:creating-platform-services-endpoint.html["Criar ponto de extremidade de serviços de plataforma"]
