---
permalink: tenant/configuring-platform-services-endpoints.html 
sidebar: sidebar 
keywords: how to configure platform services endpoint 
summary: Antes de configurar um serviço de plataforma para um bucket, você deve configurar pelo menos um endpoint para ser o destino do serviço de plataforma. 
---
= Configurar pontos de extremidade de serviços de plataforma
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de configurar um serviço de plataforma para um bucket, você deve configurar pelo menos um endpoint para ser o destino do serviço de plataforma.

O acesso aos serviços da plataforma é habilitado por locatário por um administrador do StorageGRID .  Para criar ou usar um ponto de extremidade de serviços de plataforma, você deve ser um usuário locatário com permissão de acesso Gerenciar pontos de extremidade ou Raiz, em uma grade cuja rede foi configurada para permitir que os Nós de Armazenamento acessem recursos de ponto de extremidade externos.  Para um único locatário, você pode configurar no máximo 500 pontos de extremidade de serviços de plataforma.  Entre em contato com o administrador do StorageGRID para obter mais informações.



== O que é um ponto de extremidade de serviços de plataforma?

Um ponto de extremidade de serviços de plataforma especifica as informações que o StorageGRID precisa para acessar o destino externo.

Por exemplo, se você quiser replicar objetos de um bucket do StorageGRID para um bucket do Amazon S3, crie um ponto de extremidade de serviços de plataforma que inclua as informações e credenciais que o StorageGRID precisa para acessar o bucket de destino na Amazon.

Cada tipo de serviço de plataforma requer seu próprio ponto de extremidade, portanto, você deve configurar pelo menos um ponto de extremidade para cada serviço de plataforma que planeja usar.  Depois de definir um ponto de extremidade de serviços de plataforma, use o URN do ponto de extremidade como destino no XML de configuração usado para habilitar o serviço.

Você pode usar o mesmo ponto de extremidade como destino para mais de um bucket de origem.  Por exemplo, você pode configurar vários buckets de origem para enviar metadados de objetos ao mesmo ponto de extremidade de integração de pesquisa para que você possa realizar pesquisas em vários buckets.  Você também pode configurar um bucket de origem para usar mais de um endpoint como destino, o que permite fazer coisas como enviar notificações sobre a criação de objetos para um tópico do Amazon Simple Notification Service (Amazon SNS) e notificações sobre a exclusão de objetos para um segundo tópico do Amazon SNS.



== Pontos de extremidade para replicação do CloudMirror

O StorageGRID oferece suporte a endpoints de replicação que representam buckets do S3.  Esses buckets podem ser hospedados no Amazon Web Services, na mesma implantação ou em uma implantação remota do StorageGRID ou em outro serviço.



== Pontos finais para notificações

O StorageGRID oferece suporte aos endpoints do Amazon SNS e do Kafka. Os endpoints do Simple Queue Service (SQS) ou do AWS Lambda não são suportados.

Para endpoints do Kafka, o TLS mútuo não é suportado. Como resultado, se você tiver `ssl.client.auth` definido para `required` na configuração do seu broker Kafka, isso pode causar problemas de configuração do endpoint Kafka.



== Pontos de extremidade para o serviço de integração de pesquisa

O StorageGRID oferece suporte a endpoints de integração de pesquisa que representam clusters do Elasticsearch.  Esses clusters do Elasticsearch podem estar em um data center local ou hospedados em uma nuvem AWS ou em outro lugar.

O ponto de extremidade de integração de pesquisa refere-se a um índice e tipo específicos do Elasticsearch.  Você deve criar o índice no Elasticsearch antes de criar o endpoint no StorageGRID, ou a criação do endpoint falhará.  Você não precisa criar o tipo antes de criar o ponto de extremidade.  O StorageGRID criará o tipo, se necessário, quando enviar metadados do objeto para o ponto de extremidade.

.Informações relacionadas
link:../admin/index.html["Administrar StorageGRID"]
