---
permalink: tenant/configuring-cross-origin-resource-sharing-cors.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors 
summary: 'Você pode configurar o compartilhamento de recursos de origem cruzada (CORS) para um bucket do S3 se quiser que esse bucket e os objetos nele sejam acessíveis a aplicativos da Web em outros domínios.' 
---
= Configurar compartilhamento de recursos de origem cruzada (CORS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o compartilhamento de recursos entre origens (CORS) para um bucket do S3 se quiser que esse bucket e os objetos nele sejam acessíveis a aplicativos da Web em outros domínios.

.Antes de começar
* Você está conectado ao Gerenciador de Inquilinos usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Para solicitações de configuração GET CORS, você pertence a um grupo de usuários que tem olink:tenant-management-permissions.html["Permissão para gerenciar todos os buckets ou visualizar todos os buckets"] . Essas permissões substituem as configurações de permissões em políticas de grupo ou bucket.
* Para solicitações de configuração PUT CORS, você pertence a um grupo de usuários que tem olink:tenant-management-permissions.html["Permissão para gerenciar todos os buckets"] .  Esta permissão substitui as configurações de permissões em políticas de grupo ou bucket.
* Olink:tenant-management-permissions.html["Permissão de acesso root"] fornece acesso a todas as solicitações de configuração do CORS.


.Sobre esta tarefa
O compartilhamento de recursos entre origens (CORS) é um mecanismo de segurança que permite que aplicativos web clientes em um domínio acessem recursos em um domínio diferente.  Por exemplo, suponha que você use um bucket S3 chamado `Images` para armazenar gráficos.  Ao configurar o CORS para o `Images` bucket, você pode permitir que as imagens nesse bucket sejam exibidas no site `+http://www.example.com+` .



== Habilitar CORS para um bucket

.Passos
. Use um editor de texto para criar o XML necessário.  Este exemplo mostra o XML usado para habilitar o CORS para um bucket S3.  Especificamente:
+
** Permite que qualquer domínio envie solicitações GET para o bucket
** Permite apenas o `+http://www.example.com+` domínio para enviar solicitações GET, POST e DELETE
** Todos os cabeçalhos de solicitação são permitidos
+
[listing]
----
<CORSConfiguration
    xmlns="http://s3.amazonaws.com/doc/2020-10-22/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://www.example.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
----
+
Para obter mais informações sobre o XML de configuração do CORS, consulte http://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html["Documentação da Amazon Web Services (AWS): Guia do usuário do Amazon Simple Storage Service"^] .



. Selecione *Exibir buckets* no painel ou selecione *ARMAZENAMENTO (S3)* > *Buckets*.
. Selecione o nome do bucket na tabela.
+
A página de detalhes do bucket é exibida.

. Na aba *Acesso ao bucket*, selecione o acordeão *Compartilhamento de recursos entre origens (CORS)*.
. Marque a caixa de seleção *Ativar CORS*.
. Cole o XML de configuração do CORS na caixa de texto.
. Selecione *Salvar alterações*.




== Modificar configuração CORS

.Passos
. Atualize o XML de configuração do CORS na caixa de texto ou selecione *Limpar* para recomeçar.
. Selecione *Salvar alterações*.




== Desabilitar configuração CORS

.Passos
. Desmarque a caixa de seleção *Ativar CORS*.
. Selecione *Salvar alterações*.

