---
permalink: tenant/creating-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to create platform services endpoint 
summary: Você deve criar pelo menos um ponto de extremidade do tipo correto antes de poder habilitar um serviço de plataforma. 
---
= Criar ponto de extremidade de serviços de plataforma
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar pelo menos um ponto de extremidade do tipo correto antes de poder habilitar um serviço de plataforma.

.Antes de começar
* Você está conectado ao Gerenciador de Inquilinos usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Os serviços da plataforma foram habilitados para sua conta de locatário por um administrador do StorageGRID .
* Você pertence a um grupo de usuários que tem olink:tenant-management-permissions.html["Gerenciar endpoints ou permissão de acesso root"] .
* O recurso referenciado pelo ponto de extremidade dos serviços da plataforma foi criado:
+
** Replicação do CloudMirror: bucket S3
** Notificação de evento: Amazon Simple Notification Service (Amazon SNS) ou tópico Kafka
** Notificação de pesquisa: índice do Elasticsearch, se o cluster de destino não estiver configurado para criar índices automaticamente.


* Você tem as informações sobre o recurso de destino:
+
** Host e porta para o Uniform Resource Identifier (URI)
+

NOTE: Se você planeja usar um bucket hospedado em um sistema StorageGRID como um ponto de extremidade para replicação do CloudMirror, entre em contato com o administrador da grade para determinar os valores que você precisa inserir.

** Nome de Recurso Único (URN)
+
link:specifying-urn-for-platform-services-endpoint.html["Especifique URN para o ponto de extremidade dos serviços de plataforma"]

** Credenciais de autenticação (se necessário):
+
[role="tabbed-block"]
====
.Pontos de extremidade de integração de pesquisa
--
Para endpoints de integração de pesquisa, você pode usar as seguintes credenciais:

*** Chave de acesso: ID da chave de acesso e chave de acesso secreta
*** HTTP básico: nome de usuário e senha


--
.Pontos de extremidade de replicação do CloudMirror
--
Para endpoints de replicação do CloudMirror, você pode usar as seguintes credenciais:

*** Chave de acesso: ID da chave de acesso e chave de acesso secreta
*** CAP (C2S Access Portal): URL de credenciais temporárias, certificados de servidor e cliente, chaves de cliente e uma senha de chave privada de cliente opcional.


--
.Pontos de extremidade do Amazon SNS
--
Para endpoints do Amazon SNS, você pode usar as seguintes credenciais:

*** Chave de acesso: ID da chave de acesso e chave de acesso secreta


--
.Pontos finais do Kafka
--
Para endpoints do Kafka, você pode usar as seguintes credenciais:

*** SASL/PLAIN: Nome de usuário e senha
*** SASL/SCRAM-SHA-256: Nome de usuário e senha
*** SASL/SCRAM-SHA-512: Nome de usuário e senha


--
====
** Certificado de segurança (se estiver usando um certificado CA personalizado)


* Se os recursos de segurança do Elasticsearch estiverem habilitados, você terá o privilégio de monitorar cluster para testes de conectividade e o privilégio de gravar índice ou os privilégios de indexar e excluir índice para atualizações de documentos.


.Passos
. Selecione *ARMAZENAMENTO (S3)* > *Pontos de extremidade de serviços de plataforma*.  A página de pontos de extremidade dos serviços da plataforma é exibida.
. Selecione *Criar ponto de extremidade*.
. Insira um nome de exibição para descrever brevemente o ponto de extremidade e sua finalidade.
+
O tipo de serviço de plataforma que o endpoint suporta é mostrado ao lado do nome do endpoint quando ele é listado na página Endpoints, portanto você não precisa incluir essa informação no nome.

. No campo *URI*, especifique o Identificador de Recurso Único (URI) do ponto de extremidade.
+
--
Use um dos seguintes formatos:

[listing]
----
https://host:port
http://host:port
----
Se você não especificar uma porta, as seguintes portas padrão serão usadas:

** Porta 443 para URIs HTTPS e porta 80 para URIs HTTP (a maioria dos endpoints)
** Porta 9092 para HTTPS e URIs HTTP (somente endpoints do Kafka)


--
+
Por exemplo, o URI para um bucket hospedado no StorageGRID pode ser:

+
[listing]
----
https://s3.example.com:10443
----
+
Neste exemplo, `s3.example.com` representa a entrada DNS para o IP virtual (VIP) do grupo de alta disponibilidade (HA) do StorageGRID e `10443` representa a porta definida no ponto de extremidade do balanceador de carga.

+

NOTE: Sempre que possível, você deve se conectar a um grupo HA de nós de balanceamento de carga para evitar um único ponto de falha.

+
Da mesma forma, o URI para um bucket hospedado na AWS pode ser:

+
[listing]
----
https://s3-aws-region.amazonaws.com
----
+

NOTE: Se o ponto de extremidade for usado para o serviço de replicação do CloudMirror, não inclua o nome do bucket no URI.  Inclua o nome do bucket no campo *URN*.

. Insira o Nome de Recurso Exclusivo (URN) para o ponto de extremidade.
+

NOTE: Não é possível alterar o URN de um endpoint depois que ele for criado.

. Selecione *Continuar*.
. Selecione um valor para *Tipo de autenticação*.
+
[role="tabbed-block"]
====
.Pontos de extremidade de integração de pesquisa
--
Insira ou carregue as credenciais para um ponto de extremidade de integração de pesquisa.

As credenciais fornecidas devem ter permissões de gravação para o recurso de destino.

[cols="1a,2a,2a"]
|===
| Tipo de autenticação | Descrição | Credenciais 


 a| 
Anônimo
 a| 
Fornece acesso anônimo ao destino.  Funciona somente para endpoints que tenham a segurança desabilitada.
 a| 
Sem autenticação.



 a| 
Chave de acesso
 a| 
Usa credenciais no estilo AWS para autenticar conexões com o destino.
 a| 
** ID da chave de acesso
** Chave de acesso secreta




 a| 
HTTP básico
 a| 
Usa um nome de usuário e uma senha para autenticar conexões com o destino.
 a| 
** Nome de usuário
** Senha


|===
--
.Pontos de extremidade de replicação do CloudMirror
--
Insira ou carregue as credenciais para um ponto de extremidade de replicação do CloudMirror.

As credenciais fornecidas devem ter permissões de gravação para o recurso de destino.

[cols="1a,2a,2a"]
|===
| Tipo de autenticação | Descrição | Credenciais 


 a| 
Anônimo
 a| 
Fornece acesso anônimo ao destino.  Funciona somente para endpoints que tenham a segurança desabilitada.
 a| 
Sem autenticação.



 a| 
Chave de acesso
 a| 
Usa credenciais no estilo AWS para autenticar conexões com o destino.
 a| 
** ID da chave de acesso
** Chave de acesso secreta




 a| 
CAP (Portal de Acesso C2S)
 a| 
Usa certificados e chaves para autenticar conexões com o destino.
 a| 
** URL de credenciais temporárias
** Certificado CA do servidor (upload de arquivo PEM)
** Certificado do cliente (upload de arquivo PEM)
** Chave privada do cliente (upload de arquivo PEM, formato criptografado OpenSSL ou formato de chave privada não criptografada)
** Senha da chave privada do cliente (opcional)


|===
--
.Pontos de extremidade do Amazon SNS
--
Insira ou carregue as credenciais para um endpoint do Amazon SNS.

As credenciais fornecidas devem ter permissões de gravação para o recurso de destino.

[cols="1a,2a,2a"]
|===
| Tipo de autenticação | Descrição | Credenciais 


 a| 
Anônimo
 a| 
Fornece acesso anônimo ao destino.  Funciona somente para endpoints que tenham a segurança desabilitada.
 a| 
Sem autenticação.



 a| 
Chave de acesso
 a| 
Usa credenciais no estilo AWS para autenticar conexões com o destino.
 a| 
** ID da chave de acesso
** Chave de acesso secreta


|===
--
.Pontos finais do Kafka
--
Insira ou carregue as credenciais para um ponto de extremidade do Kafka.

As credenciais fornecidas devem ter permissões de gravação para o recurso de destino.

[cols="1a,2a,2a"]
|===
| Tipo de autenticação | Descrição | Credenciais 


 a| 
Anônimo
 a| 
Fornece acesso anônimo ao destino.  Funciona somente para endpoints que tenham a segurança desabilitada.
 a| 
Sem autenticação.



 a| 
SASL/SIM
 a| 
Usa um nome de usuário e uma senha com texto simples para autenticar conexões com o destino.
 a| 
** Nome de usuário
** Senha




 a| 
SASL/SCRAM-SHA-256
 a| 
Usa um nome de usuário e uma senha usando um protocolo de desafio-resposta e hash SHA-256 para autenticar conexões com o destino.
 a| 
** Nome de usuário
** Senha




 a| 
SASL/SCRAM-SHA-512
 a| 
Usa um nome de usuário e uma senha usando um protocolo de desafio-resposta e hash SHA-512 para autenticar conexões com o destino.
 a| 
** Nome de usuário
** Senha


|===
Selecione *Usar autenticação de delegação* se o nome de usuário e a senha forem derivados de um token de delegação obtido de um cluster Kafka.

--
====
. Selecione *Continuar*.
. Selecione um botão de opção para *Verificar servidor* para escolher como a conexão TLS com o ponto de extremidade será verificada.
+
[cols="1a,2a"]
|===
| Tipo de verificação do certificado | Descrição 


 a| 
Usar certificado CA personalizado
 a| 
Use um certificado de segurança personalizado.  Se você selecionar esta configuração, copie e cole o certificado de segurança personalizado na caixa de texto *Certificado CA*.



 a| 
Usar certificado CA do sistema operacional
 a| 
Use o certificado Grid CA padrão instalado no sistema operacional para proteger conexões.



 a| 
Não verificar certificado
 a| 
O certificado usado para a conexão TLS não foi verificado.  Esta opção não é segura.

|===
. Selecione *Testar e criar ponto de extremidade*.
+
** Uma mensagem de sucesso será exibida se o ponto de extremidade puder ser alcançado usando as credenciais especificadas.  A conexão com o ponto de extremidade é validada a partir de um nó em cada site.
** Uma mensagem de erro será exibida se a validação do endpoint falhar.  Se você precisar modificar o endpoint para corrigir o erro, selecione *Retornar aos detalhes do endpoint* e atualize as informações.  Em seguida, selecione *Testar e criar endpoint*.
+

NOTE: A criação do endpoint falhará se os serviços da plataforma não estiverem habilitados para sua conta de locatário.  Entre em contato com o administrador do StorageGRID .





Depois de configurar um ponto de extremidade, você pode usar seu URN para configurar um serviço de plataforma.

.Informações relacionadas
* link:specifying-urn-for-platform-services-endpoint.html["Especifique URN para o ponto de extremidade dos serviços de plataforma"]
* link:configuring-cloudmirror-replication.html["Configurar a replicação do CloudMirror"]
* link:configuring-event-notifications.html["Configurar notificações de eventos"]
* link:configuring-search-integration-service.html["Configurar serviço de integração de pesquisa"]

