---
permalink: tenant/deleting-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete access key for other user 
summary: Se você estiver usando um locatário S3 e tiver permissões apropriadas, poderá excluir as chaves de acesso S3 de outro usuário.  Depois que uma chave de acesso é excluída, ela não pode mais ser usada para acessar os objetos e buckets na conta do locatário. 
---
= Excluir chaves de acesso S3 de outro usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando um locatário S3 e tiver permissões apropriadas, poderá excluir as chaves de acesso S3 de outro usuário.  Depois que uma chave de acesso é excluída, ela não pode mais ser usada para acessar os objetos e buckets na conta do locatário.

.Antes de começar
* Você está conectado ao Gerenciador de Inquilinos usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você tem olink:tenant-management-permissions.html["Permissão de acesso root"] .



CAUTION: Os buckets e objetos do S3 pertencentes a um usuário podem ser acessados usando o ID da chave de acesso e a chave de acesso secreta exibidas para esse usuário no Gerenciador de Tenants.  Por esse motivo, proteja as chaves de acesso como faria com uma senha.  Alterne as chaves de acesso regularmente, remova quaisquer chaves não utilizadas da conta e nunca as compartilhe com outros usuários.

.Passos
. Selecione *GERENCIAMENTO DE ACESSO* > *Usuários*.
. Na página Usuários, selecione o usuário cujas chaves de acesso S3 você deseja gerenciar.
. Na página Detalhes do usuário, selecione *Chaves de acesso* e marque a caixa de seleção de cada chave de acesso que deseja excluir.
. Selecione *Ações* > *Excluir chave selecionada*.
. Na caixa de diálogo de confirmação, selecione *Tecla Delete*.
+
Uma mensagem de confirmação aparece no canto superior direito da página.


