---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: 'Quando os administradores de grade criam as regras de gerenciamento do ciclo de vida das informações (ILM) para um sistema StorageGRID , eles podem, opcionalmente, especificar que o último horário de acesso de um objeto seja usado para determinar se esse objeto deve ser movido para um local de armazenamento diferente.  Se estiver usando um locatário do S3, você poderá aproveitar essas regras habilitando atualizações de horário do último acesso para os objetos em um bucket do S3.' 
---
= Habilitar ou desabilitar atualizações do último horário de acesso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando os administradores de grade criam as regras de gerenciamento do ciclo de vida das informações (ILM) para um sistema StorageGRID , eles podem, opcionalmente, especificar que o último horário de acesso de um objeto seja usado para determinar se esse objeto deve ser movido para um local de armazenamento diferente.  Se estiver usando um locatário do S3, você poderá aproveitar essas regras habilitando atualizações de horário do último acesso para os objetos em um bucket do S3.

Estas instruções se aplicam somente a sistemas StorageGRID que incluem pelo menos uma regra ILM que usa a opção *Último horário de acesso* como um filtro avançado ou como um horário de referência.  Você pode ignorar essas instruções se o seu sistema StorageGRID não incluir essa regra. Verlink:../ilm/using-last-access-time-in-ilm-rules.html["Usar a hora do último acesso nas regras do ILM"] para mais detalhes.

.Antes de começar
* Você está conectado ao Gerenciador de Inquilinos usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você pertence a um grupo de usuários que tem olink:tenant-management-permissions.html["Gerenciar todos os buckets ou permissão de acesso root"] . Essas permissões substituem as configurações de permissões em políticas de grupo ou bucket.


.Sobre esta tarefa
*Último horário de acesso* é uma das opções disponíveis para a instrução de posicionamento *Horário de referência* para uma regra ILM.  Definir o Tempo de referência para uma regra como Hora do último acesso permite que os administradores da grade especifiquem que os objetos sejam colocados em determinados locais de armazenamento com base em quando esses objetos foram recuperados (lidos ou visualizados) pela última vez.

Por exemplo, para garantir que objetos visualizados recentemente permaneçam em um armazenamento mais rápido, um administrador de grade pode criar uma regra ILM especificando o seguinte:

* Objetos recuperados no mês passado devem permanecer nos nós de armazenamento locais.
* Objetos que não foram recuperados no último mês devem ser movidos para um local externo.


Por padrão, as atualizações do último horário de acesso são desabilitadas.  Se o seu sistema StorageGRID incluir uma regra ILM que usa a opção *Último horário de acesso* e você quiser que essa opção se aplique a objetos neste bucket, você deverá habilitar atualizações para o último horário de acesso para os buckets do S3 especificados nessa regra.


CAUTION: Atualizar o último horário de acesso quando um objeto é recuperado pode reduzir o desempenho do StorageGRID , especialmente para objetos pequenos.

Um impacto no desempenho ocorre com as atualizações do último horário de acesso porque o StorageGRID deve executar estas etapas adicionais sempre que os objetos são recuperados:

* Atualizar os objetos com novos registros de data e hora
* Adicione os objetos à fila do ILM para que eles possam ser reavaliados em relação às regras e políticas atuais do ILM


A tabela resume o comportamento aplicado a todos os objetos no bucket quando o último horário de acesso é desabilitado ou habilitado.

[cols="1a,1a,1a,1a,1a"]
|===


.2+| Tipo de solicitação 2+| Comportamento se o último horário de acesso estiver desabilitado (padrão) 2+| Comportamento se o último horário de acesso estiver habilitado 


| Último horário de acesso atualizado? | Objeto adicionado à fila de avaliação do ILM? | Último horário de acesso atualizado? | Objeto adicionado à fila de avaliação do ILM? 


 a| 
Solicitação para recuperar um objeto, sua lista de controle de acesso ou seus metadados
 a| 
Não
 a| 
Não
 a| 
Sim
 a| 
Sim



 a| 
Solicitação para atualizar os metadados de um objeto
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



 a| 
Solicitação para listar objetos ou versões de objetos
 a| 
Não
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
Solicitação para copiar um objeto de um bucket para outro
 a| 
* Não, para a cópia de origem
* Sim, para a cópia de destino

 a| 
* Não, para a cópia de origem
* Sim, para a cópia de destino

 a| 
* Sim, para a cópia de origem
* Sim, para a cópia de destino

 a| 
* Sim, para a cópia de origem
* Sim, para a cópia de destino




 a| 
Solicitação para concluir um upload multiparte
 a| 
Sim, para o objeto montado
 a| 
Sim, para o objeto montado
 a| 
Sim, para o objeto montado
 a| 
Sim, para o objeto montado

|===
.Passos
. Selecione *Exibir buckets* no painel ou selecione *ARMAZENAMENTO (S3)* > *Buckets*.
. Selecione o nome do bucket na tabela.
+
A página de detalhes do bucket é exibida.

. Na aba *Opções do bucket*, selecione o acordeão *Atualizações de hora do último acesso*.
. Habilitar ou desabilitar atualizações de horário do último acesso.
. Selecione *Salvar alterações*.

