---
permalink: tenant/guidelines-for-configuring-openldap-server.html 
sidebar: sidebar 
keywords: how to configure open ldap 
summary: Se você quiser usar um servidor OpenLDAP para federação de identidade, deverá configurar definições específicas no servidor OpenLDAP. 
---
= Diretrizes para configurar o servidor OpenLDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você quiser usar um servidor OpenLDAP para federação de identidade, deverá configurar definições específicas no servidor OpenLDAP.



== Sobreposições de membro e reintegração

As sobreposições memberof e refint devem ser habilitadas.  Para obter mais informações, consulte as instruções para manutenção de associação de grupo reverso no _Guia do administrador de software OpenLDAP_.



== Indexação

Você deve configurar os seguintes atributos OpenLDAP com as palavras-chave de índice especificadas:

[listing]
----
olcDbIndex: objectClass eq
olcDbIndex: uid eq,pres,sub
olcDbIndex: cn eq,pres,sub
olcDbIndex: entryUUID eq
----
Além disso, certifique-se de que os campos mencionados na ajuda para Nome de usuário sejam indexados para desempenho ideal.

Consulte as informações sobre manutenção de associação de grupo reverso no _Guia do administrador de software OpenLDAP_.
