---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'Uma conta de locatário permite que você use a API REST do Simple Storage Service (S3) ou a API REST do Swift para armazenar e recuperar objetos em um sistema StorageGRID .' 
---
= Use uma conta de inquilino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma conta de locatário permite que você use a API REST do Simple Storage Service (S3) ou a API REST do Swift para armazenar e recuperar objetos em um sistema StorageGRID .



== O que é uma conta de inquilino?

Cada conta de locatário tem seus próprios grupos federados ou locais, usuários, buckets S3 ou contêineres Swift e objetos.

Contas de locatário podem ser usadas para segregar objetos armazenados por diferentes entidades.  Por exemplo, várias contas de locatário podem ser usadas para qualquer um destes casos de uso:

* *Caso de uso corporativo:* Se o sistema StorageGRID estiver sendo usado dentro de uma empresa, o armazenamento de objetos da grade pode ser segregado pelos diferentes departamentos da organização.  Por exemplo, pode haver contas de inquilinos para o departamento de Marketing, o departamento de Suporte ao Cliente, o departamento de Recursos Humanos e assim por diante.
+

NOTE: Se você usar o protocolo de cliente S3, também poderá usar buckets e políticas de bucket do S3 para segregar objetos entre os departamentos de uma empresa. Você não precisa criar contas de inquilino separadas. Veja as instruções para implementaçãolink:../s3/bucket-and-group-access-policies.html["Buckets S3 e políticas de bucket"] para mais informações.

* *Caso de uso do provedor de serviços:* Se o sistema StorageGRID estiver sendo usado por um provedor de serviços, o armazenamento de objetos da grade poderá ser segregado pelas diferentes entidades que alugam o armazenamento.  Por exemplo, pode haver contas de inquilinos para a Empresa A, Empresa B, Empresa C e assim por diante.




== Como criar uma conta de inquilino

As contas de inquilino são criadas por umlink:../admin/managing-tenants.html["Administrador de grade StorageGRID usando o Grid Manager"] .  Ao criar uma conta de locatário, o administrador da grade especifica o seguinte:

* Informações básicas, incluindo nome do locatário, tipo de cliente (S3) e cota de armazenamento opcional.
* Permissões para a conta do locatário, como se a conta do locatário pode usar os serviços da plataforma S3, configurar sua própria fonte de identidade, usar o S3 Select ou usar uma conexão de federação de grade.
* O acesso root inicial para o locatário, com base no uso de grupos e usuários locais pelo sistema StorageGRID , federação de identidade ou logon único (SSO).


Além disso, os administradores de grade podem habilitar a configuração de Bloqueio de Objeto S3 para o sistema StorageGRID se as contas de locatário S3 precisarem estar em conformidade com os requisitos regulatórios.  Quando o Bloqueio de Objeto S3 está habilitado, todas as contas de locatário S3 podem criar e gerenciar buckets compatíveis.



=== Configurar locatários do S3

Depois de umlink:../admin/creating-tenant-account.html["A conta do locatário S3 foi criada"] , você pode acessar o Gerenciador de Inquilinos para executar tarefas como as seguintes:

* Configurar federação de identidade (a menos que a fonte de identidade seja compartilhada com a grade)
* Gerenciar grupos e usuários
* Use a federação de grade para clonagem de conta e replicação entre grades
* Gerenciar chaves de acesso S3
* Criar e gerenciar buckets S3
* Use os serviços da plataforma S3
* Use o S3 Select
* Monitorar o uso do armazenamento



TIP: Embora você possa criar e gerenciar buckets S3 com o Tenant Manager, você deve usar umlink:../s3/index.html["Cliente S3"] oulink:use-s3-console.html["Console S3"] para ingerir e gerenciar objetos.
