---
permalink: tenant/managing-s3-access-keys.html 
sidebar: sidebar 
keywords: how to manage s3 access key 
summary: Cada usuário de uma conta de locatário do S3 deve ter uma chave de acesso para armazenar e recuperar objetos no sistema StorageGRID .  Uma chave de acesso consiste em um ID de chave de acesso e uma chave de acesso secreta. 
---
= Gerenciar chaves de acesso S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada usuário de uma conta de locatário do S3 deve ter uma chave de acesso para armazenar e recuperar objetos no sistema StorageGRID .  Uma chave de acesso consiste em um ID de chave de acesso e uma chave de acesso secreta.

As chaves de acesso S3 podem ser gerenciadas da seguinte forma:

* Usuários que têm a permissão *Gerenciar suas próprias credenciais S3* podem criar ou remover suas próprias chaves de acesso S3.
* Usuários que têm a permissão *Acesso root* podem gerenciar as chaves de acesso para a conta root do S3 e todos os outros usuários.  As chaves de acesso root fornecem acesso total a todos os buckets e objetos para o locatário, a menos que sejam explicitamente desabilitadas por uma política de bucket.


O StorageGRID suporta autenticação Signature versão 2 e Signature versão 4.  O acesso entre contas não é permitido, a menos que seja explicitamente habilitado por uma política de bucket.
