---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 'Se você habilitou o Bloqueio de Objeto S3 ao criar o bucket, poderá editá-lo para alterar as configurações de retenção padrão.  Você pode habilitar (ou desabilitar) a retenção padrão e definir um modo e um período de retenção padrão.' 
---
= Atualizar retenção padrão do bloqueio de objeto S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você habilitou o Bloqueio de Objeto S3 ao criar o bucket, poderá editá-lo para alterar as configurações de retenção padrão.  Você pode habilitar (ou desabilitar) a retenção padrão e definir um modo e um período de retenção padrão.

.Antes de começar
* Você está conectado ao Gerenciador de Inquilinos usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você pertence a um grupo de usuários que tem olink:tenant-management-permissions.html["Gerenciar todos os buckets ou permissão de acesso root"] . Essas permissões substituem as configurações de permissões em políticas de grupo ou bucket.
* O S3 Object Lock está habilitado globalmente para seu sistema StorageGRID , e você habilitou o S3 Object Lock quando criou o bucket. Ver link:using-s3-object-lock.html["Use o S3 Object Lock para reter objetos"] .


.Passos
. Selecione *Exibir buckets* no painel ou selecione *ARMAZENAMENTO (S3)* > *Buckets*.
. Selecione o nome do bucket na tabela.
+
A página de detalhes do bucket é exibida.

. Na aba *Opções do Bucket*, selecione o acordeão *S3 Object Lock*.
. Opcionalmente, habilite ou desabilite a *Retenção padrão* para este bucket.
+
As alterações nessa configuração não se aplicam a objetos que já estão no bucket ou a quaisquer objetos que possam ter seus próprios períodos de retenção.

. Se *Retenção padrão* estiver habilitado, especifique um *Modo de retenção padrão* para o bucket.
+
[cols="1a,2a"]
|===
| Modo de retenção padrão | Descrição 


 a| 
Governança
 a| 
** Usuários com o `s3:BypassGovernanceRetention` permissão pode usar o `x-amz-bypass-governance-retention: true` cabeçalho de solicitação para ignorar as configurações de retenção.
** Esses usuários podem excluir uma versão do objeto antes que sua data de retenção seja atingida.
** Esses usuários podem aumentar, diminuir ou remover a data de retenção de um objeto.




 a| 
Conformidade
 a| 
** O objeto não pode ser excluído até que sua data de retenção seja atingida.
** A data de retenção do objeto pode ser aumentada, mas não diminuída.
** A data de retenção do objeto não pode ser removida até que essa data seja atingida.


*Observação*: o administrador da sua rede deve permitir que você use o modo de conformidade.

|===
. Se *Retenção padrão* estiver habilitado, especifique o *Período de retenção padrão* para o bucket.
+
O *Período de retenção padrão* indica por quanto tempo novos objetos adicionados a este bucket devem ser retidos, a partir do momento em que são ingeridos. Especifique um valor menor ou igual ao período máximo de retenção do locatário, conforme definido pelo administrador da grade.

+
Um período de retenção _máximo_, que pode ser um valor de 1 dia a 100 anos, é definido quando o administrador da grade cria o locatário.  Quando você define um período de retenção _padrão_, ele não pode exceder o valor definido para o período máximo de retenção.  Se necessário, peça ao administrador da sua rede para aumentar ou diminuir o período máximo de retenção.

. Selecione *Salvar alterações*.

