---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords: how to automate installation 
summary: Você pode usar a VMware OVF Tool para automatizar a implantação de nós de grade.  Você também pode automatizar a configuração do StorageGRID. 
---
= Automatize a instalação (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a VMware OVF Tool para automatizar a implantação de nós de grade.  Você também pode automatizar a configuração do StorageGRID.



== Automatizar a implantação de nós de grade

Use a ferramenta VMware OVF para automatizar a implantação de nós de grade.

.Antes de começar
* Você tem acesso a um sistema Linux/Unix com Bash 3.2 ou posterior.
* Você tem VMware vSphere com vCenter
* Você tem o VMware OVF Tool 4.1 instalado e configurado corretamente.
* Você sabe o nome de usuário e a senha para acessar o VMware vSphere usando a ferramenta OVF
* Você tem permissões suficientes para implantar VMs de arquivos OVF e ligá-las, além de permissões para criar volumes adicionais para anexar às VMs.  Veja o `ovftool` documentação para mais detalhes.
* Você conhece a URL da infraestrutura virtual (VI) para o local no vSphere onde deseja implantar as máquinas virtuais StorageGRID .  Essa URL normalmente será um vApp ou um pool de recursos. Por exemplo:  `vi://vcenter.example.com/vi/sgws`
+

NOTE: Você pode usar o VMware `ovftool` utilitário para determinar este valor (veja o `ovftool` documentação para detalhes).

+

NOTE: Se você estiver implantando em um vApp, as máquinas virtuais não iniciarão automaticamente na primeira vez e você deverá ligá-las manualmente.

* Você coletou todas as informações necessárias para o arquivo de configuração de implantação.  Verlink:collecting-information-about-your-deployment-environment.html["Colete informações sobre seu ambiente de implantação"] para obter informações.
* Você tem acesso aos seguintes arquivos do arquivo de instalação do VMware para StorageGRID:


[cols="1a,1a"]
|===
| Nome do arquivo | Descrição 


| NetApp-SG-versão-SHA.vmdk  a| 
O arquivo de disco da máquina virtual que é usado como modelo para criar máquinas virtuais de nós de grade.

*Nota:* Este arquivo deve estar na mesma pasta que o `.ovf` e `.mf` arquivos.



| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
O arquivo de modelo do Open Virtualization Format(`.ovf` ) e arquivo de manifesto(`.mf` ) para implantar o nó de administração primário.



| vsphere-não-primário-admin.ovf vsphere-não-primário-admin.mf  a| 
O arquivo de modelo(`.ovf` ) e arquivo de manifesto(`.mf` ) para implantar nós administrativos não primários.



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
O arquivo de modelo(`.ovf` ) e arquivo de manifesto(`.mf` ) para implantar nós de gateway.



| vsphere-storage.ovf vsphere-storage.mf  a| 
O arquivo de modelo(`.ovf` ) e arquivo de manifesto(`.mf` ) para implantar nós de armazenamento baseados em máquina virtual.



| implantar-vsphere-ovftool.sh  a| 
O script de shell Bash usado para automatizar a implantação de nós de grade virtual.



| implantar-vsphere-ovftool-sample.ini  a| 
O arquivo de configuração de exemplo para uso com o `deploy-vsphere-ovftool.sh` roteiro.

|===


=== Defina o arquivo de configuração para sua implantação

Você especifica as informações necessárias para implantar nós de grade virtual para StorageGRID em um arquivo de configuração, que é usado pelo `deploy-vsphere-ovftool.sh` Script Bash.  Você pode modificar um arquivo de configuração de exemplo para não precisar criar o arquivo do zero.

.Passos
. Faça uma cópia do arquivo de configuração de exemplo(`deploy-vsphere-ovftool.sample.ini` ).  Salve o novo arquivo como `deploy-vsphere-ovftool.ini` no mesmo diretório que `deploy-vsphere-ovftool.sh` .
. Abrir `deploy-vsphere-ovftool.ini` .
. Insira todas as informações necessárias para implantar nós de grade virtual do VMware.
+
Ver<<configuration-file-settings,Configurações do arquivo de configuração>> para obter informações.

. Depois de inserir e verificar todas as informações necessárias, salve e feche o arquivo.




=== Configurações do arquivo de configuração

O `deploy-vsphere-ovftool.ini` O arquivo de configuração contém as configurações necessárias para implantar nós de grade virtual.

O arquivo de configuração primeiro lista os parâmetros globais e, em seguida, lista os parâmetros específicos do nó em seções definidas pelo nome do nó.  Quando o arquivo é usado:

* _Parâmetros globais_ são aplicados a todos os nós da grade.
* _Parâmetros específicos do nó_ substituem parâmetros globais.




==== Parâmetros globais

Os parâmetros globais são aplicados a todos os nós da grade, a menos que sejam substituídos por configurações em seções individuais.  Coloque os parâmetros que se aplicam a vários nós na seção de parâmetros globais e, em seguida, substitua essas configurações conforme necessário nas seções para nós individuais.

* *OVFTOOL_ARGUMENTS*: Você pode especificar OVFTOOL_ARGUMENTS como configurações globais ou pode aplicar argumentos individualmente a nós específicos. Por exemplo:
+
[listing, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=eagerZeroedThick --datastore='_datastore_name_'
----
+
Você pode usar o `--powerOffTarget` e `--overwrite` opções para desligar e substituir máquinas virtuais existentes.

+

CAUTION: Você deve implantar nós em diferentes armazenamentos de dados e especificar OVFTOOL_ARGUMENTS para cada nó, em vez de globalmente.

* *FONTE*: O caminho para o modelo de máquina virtual StorageGRID(`.vmdk` ) arquivo e o `.ovf` e `.mf` arquivos para nós de grade individuais.  O padrão é o diretório atual.
+
[listing, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* *TARGET*: A URL da infraestrutura virtual VMware vSphere (vi) para o local onde o StorageGRID será implantado. Por exemplo:
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* *GRID_NETWORK_CONFIG*: O método usado para adquirir endereços IP, ESTÁTICOS ou DHCP.  O padrão é ESTÁTICO.  Se todos ou a maioria dos nós usarem o mesmo método para adquirir endereços IP, você pode especificar esse método aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
GRID_NETWORK_CONFIG = STATIC
----
* *GRID_NETWORK_TARGET*: O nome de uma rede VMware existente a ser usada para a Grid Network.  Se todos ou a maioria dos nós usarem o mesmo nome de rede, você pode especificá-lo aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
GRID_NETWORK_TARGET = SG Admin Network
----
* *GRID_NETWORK_MASK*: A máscara de rede para a Rede Grid.  Se todos ou a maioria dos nós usarem a mesma máscara de rede, você pode especificá-la aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* *GRID_NETWORK_GATEWAY*: O gateway de rede para a Rede Grid.  Se todos ou a maioria dos nós usarem o mesmo gateway de rede, você pode especificá-lo aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* *GRID_NETWORK_MTU*: Opcional.  A unidade máxima de transmissão (MTU) na rede elétrica.  Se especificado, o valor deve estar entre 1280 e 9216. Por exemplo:
+
[listing]
----
GRID_NETWORK_MTU = 9000
----
+
Se omitido, 1400 será usado.

+
Se você quiser usar quadros jumbo, defina a MTU para um valor adequado para quadros jumbo, como 9000.  Caso contrário, mantenha o valor padrão.

+

NOTE: O valor de MTU da rede deve corresponder ao valor configurado na porta do switch virtual no vSphere ao qual o nó está conectado.  Caso contrário, podem ocorrer problemas de desempenho da rede ou perda de pacotes.

+

NOTE: Para obter o melhor desempenho da rede, todos os nós devem ser configurados com valores de MTU semelhantes em suas interfaces de rede de grade.  O alerta *Incompatibilidade de MTU da rede de grade* é acionado se houver uma diferença significativa nas configurações de MTU da rede de grade em nós individuais.  Os valores de MTU não precisam ser os mesmos para todos os tipos de rede.

* *ADMIN_NETWORK_CONFIG*: O método usado para adquirir endereços IP, DESATIVADO, ESTÁTICO ou DHCP.  O padrão é DESATIVADO.  Se todos ou a maioria dos nós usarem o mesmo método para adquirir endereços IP, você pode especificar esse método aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* *ADMIN_NETWORK_TARGET*: O nome de uma rede VMware existente a ser usada para a Rede de Administração.  Esta configuração é necessária, a menos que a Rede de Administração esteja desabilitada.  Se todos ou a maioria dos nós usarem o mesmo nome de rede, você pode especificá-lo aqui.  Ao contrário da Grid Network, todos os nós não precisam estar conectados à mesma Admin Network.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
ADMIN_NETWORK_TARGET = SG Admin Network
----
* *ADMIN_NETWORK_MASK*: A máscara de rede para a rede de administração.  Esta configuração é necessária se você estiver usando endereçamento IP estático.  Se todos ou a maioria dos nós usarem a mesma máscara de rede, você pode especificá-la aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* *ADMIN_NETWORK_GATEWAY*: O gateway de rede para a rede de administração.  Esta configuração é necessária se você estiver usando endereçamento IP estático e especificar sub-redes externas na configuração ADMIN_NETWORK_ESL.  (Ou seja, não é necessário se ADMIN_NETWORK_ESL estiver vazio.)  Se todos ou a maioria dos nós usarem o mesmo gateway de rede, você pode especificá-lo aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* *ADMIN_NETWORK_ESL*: A lista de sub-redes externas (rotas) para a Rede de Administração, especificada como uma lista separada por vírgulas de destinos de rotas CIDR.  Se todos ou a maioria dos nós usarem a mesma lista de sub-redes externas, você poderá especificá-la aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* *ADMIN_NETWORK_MTU*: Opcional.  A unidade máxima de transmissão (MTU) na rede de administração.  Não especifique se ADMIN_NETWORK_CONFIG = DHCP.  Se especificado, o valor deve estar entre 1280 e 9216.  Se omitido, 1400 será usado.  Se você quiser usar quadros jumbo, defina a MTU para um valor adequado para quadros jumbo, como 9000.  Caso contrário, mantenha o valor padrão.  Se todos ou a maioria dos nós usarem a mesma MTU para a Rede de Administração, você pode especificá-la aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* *CLIENT_NETWORK_CONFIG*: O método usado para adquirir endereços IP, DESATIVADO, ESTÁTICO ou DHCP.  O padrão é DESATIVADO.  Se todos ou a maioria dos nós usarem o mesmo método para adquirir endereços IP, você pode especificar esse método aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* *CLIENT_NETWORK_TARGET*: O nome de uma rede VMware existente a ser usada para a Rede do Cliente.  Esta configuração é necessária, a menos que a Rede do Cliente esteja desabilitada.  Se todos ou a maioria dos nós usarem o mesmo nome de rede, você pode especificá-lo aqui.  Ao contrário da Rede Grid, todos os nós não precisam estar conectados à mesma Rede Cliente.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
CLIENT_NETWORK_TARGET = SG Client Network
----
* *CLIENT_NETWORK_MASK*: A máscara de rede para a rede do cliente.  Esta configuração é necessária se você estiver usando endereçamento IP estático.  Se todos ou a maioria dos nós usarem a mesma máscara de rede, você pode especificá-la aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* *CLIENT_NETWORK_GATEWAY*: O gateway de rede para a Rede do Cliente.  Esta configuração é necessária se você estiver usando endereçamento IP estático.  Se todos ou a maioria dos nós usarem o mesmo gateway de rede, você pode especificá-lo aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* *CLIENT_NETWORK_MTU*: Opcional.  A unidade máxima de transmissão (MTU) na rede do cliente.  Não especifique se CLIENT_NETWORK_CONFIG = DHCP.  Se especificado, o valor deve estar entre 1280 e 9216.  Se omitido, 1400 será usado.  Se você quiser usar quadros jumbo, defina a MTU para um valor adequado para quadros jumbo, como 9000.  Caso contrário, mantenha o valor padrão.  Se todos ou a maioria dos nós usarem a mesma MTU para a Rede do Cliente, você pode especificá-la aqui.  Você pode então substituir a configuração global especificando configurações diferentes para um ou mais nós individuais. Por exemplo:
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* *PORT_REMAP*: Remapeia qualquer porta usada por um nó para comunicações internas do nó da grade ou comunicações externas.  O remapeamento de portas é necessário se as políticas de rede corporativa restringirem uma ou mais portas usadas pelo StorageGRID.  Para obter a lista de portas usadas pelo StorageGRID, consulte comunicações internas do nó da grade e comunicações externas emlink:../network/index.html["Diretrizes de rede"] .
+

NOTE: Não remapeie as portas que você planeja usar para configurar os pontos de extremidade do balanceador de carga.

+

NOTE: Se somente PORT_REMAP estiver definido, o mapeamento especificado será usado para comunicações de entrada e saída.  Se PORT_REMAP_INBOUND também for especificado, PORT_REMAP se aplicará somente às comunicações de saída.

+
O formato utilizado é: `_network type/protocol/default port used by grid node/new port_` , onde o tipo de rede é grade, administrador ou cliente, e o protocolo é tcp ou udp.

+
Por exemplo:

+
[listing]
----
PORT_REMAP = client/tcp/18082/443
----
+
Se usado sozinho, este exemplo de configuração mapeia simetricamente as comunicações de entrada e saída do nó da grade da porta 18082 para a porta 443.  Se usado em conjunto com PORT_REMAP_INBOUND, esta configuração de exemplo mapeia as comunicações de saída da porta 18082 para a porta 443.

+
Você também pode remapear várias portas usando uma lista separada por vírgulas.

+
Por exemplo:

+
[listing]
----
PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80
----
* *PORT_REMAP_INBOUND*: Remapeia as comunicações de entrada para a porta especificada.  Se você especificar PORT_REMAP_INBOUND, mas não especificar um valor para PORT_REMAP, as comunicações de saída para a porta permanecerão inalteradas.
+

NOTE: Não remapeie as portas que você planeja usar para configurar os pontos de extremidade do balanceador de carga.

+
O formato utilizado é: `_network type_/_protocol/_default port used by grid node_/_new port_` , onde o tipo de rede é grade, administrador ou cliente, e o protocolo é tcp ou udp.

+
Por exemplo:

+
[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
+
Este exemplo pega o tráfego enviado para a porta 443 para passar por um firewall interno e o direciona para a porta 18082, onde o nó da grade está escutando solicitações S3.

+
Você também pode remapear várias portas de entrada usando uma lista separada por vírgulas.

+
Por exemplo:

+
[listing]
----
PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22
----
* *TEMPORARY_PASSWORD_TYPE*: O tipo de senha de instalação temporária a ser usada ao acessar o console da VM ou a API de instalação do StorageGRID , ou usar SSH, antes que o nó ingresse na grade.
+

TIP: Se todos ou a maioria dos nós usarem o mesmo tipo de senha de instalação temporária, especifique o tipo na seção de parâmetros globais.  Então, opcionalmente, use uma configuração diferente para um nó individual.  Por exemplo, se você selecionar *Usar senha personalizada* globalmente, poderá usar *CUSTOM_TEMPORARY_PASSWORD=<senha>* para definir a senha para cada nó.

+
*TEMPORARY_PASSWORD_TYPE* pode ser um dos seguintes:

+
** *Usar nome do nó*: O nome do nó é usado como senha de instalação temporária e fornece acesso ao console da VM, à API de instalação do StorageGRID e ao SSH.
** *Desabilitar senha*: Nenhuma senha de instalação temporária será usada.  Se você precisar acessar a VM para depurar problemas de instalação, consultelink:troubleshooting-installation-issues.html["Solucionar problemas de instalação"] .
** *Usar senha personalizada*: O valor fornecido com *CUSTOM_TEMPORARY_PASSWORD=<password>* é usado como senha de instalação temporária e fornece acesso ao console da VM, à API de instalação do StorageGRID e ao SSH.
+

TIP: Opcionalmente, você pode omitir o parâmetro *TEMPORARY_PASSWORD_TYPE* e especificar apenas *CUSTOM_TEMPORARY_PASSWORD=<password>*.



* *CUSTOM_TEMPORARY_PASSWORD=<senha>* Opcional.  A senha temporária a ser usada durante a instalação ao acessar o console da VM, a API de instalação do StorageGRID e o SSH.  Ignorado se *TEMPORARY_PASSWORD_TYPE* ​​estiver definido como *Usar nome do nó* ou *Desativar senha*.




==== Parâmetros específicos do nó

Cada nó está em sua própria seção do arquivo de configuração.  Cada nó requer as seguintes configurações:

* O cabeçalho da seção define o nome do nó que será exibido no Grid Manager.  Você pode substituir esse valor especificando o parâmetro opcional NODE_NAME para o nó.
* *NODE_TYPE*: VM_Admin_Node, VM_Storage_Node ou VM_API_Gateway_Node
* *STORAGE_TYPE*: combinado, dados ou metadados.  Este parâmetro opcional para nós de armazenamento assume como padrão o valor combinado (dados e metadados) se não for especificado. Para obter mais informações, consulte link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipos de nós de armazenamento"] .
* *GRID_NETWORK_IP*: O endereço IP do nó na rede Grid.
* *ADMIN_NETWORK_IP*: O endereço IP do nó na rede de administração.  Obrigatório somente se o nó estiver conectado à rede de administração e ADMIN_NETWORK_CONFIG estiver definido como STATIC.
* *CLIENT_NETWORK_IP*: O endereço IP do nó na rede do cliente.  Obrigatório somente se o nó estiver conectado à rede do cliente e CLIENT_NETWORK_CONFIG para este nó estiver definido como STATIC.
* *ADMIN_IP*: O endereço IP do nó de administração primário na rede Grid.  Use o valor especificado como GRID_NETWORK_IP para o nó de administração primário.  Se você omitir esse parâmetro, o nó tentará descobrir o IP do nó de administração primário usando o mDNS. Para obter mais informações, consulte link:how-grid-nodes-discover-primary-admin-node.html["Como os nós da grade descobrem o nó administrativo principal"] .
+

NOTE: O parâmetro ADMIN_IP é ignorado para o nó de administração primário.

* Quaisquer parâmetros que não foram definidos globalmente.  Por exemplo, se um nó estiver anexado à Rede de Administração e você não tiver especificado os parâmetros ADMIN_NETWORK globalmente, será necessário especificá-los para o nó.


.Nó de administração primário
As seguintes configurações adicionais são necessárias para o nó de administração principal:

* *TIPO_NÓ*: Nó_Administrador_VM
* *ADMIN_ROLE*: Primário


Esta entrada de exemplo é para um nó de administração primário que está em todas as três redes:

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node
  TEMPORARY_PASSWORD_TYPE = Use custom password
  CUSTOM_TEMPORARY_PASSWORD = Passw0rd

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
A seguinte configuração adicional é opcional para o nó de administração principal:

* *DISCO*: Por padrão, os nós de administração recebem dois discos rígidos adicionais de 200 GB para auditoria e uso de banco de dados.  Você pode aumentar essas configurações usando o parâmetro DISK. Por exemplo:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: Para nós de administração, INSTÂNCIAS deve sempre ser igual a 2.

.Nó de armazenamento
A seguinte configuração adicional é necessária para nós de armazenamento:

* *TIPO_NÓ*: Nó_de_armazenamento_VM
+
Esta entrada de exemplo é para um nó de armazenamento que está nas redes de grade e de administração, mas não na rede do cliente.  Este nó usa a configuração ADMIN_IP para especificar o endereço IP do nó de administração principal na rede Grid.

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
Este segundo exemplo de entrada é para um nó de armazenamento em uma rede de cliente onde a política de rede corporativa do cliente declara que um aplicativo cliente S3 só tem permissão para acessar o nó de armazenamento usando a porta 80 ou 443.  O arquivo de configuração de exemplo usa PORT_REMAP para permitir que o nó de armazenamento envie e receba mensagens S3 na porta 443.

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
O último exemplo cria um remapeamento simétrico para o tráfego SSH da porta 22 para a porta 3022, mas define explicitamente os valores para o tráfego de entrada e saída.

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


As seguintes configurações adicionais são opcionais para nós de armazenamento:

* *DISCO*: Por padrão, os nós de armazenamento recebem três discos de 4 TB para uso do RangeDB.  Você pode aumentar essas configurações com o parâmetro DISK. Por exemplo:
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----
* *TIPO_DE_ARMAZENAMENTO*: Por padrão, todos os novos Nós de Armazenamento são configurados para armazenar dados de objetos e metadados, conhecidos como Nó de Armazenamento _combinado_.  Você pode alterar o tipo de nó de armazenamento para armazenar somente dados ou metadados com o parâmetro STORAGE_TYPE. Por exemplo:
+
[listing]
----
STORAGE_TYPE = data
----


.Nó de gateway
A seguinte configuração adicional é necessária para nós de gateway:

* *TIPO_NÓ*: VM_API_Gateway


Esta entrada de exemplo é para um nó de gateway de exemplo em todas as três redes.  Neste exemplo, nenhum parâmetro de rede do cliente foi especificado na seção global do arquivo de configuração, portanto, eles devem ser especificados para o nó:

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG Client Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----
.Nó de administração não primário
As seguintes configurações adicionais são necessárias para nós administrativos não primários:

* *TIPO_NÓ*: Nó_Administrador_VM
* *ADMIN_ROLE*: Não primário


Esta entrada de exemplo é para um nó de administração não primário que não está na rede do cliente:

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG Grid Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
A seguinte configuração adicional é opcional para nós administrativos não primários:

* *DISCO*: Por padrão, os nós de administração recebem dois discos rígidos adicionais de 200 GB para auditoria e uso de banco de dados.  Você pode aumentar essas configurações usando o parâmetro DISK. Por exemplo:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: Para nós de administração, INSTÂNCIAS deve sempre ser igual a 2.



== Execute o script Bash

Você pode usar o `deploy-vsphere-ovftool.sh` Script Bash e o arquivo de configuração deploy-vsphere-ovftool.ini que você modificou para automatizar a implantação de nós StorageGRID no VMware vSphere.

.Antes de começar
Você criou um arquivo de configuração deploy-vsphere-ovftool.ini para seu ambiente.

Você pode usar a ajuda disponível com o script Bash inserindo os comandos de ajuda(`-h/--help` ). Por exemplo:

[listing]
----
./deploy-vsphere-ovftool.sh -h
----
ou

[listing]
----
./deploy-vsphere-ovftool.sh --help
----
.Passos
. Efetue login na máquina Linux que você está usando para executar o script Bash.
. Mude para o diretório onde você extraiu o arquivo de instalação.
+
Por exemplo:

+
[listing]
----
cd StorageGRID-Webscale-version/vsphere
----
. Para implantar todos os nós da grade, execute o script Bash com as opções apropriadas para seu ambiente.
+
Por exemplo:

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----
. Se um nó de grade não puder ser implantado devido a um erro, resolva o erro e execute novamente o script Bash somente para esse nó.
+
Por exemplo:

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----


A implantação é concluída quando o status de cada nó é "Aprovado".

[listing]
----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----


== Automatize a configuração do StorageGRID

Após implantar os nós da grade, você pode automatizar a configuração do sistema StorageGRID .

.Antes de começar
* Você sabe a localização dos seguintes arquivos do arquivo de instalação.
+
[cols="1a,1a"]
|===
| Nome do arquivo | Descrição 


| configurar-storagegrid.py  a| 
Script Python usado para automatizar a configuração



| configurar-storagegrid.sample.json  a| 
Arquivo de configuração de exemplo para uso com o script



| configurar-storagegrid.blank.json  a| 
Arquivo de configuração em branco para uso com o script

|===
* Você criou um `configure-storagegrid.json` arquivo de configuração.  Para criar este arquivo, você pode modificar o arquivo de configuração de exemplo(`configure-storagegrid.sample.json` ) ou o arquivo de configuração em branco(`configure-storagegrid.blank.json` ).
+
Você pode usar o `configure-storagegrid.py` Script Python e o `configure-storagegrid.json` arquivo de configuração de grade para automatizar a configuração do seu sistema StorageGRID .

+

NOTE: Você também pode configurar o sistema usando o Grid Manager ou a API de instalação.



.Passos
. Faça login na máquina Linux que você está usando para executar o script Python.
. Mude para o diretório onde você extraiu o arquivo de instalação.
+
Por exemplo:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
onde `platform` é debs, rpms ou vsphere.

. Execute o script Python e use o arquivo de configuração que você criou.
+
Por exemplo:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Resultado
Um pacote de recuperação `.zip` O arquivo é gerado durante o processo de configuração e é baixado para o diretório onde você está executando o processo de instalação e configuração.  Você deve fazer backup do arquivo do pacote de recuperação para poder recuperar o sistema StorageGRID se um ou mais nós da grade falharem.  Por exemplo, copie-o para um local de rede seguro e com backup e para um local de armazenamento em nuvem seguro.


CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID .

Se você especificou que senhas aleatórias devem ser geradas, abra o `Passwords.txt` arquivo e procure as senhas necessárias para acessar seu sistema StorageGRID .

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Seu sistema StorageGRID estará instalado e configurado quando uma mensagem de confirmação for exibida.

[listing]
----
StorageGRID has been configured and installed.
----
.Informações relacionadas
* link:navigating-to-grid-manager.html["Navegue até o Gerenciador de Grade"]
* link:overview-of-installation-rest-api.html["Instalação REST API"]

