---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download vmware installation files 
summary: Você deve baixar os arquivos de instalação do StorageGRID e extrair os arquivos. Opcionalmente, você pode verificar manualmente os arquivos no pacote de instalação. 
---
= Baixe e extraia os arquivos de instalação do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve baixar os arquivos de instalação do StorageGRID e extrair os arquivos. Opcionalmente, você pode verificar manualmente os arquivos no pacote de instalação.

.Passos
. Vá para o https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Página de downloads da NetApp para StorageGRID"^] .
. Selecione o botão para baixar a versão mais recente ou selecione outra versão no menu suspenso e selecione *Ir*.
. Sign in com o nome de usuário e a senha da sua conta NetApp .
. Se uma declaração de Cuidado/Leitura Obrigatória aparecer, leia-a e marque a caixa de seleção.
+

CAUTION: Você deve aplicar todos os hotfixes necessários após instalar a versão do StorageGRID . Para mais informações, consulte olink:../maintain/storagegrid-hotfix-procedure.html["procedimento de hotfix nas instruções de recuperação e manutenção"]

. Leia o Contrato de Licença do Usuário Final, marque a caixa de seleção e selecione *Aceitar e Continuar*.
. Na coluna *Instalar StorageGRID*, selecione o arquivo de instalação .tgz ou .zip para o VMware.
+

NOTE: Use o `.zip` arquivo se você estiver executando o Windows no laptop de serviço.

. Salve o arquivo de instalação.
. [[vmware-download-verification-package]]Se você precisar verificar o arquivo de instalação:
+
.. Baixe o pacote de verificação de assinatura de código do StorageGRID .  O nome do arquivo para este pacote usa o formato `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz` , onde `<version-number>` é a versão do software StorageGRID .
.. Siga os passos paralink:../vmware/download-files-verify.html["verificar manualmente os arquivos de instalação"] .


. Extraia os arquivos do arquivo de instalação.
. Escolha os arquivos que você precisa.
+
Os arquivos necessários dependem da topologia de grade planejada e de como você implantará seu sistema StorageGRID .




NOTE: Os caminhos listados na tabela são relativos ao diretório de nível superior instalado pelo arquivo de instalação extraído.

[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./vsphere/LEIA-ME  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID .



| ./vsphere/NLF000000.txt  a| 
Uma licença gratuita que não fornece nenhum direito de suporte para o produto.



| ./vsphere/ NetApp-SG-versão-SHA.vmdk  a| 
O arquivo de disco da máquina virtual que é usado como modelo para criar máquinas virtuais de nós de grade.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
O arquivo de modelo do Open Virtualization Format(`.ovf` ) e arquivo de manifesto(`.mf` ) para implantar o nó de administração primário.



| ./vsphere/vsphere-não-primário-admin.ovf ./vsphere/vsphere-não-primário-admin.mf  a| 
O arquivo de modelo(`.ovf` ) e arquivo de manifesto(`.mf` ) para implantar nós administrativos não primários.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
O arquivo de modelo(`.ovf` ) e arquivo de manifesto(`.mf` ) para implantar nós de gateway.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
O arquivo de modelo(`.ovf` ) e arquivo de manifesto(`.mf` ) para implantar nós de armazenamento baseados em máquina virtual.



| Ferramenta de script de implantação | Descrição 


| ./vsphere/implantar-vsphere-ovftool.sh  a| 
Um script de shell Bash usado para automatizar a implantação de nós de grade virtual.



| ./vsphere/implantar-vsphere-ovftool-sample.ini  a| 
Um exemplo de arquivo de configuração para uso com o `deploy-vsphere-ovftool.sh` roteiro.



| ./vsphere/configure-storagegrid.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID .



| ./vsphere/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID .



| ./vsphere/storagegrid-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de gerenciamento de grade quando o logon único (SSO) estiver habilitado.  Você também pode usar este script para integração do Ping Federate.



| ./vsphere/configure-storagegrid.sample.json  a| 
Um exemplo de arquivo de configuração para uso com o `configure-storagegrid.py` roteiro.



| ./vsphere/configure-storagegrid.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` roteiro.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de gerenciamento de grade quando o logon único (SSO) estiver habilitado usando o Active Directory ou o Ping Federate.



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
Um script auxiliar chamado pelo companheiro `storagegrid-ssoauth-azure.py` Script Python para executar interações SSO com o Azure.



| ./vsphere/extras/esquemas-api  a| 
Esquemas de API para StorageGRID.

*Observação*: antes de executar uma atualização, você pode usar esses esquemas para confirmar se qualquer código que você escreveu para usar as APIs de gerenciamento do StorageGRID será compatível com a nova versão do StorageGRID , caso você não tenha um ambiente StorageGRID não produtivo para testes de compatibilidade de atualização.

|===