---
permalink: vmware/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation REST API 
summary: O StorageGRID fornece a API de instalação do StorageGRID para executar tarefas de instalação. 
---
= Instalação REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID fornece a API de instalação do StorageGRID para executar tarefas de instalação.

A API usa a plataforma de API de código aberto Swagger para fornecer a documentação da API.  O Swagger permite que desenvolvedores e não desenvolvedores interajam com a API em uma interface de usuário que ilustra como a API responde a parâmetros e opções.  Esta documentação pressupõe que você esteja familiarizado com tecnologias web padrão e o formato de dados JSON.


CAUTION: Todas as operações de API que você realiza usando a página de documentação da API são operações ativas.  Tenha cuidado para não criar, atualizar ou excluir dados de configuração ou outros dados por engano.

Cada comando da API REST inclui a URL da API, uma ação HTTP, quaisquer parâmetros de URL obrigatórios ou opcionais e uma resposta de API esperada.



== API de instalação do StorageGRID

A API de instalação do StorageGRID só estará disponível quando você estiver configurando inicialmente seu sistema StorageGRID e se precisar executar uma recuperação do nó de administração primário.  A API de instalação pode ser acessada via HTTPS a partir do Grid Manager.

Para acessar a documentação da API, vá para a página de instalação no nó de administração principal e selecione *Ajuda* > *Documentação da API* na barra de menu.

A API de instalação do StorageGRID inclui as seguintes seções:

* *config* — Operações relacionadas ao lançamento do produto e versões da API.  Você pode listar a versão de lançamento do produto e as principais versões da API suportadas por essa versão.
* *grid* -- Operações de configuração em nível de grade.  Você pode obter e atualizar as configurações da grade, incluindo detalhes da grade, sub-redes da rede da grade, senhas da grade e endereços IP dos servidores NTP e DNS.
* *nodes* -- Operações de configuração em nível de nó.  Você pode recuperar uma lista de nós de grade, excluir um nó de grade, configurar um nó de grade, visualizar um nó de grade e redefinir a configuração de um nó de grade.
* *provisão* -- Operações de provisionamento.  Você pode iniciar a operação de provisionamento e visualizar o status da operação de provisionamento.
* *recuperação* -- Operações de recuperação do nó de administração principal.  Você pode redefinir informações, carregar o Pacote de Recuperação, iniciar a recuperação e visualizar o status da operação de recuperação.
* *recovery-package* -- Operações para baixar o pacote de recuperação.
* *sites* -- Operações de configuração em nível de site.  Você pode criar, visualizar, excluir e modificar um site.
* *temporary-password* -- Operações na senha temporária para proteger a mgmt-api durante a instalação.

