---
permalink: vmware/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Você pode usar uma máquina virtual para hospedar qualquer tipo de nó StorageGRID .  Você precisa de uma máquina virtual para cada nó da grade. 
---
= Requisitos de software para VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar uma máquina virtual para hospedar qualquer tipo de nó StorageGRID .  Você precisa de uma máquina virtual para cada nó da grade.



== Hipervisor VMware vSphere

Você deve instalar o VMware vSphere Hypervisor em um servidor físico preparado.  O hardware deve ser configurado corretamente (incluindo versões de firmware e configurações de BIOS) antes de instalar o software VMware.

* Configure a rede no hipervisor conforme necessário para dar suporte à rede do sistema StorageGRID que você está instalando.
+
link:../network/index.html["Diretrizes de rede"]

* Certifique-se de que o armazenamento de dados seja grande o suficiente para as máquinas virtuais e os discos virtuais necessários para hospedar os nós da grade.
* Se você criar mais de um armazenamento de dados, nomeie cada armazenamento de dados para que você possa identificar facilmente qual armazenamento de dados usar para cada nó de grade ao criar máquinas virtuais.




== Requisitos de configuração do host ESX


CAUTION: Você deve configurar corretamente o protocolo de tempo de rede (NTP) em cada host ESX.  Se o horário do host estiver incorreto, poderão ocorrer efeitos negativos, incluindo perda de dados.



== Requisitos de configuração do VMware

Você deve instalar e configurar o VMware vSphere e o vCenter antes de implantar os nós do StorageGRID .

Para versões suportadas do software VMware vSphere Hypervisor e VMware vCenter Server, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .

Para saber as etapas necessárias para instalar esses produtos VMware, consulte a documentação da VMware.
