---
permalink: rhel/automating-installation.html 
sidebar: sidebar 
keywords: how to automate red hat linux installation 
summary: Você pode automatizar a instalação do serviço de host StorageGRID e a configuração dos nós da grade. 
---
= Automatize a instalação do StorageGRID no Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode automatizar a instalação do serviço de host StorageGRID e a configuração dos nós da grade.

Automatizar a implantação pode ser útil em qualquer um dos seguintes casos:

* Você já usa uma estrutura de orquestração padrão, como Ansible, Puppet ou Chef, para implantar e configurar hosts físicos ou virtuais.
* Você pretende implantar várias instâncias do StorageGRID .
* Você está implantando uma instância StorageGRID grande e complexa.


O serviço de host StorageGRID é instalado por um pacote e controlado por arquivos de configuração.  Você pode criar os arquivos de configuração usando um destes métodos:

* link:creating-node-configuration-files.html["Crie os arquivos de configuração"]interativamente durante uma instalação manual.
* Prepare os arquivos de configuração com antecedência (ou programaticamente) para permitir a instalação automatizada usando estruturas de orquestração padrão, conforme descrito neste artigo.
+
O StorageGRID fornece scripts Python opcionais para automatizar a configuração de dispositivos StorageGRID e de todo o sistema StorageGRID (a "grade").  Você pode usar esses scripts diretamente ou inspecioná-los para aprender como usá-los.link:overview-of-installation-rest-api.html["API REST de instalação do StorageGRID"] em ferramentas de implantação e configuração de grade que você mesmo desenvolve.





== Automatize a instalação e a configuração do serviço de host StorageGRID

Você pode automatizar a instalação do serviço de host StorageGRID usando estruturas de orquestração padrão, como Ansible, Puppet, Chef, Fabric ou SaltStack.

O serviço de host StorageGRID é empacotado em um RPM e é controlado por arquivos de configuração que você pode preparar com antecedência (ou programaticamente) para permitir a instalação automatizada.  Se você já usa uma estrutura de orquestração padrão para instalar e configurar o RHEL, adicionar o StorageGRID aos seus playbooks ou receitas deve ser simples.

Veja o exemplo de função e manual do Ansible no `/extras` pasta fornecida com o arquivo de instalação.  O manual do Ansible mostra como o `storagegrid` A função prepara o host e instala o StorageGRID nos servidores de destino.  Você pode personalizar a função ou o manual conforme necessário.


NOTE: O manual de exemplo não inclui as etapas necessárias para criar dispositivos de rede antes de iniciar o serviço de host StorageGRID .  Adicione estas etapas antes de finalizar e usar o manual.

Você pode automatizar todas as etapas de preparação dos hosts e implantação de nós de grade virtual.



=== Exemplo de função e manual do Ansible

Exemplo de função e manual do Ansible são fornecidos com o arquivo de instalação no `/extras` pasta.  O manual do Ansible mostra como o `storagegrid` A função prepara os hosts e instala o StorageGRID nos servidores de destino.  Você pode personalizar a função ou o manual conforme necessário.

As tarefas de instalação fornecidas `storagegrid` exemplo de função use o `ansible.builtin.dnf` módulo para executar a instalação a partir dos arquivos RPM locais ou de um repositório Yum remoto. Se o módulo não estiver disponível ou não for compatível, talvez seja necessário editar as tarefas Ansible apropriadas nos seguintes arquivos para usá-lo `yum` ou `ansible.builtin.yum` módulo:

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`




== Automatize a configuração do StorageGRID

Após implantar os nós da grade, você pode automatizar a configuração do sistema StorageGRID .

.Antes de começar
* Você sabe a localização dos seguintes arquivos do arquivo de instalação.
+
[cols="1a,1a"]
|===
| Nome do arquivo | Descrição 


| configurar-storagegrid.py  a| 
Script Python usado para automatizar a configuração



| configurar-storagegrid.sample.json  a| 
Arquivo de configuração de exemplo para uso com o script



| configurar-storagegrid.blank.json  a| 
Arquivo de configuração em branco para uso com o script

|===
* Você criou um `configure-storagegrid.json` arquivo de configuração.  Para criar este arquivo, você pode modificar o arquivo de configuração de exemplo(`configure-storagegrid.sample.json` ) ou o arquivo de configuração em branco(`configure-storagegrid.blank.json` ).


.Sobre esta tarefa
Você pode usar o `configure-storagegrid.py` Script Python e o `configure-storagegrid.json` arquivo de configuração para automatizar a configuração do seu sistema StorageGRID .


NOTE: Você também pode configurar o sistema usando o Grid Manager ou a API de instalação.

.Passos
. Faça login na máquina Linux que você está usando para executar o script Python.
. Mude para o diretório onde você extraiu o arquivo de instalação.
+
Por exemplo:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
onde `platform` é `debs` , `rpms` , ou `vsphere` .

. Execute o script Python e use o arquivo de configuração que você criou.
+
Por exemplo:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Resultado
Um pacote de recuperação `.zip` O arquivo é gerado durante o processo de configuração e é baixado para o diretório onde você está executando o processo de instalação e configuração.  Você deve fazer backup do arquivo do pacote de recuperação para poder recuperar o sistema StorageGRID se um ou mais nós da grade falharem.  Por exemplo, copie-o para um local de rede seguro e com backup e para um local de armazenamento em nuvem seguro.


CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID .

Se você especificou que senhas aleatórias seriam geradas, abra o `Passwords.txt` arquivo e procure as senhas necessárias para acessar seu sistema StorageGRID .

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Seu sistema StorageGRID estará instalado e configurado quando uma mensagem de confirmação for exibida.

[listing]
----
StorageGRID has been configured and installed.
----
.Informações relacionadas
link:overview-of-installation-rest-api.html["Instalação REST API"]
