---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: Alterar as senhas de acesso SSH para nós de administração também atualiza os conjuntos exclusivos de chaves SSH internas para cada nó na grade.  O nó de administração principal usa essas chaves SSH para acessar nós usando autenticação segura e sem senha. 
---
= Alterar senhas de acesso SSH para nós de administração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alterar as senhas de acesso SSH para nós de administração também atualiza os conjuntos exclusivos de chaves SSH internas para cada nó na grade.  O nó de administração principal usa essas chaves SSH para acessar nós usando autenticação segura e sem senha.

Use uma chave SSH para efetuar login em um nó como `admin` ou para o usuário root em uma VM ou conexão de console físico.

.Antes de começar
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você tem olink:admin-group-permissions.html["Permissão de acesso de manutenção ou root"] .
* Você tem a senha de provisionamento atual.


.Sobre esta tarefa
As novas senhas de acesso para os nós de administração e as novas chaves internas para cada nó são armazenadas no `Passwords.txt` arquivo no Pacote de Recuperação. As chaves estão listadas na coluna Senha desse arquivo.

Há senhas de acesso SSH separadas para as chaves SSH usadas para comunicação entre nós.  Elas não são alteradas por este procedimento.



== Acesse o assistente

.Passos
. Selecione *CONFIGURAÇÃO* > *Controle de acesso* > *Senhas de grade*.
. Em *Alterar chaves SSH*, selecione *Fazer uma alteração*.




== [[download-current]]Baixe o pacote de recuperação atual

Antes de alterar as chaves de acesso SSH, baixe o Pacote de Recuperação atual. Você pode usar as chaves neste arquivo se o processo de alteração de chave falhar para qualquer nó.

.Passos
. Digite a senha de provisionamento para sua grade.
. Selecione *Baixar pacote de recuperação*.
. Copie o arquivo do pacote de recuperação(`.zip` ) para dois locais seguros, protegidos e separados.
+

CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID .

. Selecione *Continuar*.
. Quando a caixa de diálogo de confirmação aparecer, selecione *Sim* se estiver pronto para começar a alterar as chaves de acesso SSH.
+

CAUTION: Você não pode cancelar este processo depois que ele for iniciado.





== Alterar chaves de acesso SSH

Quando o processo de alteração das chaves de acesso SSH é iniciado, um novo Pacote de Recuperação é gerado, incluindo as novas chaves. Em seguida, as chaves são atualizadas em cada nó.

.Passos
. Aguarde a geração do novo Pacote de Recuperação, o que pode levar alguns minutos.
. Quando o botão Baixar novo pacote de recuperação estiver habilitado, selecione *Baixar novo pacote de recuperação* e salve o novo arquivo do pacote de recuperação(`.zip` ) para dois locais seguros, protegidos e separados.
. Quando o download for concluído:
+
.. Abra o `.zip` arquivo.
.. Confirme se você pode acessar o conteúdo, incluindo o `Passwords.txt` arquivo, que contém as novas chaves de acesso SSH.
.. Copie o novo arquivo do pacote de recuperação(`.zip` ) para dois locais seguros, protegidos e separados.
+

CAUTION: Não substitua o antigo Pacote de Recuperação.

+
O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID .



. Aguarde a atualização das chaves em cada nó, o que pode levar alguns minutos.
+
Se as chaves forem alteradas para todos os nós, um banner verde de sucesso será exibido.

+
Se houver um erro durante o processo de atualização, uma mensagem de banner listará o número de nós que não tiveram suas chaves alteradas.  O sistema repetirá automaticamente o processo em qualquer nó cuja chave não tenha sido alterada.  Se o processo terminar com alguns nós ainda sem uma chave alterada, o botão *Repetir* será exibido.

+
Se a atualização da chave falhar para um ou mais nós:

+
.. Revise as mensagens de erro listadas na tabela.
.. Resolva os problemas.
.. Selecione *Repetir*.
+
Tentar novamente altera apenas as chaves de acesso SSH nos nós que falharam durante tentativas anteriores de alteração de chave.



. Após as chaves de acesso SSH terem sido alteradas para todos os nós, exclua o<<download-current,primeiro pacote de recuperação que você baixou>> .
. Opcionalmente, selecione *MANUTENÇÃO* > *Sistema* > *Pacote de recuperação* para baixar uma cópia adicional do novo Pacote de recuperação.

