---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords: change password, grid manager password 
summary: Se você for um usuário local do Grid Manager, poderá alterar sua própria senha. 
---
= Alterar sua senha
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você for um usuário local do Grid Manager, poderá alterar sua própria senha.

.Antes de começar
Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .

.Sobre esta tarefa
Se você fizer login no StorageGRID como um usuário federado ou se o logon único (SSO) estiver habilitado, não será possível alterar sua senha no Grid Manager.  Em vez disso, você deve alterar sua senha na fonte de identidade externa, por exemplo, Active Directory ou OpenLDAP.

.Passos
. No cabeçalho do Grid Manager, selecione *_seu nome_* > *Alterar senha*.
. Digite sua senha atual.
. Digite uma nova senha.
+
Sua senha deve conter no mínimo 8 e no máximo 32 caracteres.  As senhas diferenciam maiúsculas de minúsculas.

. Digite novamente a nova senha.
. Selecione *Salvar*.

