---
permalink: admin/changing-network-options-object-encryption.html 
sidebar: sidebar 
keywords: enable http, storage node connections 
summary: Você pode configurar a segurança de rede e de objetos para criptografar objetos armazenados, impedir determinadas solicitações do S3 ou permitir que conexões de clientes com nós de armazenamento usem HTTP em vez de HTTPS. 
---
= Configurar a segurança da rede e do objeto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar a segurança de rede e de objetos para criptografar objetos armazenados, impedir determinadas solicitações do S3 ou permitir que conexões de clientes com nós de armazenamento usem HTTP em vez de HTTPS.



== Criptografia de objetos armazenados

A criptografia de objetos armazenados permite a criptografia de todos os dados de objetos à medida que são ingeridos pelo S3.  Por padrão, os objetos armazenados não são criptografados, mas você pode optar por criptografar objetos usando o algoritmo de criptografia AES-128 ou AES-256.  Quando você ativa a configuração, todos os objetos recém-ingeridos são criptografados, mas nenhuma alteração é feita nos objetos armazenados existentes.  Se você desabilitar a criptografia, os objetos criptografados atualmente permanecerão criptografados, mas os objetos recém-ingeridos não serão criptografados.

A configuração de criptografia de objeto armazenado se aplica somente a objetos do S3 que não foram criptografados pela criptografia em nível de bucket ou de objeto.

Para obter mais detalhes sobre os métodos de criptografia StorageGRID , consultelink:../admin/reviewing-storagegrid-encryption-methods.html["Revise os métodos de criptografia do StorageGRID"] .



== Impedir modificação do cliente

Impedir modificação do cliente é uma configuração de todo o sistema.  Quando a opção *Impedir modificação do cliente* é selecionada, as seguintes solicitações são negadas.



=== API REST S3

* Solicitações DeleteBucket
* Quaisquer solicitações para modificar dados de um objeto existente, metadados definidos pelo usuário ou marcação de objeto S3




== Habilitar HTTP para conexões de nó de armazenamento

Por padrão, os aplicativos cliente usam o protocolo de rede HTTPS para qualquer conexão direta com os nós de armazenamento.  Opcionalmente, você pode habilitar HTTP para essas conexões, por exemplo, ao testar uma grade que não seja de produção.

Use HTTP para conexões de nós de armazenamento somente se os clientes S3 precisarem fazer conexões HTTP diretamente com os nós de armazenamento.  Você não precisa usar esta opção para clientes que usam apenas conexões HTTPS ou para clientes que se conectam ao serviço Load Balancer (porque você podelink:../admin/configuring-load-balancer-endpoints.html["configurar cada ponto de extremidade do balanceador de carga"] para usar HTTP ou HTTPS).

Verlink:summary-ip-addresses-and-ports-for-client-connections.html["Resumo: Endereços IP e portas para conexões de clientes"] para saber quais portas os clientes S3 usam ao se conectar aos nós de armazenamento usando HTTP ou HTTPS.



== Selecionar opções

.Antes de começar
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você tem permissão de acesso Root.


.Passos
. Selecione *CONFIGURAÇÃO* > *Segurança* > *Configurações de segurança*.
. Selecione a aba *Rede e objetos*.
. Para criptografia de objetos armazenados, use a configuração *Nenhum* (padrão) se não quiser que objetos armazenados sejam criptografados ou selecione *AES-128* ou *AES-256* para criptografar objetos armazenados.
. Opcionalmente, selecione *Impedir modificação do cliente* se quiser impedir que clientes S3 façam solicitações específicas.
+

NOTE: Se você alterar essa configuração, levará cerca de um minuto para que a nova configuração seja aplicada.  O valor configurado é armazenado em cache para desempenho e dimensionamento.

. Opcionalmente, selecione *Habilitar HTTP para conexões de nós de armazenamento* se os clientes se conectarem diretamente aos nós de armazenamento e você quiser usar conexões HTTP.
+

NOTE: Tenha cuidado ao habilitar o HTTP para uma grade de produção porque as solicitações serão enviadas sem criptografia.

. Selecione *Salvar*.

