---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Cada nó na sua grade tem uma senha exclusiva do console do nó, que você precisa para efetuar login no nó.  Use estas etapas para alterar a senha do console do nó para cada nó na sua grade.  As senhas são armazenadas no Pacote de Recuperação. 
---
= Alterar senhas do console do nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada nó na sua grade tem uma senha exclusiva do console do nó, que você precisa para efetuar login no nó.  Use estas etapas para alterar a senha exclusiva do console de cada nó na sua grade.

.Antes de começar
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você tem olink:admin-group-permissions.html["Permissão de acesso de manutenção ou root"] .
* Você tem a senha de provisionamento atual.


.Sobre esta tarefa
Use a senha do console do nó para efetuar login em um nó como "admin" usando SSH ou como usuário root em uma conexão de console físico/VM.  O processo de alteração de senha do console do nó cria novas senhas para cada nó em sua grade e armazena as senhas em um arquivo atualizado. `Passwords.txt` arquivo no Pacote de Recuperação.  As senhas são listadas na coluna Senha no arquivo Passwords.txt.


NOTE: Há senhas de acesso SSH separadas para as chaves SSH usadas para comunicação entre nós.  As senhas de acesso SSH não são alteradas por este procedimento.



== Acesse o assistente

.Passos
. Selecione *CONFIGURAÇÃO* > *Controle de acesso* > *Senhas de grade*.
. Em *Alterar senhas do console do nó*, selecione *Fazer uma alteração*.




== Digite a senha de provisionamento

.Passos
. Digite a senha de provisionamento para sua grade.
. Selecione *Continuar*.




== [[download-current]]Baixe o pacote de recuperação atual

Antes de alterar as senhas do console do nó, baixe o Pacote de Recuperação atual. Você pode usar as senhas neste arquivo se o processo de alteração de senha falhar para qualquer nó.

.Passos
. Selecione *Baixar pacote de recuperação*.
. Copie o arquivo do pacote de recuperação(`.zip` ) para dois locais seguros, protegidos e separados.
+

CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID .

. Selecione *Continuar*.
. Quando a caixa de diálogo de confirmação aparecer, selecione *Sim* se estiver pronto para começar a alterar as senhas do console do nó.
+
Você não pode cancelar este processo depois que ele for iniciado.





== Alterar senhas do console do nó

Quando o processo de senha do console do nó é iniciado, um novo Pacote de Recuperação é gerado, incluindo as novas senhas.  Em seguida, as senhas são atualizadas em cada nó.

.Passos
. Aguarde a geração do novo Pacote de Recuperação, o que pode levar alguns minutos.
. Selecione *Baixar novo pacote de recuperação*.
. Quando o download for concluído:
+
.. Abra o `.zip` arquivo.
.. Confirme se você pode acessar o conteúdo, incluindo o `Passwords.txt` arquivo, que contém as novas senhas do console do nó.
.. Copie o novo arquivo do pacote de recuperação(`.zip` ) para dois locais seguros, protegidos e separados.
+

CAUTION: Não substitua o antigo Pacote de Recuperação.

+
O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID .



. Marque a caixa de seleção para indicar que você baixou o novo Pacote de Recuperação e verificou o conteúdo.
. Selecione *Alterar senhas do console do nó* e aguarde até que todos os nós sejam atualizados com as novas senhas.  Isso pode levar alguns minutos.
+
Se as senhas forem alteradas para todos os nós, um banner verde de sucesso será exibido.  Vá para o próximo passo.

+
Se houver um erro durante o processo de atualização, uma mensagem de banner listará o número de nós que não tiveram suas senhas alteradas. O sistema repetirá automaticamente o processo em qualquer nó cuja senha não tenha sido alterada. Se o processo terminar com alguns nós ainda sem uma senha alterada, o botão *Repetir* será exibido.

+
Se a atualização da senha falhar para um ou mais nós:

+
.. Revise as mensagens de erro listadas na tabela.
.. Resolva os problemas.
.. Selecione *Repetir*.
+

NOTE: Tentar novamente altera apenas as senhas do console do nó nos nós que falharam durante tentativas anteriores de alteração de senha.



. Depois que as senhas do console do nó forem alteradas para todos os nós, exclua o<<download-current,primeiro pacote de recuperação que você baixou>> .
. Opcionalmente, use o link *Pacote de recuperação* para baixar uma cópia adicional do novo Pacote de recuperação.

