---
permalink: admin/configuring-client-connections.html 
sidebar: sidebar 
keywords: s3 connection, connect to storagegrid, s3 setup wizard 
summary: Como administrador de grade, você gerencia as opções de configuração que controlam como os aplicativos cliente S3 se conectam ao seu sistema StorageGRID para armazenar e recuperar dados. 
---
= Configurar conexões do cliente S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como administrador de grade, você gerencia as opções de configuração que controlam como os aplicativos cliente S3 se conectam ao seu sistema StorageGRID para armazenar e recuperar dados.


TIP: Os detalhes do Swift foram removidos desta versão do site de documentação. Ver https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-client-connections.html["StorageGRID 11.8: Configurar conexões de cliente S3 e Swift"^] .



== Tarefas de configuração

. Execute tarefas de pré-requisito no StorageGRID, com base em como o aplicativo cliente se conectará ao StorageGRID.


[role="tabbed-block"]
====
.Tarefas necessárias
--
Você deve obter:

* Endereços IP
* Nomes de domínio
* Certificado SSL


--
.Tarefas opcionais
--
Opcionalmente, configure:

* Federação de identidade
* SSO


--
====
. Use o StorageGRID para obter os valores que o aplicativo precisa para se conectar à grade.  Você pode usar o assistente de configuração do S3 ou configurar cada entidade do StorageGRID manualmente. +


[role="tabbed-block"]
====
.Use o assistente de configuração do S3
--
Siga as etapas do assistente de configuração do S3.

--
.Configurar manualmente
--
. Criar grupo de alta disponibilidade
. Criar ponto de extremidade do balanceador de carga
. Criar conta de inquilino
. Criar bucket e chaves de acesso
. Configurar regra e política do ILM


--
====
. Use o aplicativo S3 para concluir a conexão com o StorageGRID.  Crie entradas DNS para associar endereços IP a quaisquer nomes de domínio que você planeja usar.
+
Conforme necessário, execute configurações adicionais do aplicativo.

. Execute tarefas contínuas no aplicativo e no StorageGRID para gerenciar e monitorar o armazenamento de objetos ao longo do tempo.




== Informações necessárias para anexar o StorageGRID a um aplicativo cliente

Antes de poder anexar o StorageGRID a um aplicativo cliente S3, você deve executar etapas de configuração no StorageGRID e obter determinado valor.



=== Quais valores eu preciso?

A tabela a seguir mostra os valores que você deve configurar no StorageGRID e onde esses valores são usados ​​pelo aplicativo S3 e pelo servidor DNS.

[cols="1a,1a,1a"]
|===
| Valor | Onde o valor é configurado | Onde o valor é usado 


 a| 
Endereços IP virtuais (VIP)
 a| 
StorageGRID > grupo HA
 a| 
Entrada DNS



 a| 
Porta
 a| 
StorageGRID > Ponto de extremidade do balanceador de carga
 a| 
Aplicação do cliente



 a| 
Certificado SSL
 a| 
StorageGRID > Ponto de extremidade do balanceador de carga
 a| 
Aplicação do cliente



 a| 
Nome do servidor (FQDN)
 a| 
StorageGRID > Ponto de extremidade do balanceador de carga
 a| 
* Aplicação do cliente
* Entrada DNS




 a| 
ID da chave de acesso S3 e chave de acesso secreta
 a| 
StorageGRID > Locatário e bucket
 a| 
Aplicação do cliente



 a| 
Nome do balde/recipiente
 a| 
StorageGRID > Locatário e bucket
 a| 
Aplicação do cliente

|===


=== Como obtenho esses valores?

Dependendo de suas necessidades, você pode fazer o seguinte para obter as informações necessárias:

* *Use olink:use-s3-setup-wizard.html["Assistente de configuração do S3"] *.  O assistente de configuração do S3 ajuda você a configurar rapidamente os valores necessários no StorageGRID e gera um ou dois arquivos que você pode usar ao configurar o aplicativo S3.  O assistente orienta você nas etapas necessárias e ajuda a garantir que suas configurações estejam em conformidade com as práticas recomendadas do StorageGRID .
+

NOTE: Se você estiver configurando um aplicativo S3, é recomendável usar o assistente de configuração do S3, a menos que você saiba que tem requisitos especiais ou que sua implementação exija personalização significativa.

* *Use olink:../fabricpool/use-fabricpool-setup-wizard.html["Assistente de configuração do FabricPool"] *.  Semelhante ao assistente de configuração do S3, o assistente de configuração do FabricPool ajuda você a configurar rapidamente os valores necessários e gera um arquivo que você pode usar ao configurar uma camada de nuvem do FabricPool no ONTAP.
+

NOTE: Se você planeja usar o StorageGRID como o sistema de armazenamento de objetos para uma camada de nuvem do FabricPool , é recomendável usar o assistente de configuração do FabricPool , a menos que você saiba que tem requisitos especiais ou que sua implementação exija personalização significativa.

* *Configurar itens manualmente*.  Se você estiver se conectando a um aplicativo S3 e preferir não usar o assistente de configuração do S3, poderá obter os valores necessários executando a configuração manualmente. Siga estes passos:
+
.. Configure o grupo de alta disponibilidade (HA) que você deseja usar para o aplicativo S3. Ver link:configure-high-availability-group.html["Configurar grupos de alta disponibilidade"] .
.. Crie o ponto de extremidade do balanceador de carga que o aplicativo S3 usará. Ver link:configuring-load-balancer-endpoints.html["Configurar pontos de extremidade do balanceador de carga"] .
.. Crie a conta de locatário que o aplicativo S3 usará. Ver link:creating-tenant-account.html["Criar uma conta de inquilino"] .
.. Para um locatário S3, entre na conta do locatário e gere um ID de chave de acesso e uma chave de acesso secreta para cada usuário que acessará o aplicativo. Ver link:../tenant/creating-your-own-s3-access-keys.html["Crie suas próprias chaves de acesso"] .
.. Crie um ou mais buckets S3 na conta do locatário.  Para S3, vejalink:../tenant/creating-s3-bucket.html["Criar bucket S3"] .
.. Para adicionar instruções de posicionamento específicas para os objetos pertencentes ao novo locatário ou bucket/contêiner, crie uma nova regra do ILM e ative uma nova política do ILM para usar essa regra. Verlink:../ilm/access-create-ilm-rule-wizard.html["Criar regra ILM"] elink:../ilm/creating-ilm-policy.html["Criar política de ILM"] .



