---
permalink: admin/controlling-access-through-firewalls.html 
sidebar: sidebar 
keywords: firewall access, firewall ports, external firewall 
summary: Você pode abrir ou fechar portas específicas no firewall externo. 
---
= Controle de acesso em firewall externo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode abrir ou fechar portas específicas no firewall externo.

Você pode controlar o acesso às interfaces de usuário e APIs nos nós de administração do StorageGRID abrindo ou fechando portas específicas no firewall externo.  Por exemplo, você pode querer impedir que os locatários consigam se conectar ao Grid Manager pelo firewall, além de usar outros métodos para controlar o acesso ao sistema.

Se você quiser configurar o firewall interno do StorageGRID , consultelink:../admin/configure-firewall-controls.html["Configurar firewall interno"] .

[cols="1a,1a,2a"]
|===
| Porta | Descrição | Se a porta estiver aberta... 


 a| 
443
 a| 
Porta HTTPS padrão para nós de administração
 a| 
Navegadores da Web e clientes da API de gerenciamento podem acessar o Grid Manager, a Grid Management API, o Tenant Manager e a Tenant Management API.

*Observação:* a porta 443 também é usada para algum tráfego interno.



 a| 
8443
 a| 
Porta do Grid Manager restrita em nós de administração
 a| 
* Navegadores da Web e clientes da API de gerenciamento podem acessar o Grid Manager e a Grid Management API usando HTTPS.
* Navegadores da Web e clientes da API de gerenciamento não podem acessar o Gerenciador de Tenants ou a API de Gerenciamento de Tenants.
* Solicitações de conteúdo interno serão rejeitadas.




 a| 
9443
 a| 
Porta restrita do Tenant Manager em nós de administração
 a| 
* Navegadores da Web e clientes da API de gerenciamento podem acessar o Gerenciador de Tenants e a API de Gerenciamento de Tenants usando HTTPS.
* Navegadores da Web e clientes da API de gerenciamento não podem acessar o Grid Manager ou a Grid Management API.
* Solicitações de conteúdo interno serão rejeitadas.


|===

TIP: O logon único (SSO) não está disponível nas portas restritas do Grid Manager ou do Tenant Manager.  Você deve usar a porta HTTPS padrão (443) se quiser que os usuários se autentiquem com logon único.

.Informações relacionadas
* link:signing-in-to-grid-manager.html["Sign in no Grid Manager"]
* link:creating-tenant-account.html["Criar conta de inquilino"]
* link:../network/external-communications.html["Comunicações externas"]

