---
permalink: admin/copying-storagegrid-system-ca-certificate.html 
sidebar: sidebar 
keywords: grid ca certificate, copy certificate 
summary: 'O StorageGRID usa uma Autoridade de Certificação interna (CA) para proteger o tráfego interno.  Este certificado não muda se você carregar seus próprios certificados.' 
---
= Copie o certificado Grid CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID usa uma autoridade de certificação interna (CA) para proteger o tráfego interno.  Este certificado não muda se você carregar seus próprios certificados.

.Antes de começar
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você temlink:admin-group-permissions.html["permissões de acesso específicas"] .


.Sobre esta tarefa
Se um certificado de servidor personalizado tiver sido configurado, os aplicativos cliente deverão verificar o servidor usando o certificado de servidor personalizado.  Eles não devem copiar o certificado CA do sistema StorageGRID .

.Passos
. Selecione *CONFIGURAÇÃO* > *Segurança* > *Certificados* e então selecione a aba *Grid CA*.
. Na seção *Certificado PEM*, baixe ou copie o certificado.
+
[role="tabbed-block"]
====
.Baixar arquivo de certificado
--
Baixe o certificado `.pem` arquivo.

.. Selecione *Baixar certificado*.
.. Especifique o nome do arquivo do certificado e o local do download.  Salve o arquivo com a extensão `.pem` .
+
Por exemplo:  `storagegrid_certificate.pem`



--
.Certificado de cópia PEM
--
Copie o texto do certificado para colar em outro lugar.

.. Selecione *Copiar certificado PEM*.
.. Cole o certificado copiado em um editor de texto.
.. Salve o arquivo de texto com a extensão `.pem` .
+
Por exemplo:  `storagegrid_certificate.pem`



--
====

