---
permalink: admin/deleting-traffic-classification-policy.html 
sidebar: sidebar 
keywords: delete traffic classification policy 
summary: Se você não precisar mais de uma política de classificação de tráfego, poderá excluí-la. 
---
= Excluir uma política de classificação de tráfego
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode excluir uma política de classificação de tráfego se não precisar mais dela.  Certifique-se de excluir a política correta porque uma política não pode ser recuperada quando excluída.

.Antes de começar
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você tem olink:admin-group-permissions.html["Permissão de acesso root"] .


.Passos
. Selecione *CONFIGURAÇÃO* > *Rede* > *Classificação de tráfego*.
+
A página Políticas de classificação de tráfego é exibida com as políticas existentes listadas em uma tabela.

. Exclua a política usando o menu Ações ou a página de detalhes.
+
[role="tabbed-block"]
====
.Menu de ações
--
.. Marque a caixa de seleção da política.
.. Selecione *Ações* > *Remover*.


--
.Página de detalhes da política
--
.. Selecione o nome da política.
.. Selecione o botão *Remover* ao lado do nome da política.


--
====
. Selecione *Sim* para confirmar que deseja excluir a política.
+
A política foi excluída.


