---
permalink: admin/global-certificate-types.html 
sidebar: sidebar 
keywords: rsa, ecdsa, custom certificate encryption 
summary: 'O sistema StorageGRID suporta certificados de servidor criptografados com RSA ou ECDSA (Algoritmo de Assinatura Digital de Curva Elíptica).' 
---
= Tipos de certificados de servidor suportados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema StorageGRID suporta certificados personalizados criptografados com RSA ou ECDSA (Algoritmo de Assinatura Digital de Curva Elíptica).


TIP: O tipo de cifra da política de segurança deve corresponder ao tipo de certificado do servidor.  Por exemplo, cifras RSA exigem certificados RSA, e cifras ECDSA exigem certificados ECDSA. Ver link:using-storagegrid-security-certificates.html["Gerenciar certificados de segurança"] .  Se você configurar uma política de segurança personalizada que não seja compatível com o certificado do servidor, você poderálink:manage-tls-ssh-policy.html#temporarily-revert-to-default-security-policy["reverter temporariamente para a política de segurança padrão"] .

Para obter mais informações sobre como o StorageGRID protege as conexões do cliente, consultelink:security-for-clients.html["Segurança para clientes S3"] .
