---
permalink: admin/updating-storagegrid-license-information.html 
sidebar: sidebar 
keywords: storagegrid license, update license, add storage capacity 
summary: Você deve atualizar as informações da licença do seu sistema StorageGRID sempre que os termos da sua licença forem alterados.  Por exemplo, você deve atualizar as informações da licença se comprar capacidade de armazenamento adicional para sua rede. 
---
= Atualizar informações da licença do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve atualizar as informações da licença do seu sistema StorageGRID sempre que os termos da sua licença forem alterados.  Por exemplo, você deve atualizar as informações da licença se comprar capacidade de armazenamento adicional para sua rede.

.Antes de começar
* Você tem um novo arquivo de licença para aplicar ao seu sistema StorageGRID .
* Você temlink:admin-group-permissions.html["permissões de acesso específicas"] .
* Você tem a senha de provisionamento.


.Passos
. Selecione *MANUTENÇÃO* > *Sistema* > *Licença*.
. Na seção Atualizar licença, selecione *Procurar*.
. Localize e selecione o novo arquivo de licença(`.txt` ).
+
O novo arquivo de licença é validado e exibido.

. Digite a senha de provisionamento.
. Selecione *Salvar*.

