---
permalink: s3/authenticating-requests.html 
sidebar: sidebar 
keywords: authenticate requests, authenticating, requests 
summary: O sistema StorageGRID oferece suporte ao acesso autenticado e anônimo a objetos usando a API S3. 
---
= Autenticar solicitações
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema StorageGRID oferece suporte ao acesso autenticado e anônimo a objetos usando a API S3.

A API do S3 oferece suporte ao Signature versão 2 e ao Signature versão 4 para autenticação de solicitações da API do S3.

Solicitações autenticadas devem ser assinadas usando seu ID de chave de acesso e sua chave de acesso secreta.

O sistema StorageGRID suporta dois métodos de autenticação: HTTP `Authorization` cabeçalho e usando parâmetros de consulta.



== Use o cabeçalho de autorização HTTP

O HTTP `Authorization` O cabeçalho é usado por todas as operações da API do S3, exceto solicitações anônimas, quando permitido pela política de bucket.  O `Authorization` O cabeçalho contém todas as informações de assinatura necessárias para autenticar uma solicitação.



== Usar parâmetros de consulta

Você pode usar parâmetros de consulta para adicionar informações de autenticação a uma URL.  Isso é conhecido como pré-assinatura de URL, que pode ser usado para conceder acesso temporário a recursos específicos.  Usuários com a URL pré-assinada não precisam saber a chave de acesso secreta para acessar o recurso, o que permite que você forneça acesso restrito de terceiros a um recurso.
