---
permalink: s3/deprecated-bucket-requests-for-legacy-compliance.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated bucket requests 
summary: Talvez seja necessário usar a API REST do StorageGRID S3 para gerenciar buckets que foram criados usando o recurso de conformidade legado. 
---
= Solicitações de bucket obsoletas para conformidade legada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário usar a API REST do StorageGRID S3 para gerenciar buckets que foram criados usando o recurso de conformidade legado.



== Recurso de conformidade obsoleto

O recurso de conformidade do StorageGRID que estava disponível em versões anteriores do StorageGRID foi descontinuado e substituído pelo S3 Object Lock.

Se você habilitou anteriormente a configuração global de Conformidade, a configuração global de Bloqueio de Objeto S3 será habilitada no StorageGRID 11.6.  Não é mais possível criar novos buckets com a Conformidade ativada; no entanto, conforme necessário, você pode usar a API REST do StorageGRID S3 para gerenciar quaisquer buckets compatíveis legados existentes.

* link:use-s3-api-for-s3-object-lock.html["Use a API REST do S3 para configurar o bloqueio de objeto do S3"]
* link:../ilm/index.html["Gerenciar objetos com ILM"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Base de conhecimento da NetApp : Como gerenciar buckets compatíveis legados no StorageGRID 11.5"^]


Solicitações de conformidade obsoletas:

* link:../s3/deprecated-put-bucket-request-modifications-for-compliance.html["Obsoleto - Modificações na solicitação do bucket PUT para conformidade"]
+
O elemento XML SGCompliance está obsoleto.  Anteriormente, você podia incluir esse elemento personalizado StorageGRID no corpo de solicitação XML opcional de solicitações PUT Bucket para criar um bucket compatível.

* link:../s3/deprecated-get-bucket-compliance-request.html["Obsoleto - Conformidade com o GET Bucket"]
+
A solicitação de conformidade do GET Bucket está obsoleta.  No entanto, você pode continuar a usar essa solicitação para determinar as configurações de conformidade atualmente em vigor para um bucket compatível legado existente.

* link:../s3/deprecated-put-bucket-compliance-request.html["Obsoleto - Conformidade com PUT Bucket"]
+
A solicitação de conformidade do PUT Bucket está obsoleta.  No entanto, você pode continuar a usar essa solicitação para modificar as configurações de conformidade de um bucket compatível legado existente.  Por exemplo, você pode colocar um bucket existente em retenção legal ou aumentar seu período de retenção.


