---
permalink: s3/get-bucket-metadata-notification-configuration-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket metadata notification configuration 
summary: A solicitação de configuração de notificação de metadados do GET Bucket permite que você recupere o XML de configuração usado para configurar a integração de pesquisa para buckets individuais. 
---
= Configuração de notificação de metadados do GET Bucket
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A solicitação de configuração de notificação de metadados do GET Bucket permite que você recupere o XML de configuração usado para configurar a integração de pesquisa para buckets individuais.

Você deve ter a permissão s3:GetBucketMetadataNotification ou ser root da conta para concluir esta operação.



== Exemplo de solicitação

Esta solicitação recupera a configuração de notificação de metadados para o bucket denominado `bucket` .

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Resposta

O corpo da resposta inclui a configuração de notificação de metadados para o bucket.  A configuração de notificação de metadados permite que você determine como o bucket é configurado para integração de pesquisa.  Ou seja, ele permite que você determine quais objetos são indexados e para quais endpoints seus metadados de objeto estão sendo enviados.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:_region:account-ID_:domain/_mydomain/myindex/mytype_</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
Cada configuração de notificação de metadados inclui uma ou mais regras.  Cada regra especifica os objetos aos quais se aplica e o destino para onde o StorageGRID deve enviar metadados do objeto.  Os destinos devem ser especificados usando o URN de um ponto de extremidade StorageGRID .

[cols="1a,2a,1a"]
|===
| Nome | Descrição | Obrigatório 


 a| 
Configuração de Notificação de Metadados
 a| 
Tag de contêiner para regras usadas para especificar os objetos e o destino para notificações de metadados.

Contém um ou mais elementos Rule.
 a| 
Sim



 a| 
Regra
 a| 
Tag de contêiner para uma regra que identifica os objetos cujos metadados devem ser adicionados a um índice especificado.

Regras com prefixos sobrepostos são rejeitadas.

Incluído no elemento MetadataNotificationConfiguration.
 a| 
Sim



 a| 
EU IA
 a| 
Identificador exclusivo para a regra.

Incluído no elemento Rule.
 a| 
Não



 a| 
Status
 a| 
O status pode ser "Habilitado" ou "Desabilitado".  Nenhuma ação é tomada para regras que estão desabilitadas.

Incluído no elemento Rule.
 a| 
Sim



 a| 
Prefixo
 a| 
Objetos que correspondem ao prefixo são afetados pela regra, e seus metadados são enviados ao destino especificado.

Para corresponder a todos os objetos, especifique um prefixo vazio.

Incluído no elemento Rule.
 a| 
Sim



 a| 
Destino
 a| 
Tag de contêiner para o destino de uma regra.

Incluído no elemento Rule.
 a| 
Sim



 a| 
Urna
 a| 
URN do destino para onde os metadados do objeto são enviados.  Deve ser a URN de um ponto de extremidade StorageGRID com as seguintes propriedades:

* `es`deve ser o terceiro elemento.
* A URN deve terminar com o índice e o tipo onde os metadados são armazenados, no formato `domain-name/myindex/mytype` .


Os endpoints são configurados usando o Tenant Manager ou a Tenant Management API.  Eles assumem a seguinte forma:

* `arn:aws:es:_region:account-ID_:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


O ponto de extremidade deve ser configurado antes que o XML de configuração seja enviado, ou a configuração falhará com um erro 404.

A urna está incluída no elemento Destino.
 a| 
Sim

|===


== Exemplo de resposta

O XML incluído entre o `<MetadataNotificationConfiguration></MetadataNotificationConfiguration>` tags mostra como a integração com um ponto de extremidade de integração de pesquisa é configurada para o bucket.  Neste exemplo, os metadados do objeto estão sendo enviados para um índice do Elasticsearch denominado `current` e digite nomeado `2017` que está hospedado em um domínio AWS chamado `records` .

[listing]
----
HTTP/1.1 200 OK
Date: Thu, 20 Jul 2017 18:24:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/11.0.0
x-amz-request-id: 3832973499
Content-Length: 264
Content-Type: application/xml

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix>2017</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/records/current/2017</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.Informações relacionadas
link:../tenant/index.html["Use uma conta de inquilino"]
