---
permalink: s3/s3-rest-api-supported-operations-and-limitations.html 
sidebar: sidebar 
keywords: s3 rest api supported operations, s3 rest api limitations 
summary: 'O sistema StorageGRID implementa a API do Simple Storage Service (versão da API 2006-03-01) com suporte para a maioria das operações e com algumas limitações.  Você precisa entender os detalhes de implementação ao integrar aplicativos cliente da API REST do S3.' 
---
= Detalhes da implementação da API REST S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema StorageGRID implementa a API do Simple Storage Service (versão da API 2006-03-01) com suporte para a maioria das operações e com algumas limitações.  Você precisa entender os detalhes de implementação ao integrar aplicativos cliente da API REST do S3.

O sistema StorageGRID oferece suporte a solicitações no estilo de hospedagem virtual e solicitações no estilo de caminho.



== Manuseio de data

A implementação StorageGRID da API REST do S3 suporta apenas formatos de data HTTP válidos.

O sistema StorageGRID suporta apenas formatos de data HTTP válidos para quaisquer cabeçalhos que aceitem valores de data.  A parte de hora da data pode ser especificada no formato Greenwich Mean Time (GMT) ou no formato Universal Coordinated Time (UTC) sem deslocamento de fuso horário (+0000 deve ser especificado).  Se você incluir o `x-amz-date` cabeçalho na sua solicitação, ele substitui qualquer valor especificado no cabeçalho da solicitação Date.  Ao usar o AWS Signature versão 4, o `x-amz-date` O cabeçalho deve estar presente na solicitação assinada porque o cabeçalho de data não é suportado.



== Cabeçalhos de solicitação comuns

O sistema StorageGRID suporta os cabeçalhos de solicitação comuns definidos por https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html["Referência da API do Amazon Simple Storage Service: Cabeçalhos de solicitação comuns"^] , com uma exceção.

[cols="1a,2a"]
|===
| Cabeçalho da solicitação | Implementação 


 a| 
Autorização
 a| 
Suporte total para AWS Signature versão 2

Suporte para AWS Signature versão 4, com as seguintes exceções:

* Quando você fornece o valor real da soma de verificação da carga útil em `x-amz-content-sha256` , o valor é aceito sem validação, como se o valor `UNSIGNED-PAYLOAD` tinha sido fornecido para o cabeçalho.  Quando você fornece um `x-amz-content-sha256` valor do cabeçalho que implica `aws-chunked` streaming (por exemplo, STREAMING-AWS4-HMAC-SHA256-PAYLOAD), as assinaturas dos blocos não são verificadas em relação aos dados dos blocos.




 a| 
token de segurança x-amz
 a| 
Não implementado.  Devoluções `XNotImplemented` .

|===


== Cabeçalhos de resposta comuns

O sistema StorageGRID suporta todos os cabeçalhos de resposta comuns definidos pela _Simple Storage Service API Reference_, com uma exceção.

[cols="1a,2a"]
|===
| Cabeçalho de resposta | Implementação 


 a| 
x-amz-id-2
 a| 
Não utilizado

|===