---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: Os arquivos MIB contêm definições e informações sobre as propriedades dos recursos e serviços gerenciados para os nós na sua grade.  Você pode acessar arquivos MIB que definem os objetos e notificações para StorageGRID.  Esses arquivos podem ser úteis para monitorar sua grade. 
---
= Acessar arquivos MIB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os arquivos MIB contêm definições e informações sobre as propriedades dos recursos e serviços gerenciados para os nós na sua grade.  Você pode acessar arquivos MIB que definem os objetos e notificações para StorageGRID.  Esses arquivos podem ser úteis para monitorar sua grade.

Verlink:using-snmp-monitoring.html["Usar monitoramento SNMP"] para mais informações sobre arquivos SNMP e MIB.



== Acessar arquivos MIB

Siga estas etapas para acessar os arquivos MIB.

.Passos
. Selecione *CONFIGURAÇÃO* > *Monitoramento* > *Agente SNMP*.
. Na página do agente SNMP, selecione o arquivo que deseja baixar:
+
** *NETAPP-STORAGEGRID-MIB.txt*: Define a tabela de alertas e notificações (traps) acessíveis em todos os nós de administração.
** *ES-NETAPP-06-MIB.mib*: Define objetos e notificações para dispositivos baseados na Série E.
** *MIB_1_10.zip*: Define objetos e notificações para dispositivos com uma interface BMC .
+
[]
====

TIP: Você também pode acessar arquivos MIB no seguinte local em qualquer nó do StorageGRID : `/usr/share/snmp/mibs`

====


. Para extrair os OIDs do StorageGRID do arquivo MIB:
+
.. Obtenha o OID da raiz do StorageGRID MIB:
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
Resultado: `.1.3.6.1.4.1.789.28669` (`28669` é sempre o OID para StorageGRID)

.. Grep para o OID StorageGRID em toda a árvore (usando `paste` para unir linhas):
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`






TIP: O `snmptranslate` O comando tem muitas opções úteis para explorar o MIB.  Este comando está disponível em qualquer nó StorageGRID .



== Conteúdo do arquivo MIB

Todos os objetos estão sob o OID StorageGRID .

[cols="1a,1a,2a"]
|===
| Nome do objeto | ID do objeto (OID) | Descrição 


| .iso.org.dod.internet.  + empresas privadas.  + netapp.grade de armazenamento | .1.3.6.1.4.1.789.28669  a| 
O módulo MIB para entidades NetApp StorageGRID .

|===


== Objetos MIB

[cols="1a,1a,2a"]
|===
| Nome do objeto | ID do objeto (OID) | Descrição 


| Contagem de Alerta Ativo | .1.3.6.1.4.1. + 789.28669.1.3  a| 
O número de alertas ativos na activeAlertTable.



| Tabela de Alerta Ativo | .1.3.6.1.4.1. + 789.28669.1.4  a| 
Uma tabela de alertas ativos no StorageGRID.



| ID de alerta ativo | .1.3.6.1.4.1. + 789.28669.1.4.1.1  a| 
O ID do alerta.  Único no conjunto atual de alertas ativos.



| NomeAlertaAtivo | .1.3.6.1.4.1. + 789.28669.1.4.1.2  a| 
O nome do alerta.



| instância de alerta ativo | .1.3.6.1.4.1. + 789.28669.1.4.1.3  a| 
O nome da entidade que gerou o alerta, normalmente o nome do nó.



| activeAlertSeverity | .1.3.6.1.4.1. + 789.28669.1.4.1.4  a| 
A gravidade do alerta.



| hora de início do alerta ativo | .1.3.6.1.4.1. + 789.28669.1.4.1.5  a| 
Data e hora em que o alerta foi disparado.

|===


== Tipos de notificação (armadilhas)

Todas as notificações incluem as seguintes variáveis como varbinds:

* ID de alerta ativo
* NomeAlertaAtivo
* instância de alerta ativo
* activeAlertSeverity
* hora de início do alerta ativo


[cols="1a,1a,2a"]
|===
| Tipo de notificação | ID do objeto (OID) | Descrição 


| Alerta Menor Ativo | .1.3.6.1.4.1. + 789.28669.0.6  a| 
Um alerta com gravidade menor



| AlertaMaiorAtivo | .1.3.6.1.4.1. + 789.28669.0.7  a| 
Um alerta com grande gravidade



| AlertaCríticoAtivo | .1.3.6.1.4.1. + 789.28669.0.8  a| 
Um alerta com gravidade crítica

|===