---
permalink: monitor/storagegrid-software-logs.html 
sidebar: sidebar 
keywords: logs 
summary: Você pode usar os logs do StorageGRID para solucionar problemas. 
---
= Registros do software StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os logs do StorageGRID para solucionar problemas.


NOTE: Se você deseja enviar seus logs para um servidor syslog externo ou alterar o destino das informações de auditoria, como `bycast.log` e `nms.log` , verlink:../monitor/configure-audit-messages.html#["Configurar mensagens de auditoria e destinos de log"] .



== Logs do StorageGRID geral

[cols="3a,3a,2a"]
|===
| Nome do arquivo | Notas | Encontrado em 


| /var/local/log/bycast.log  a| 
O arquivo principal de solução de problemas do StorageGRID . Selecione *SUPORTE* > *Ferramentas* > *Topologia de grade*.  Em seguida, selecione *_Site_* > *_Nó_* > *SSM* > *Eventos*.
 a| 
Todos os nós



| /var/local/log/bycast-err.log  a| 
Contém um subconjunto de `bycast.log` (mensagens com gravidade ERRO e CRÍTICO). Mensagens CRÍTICAS também são exibidas no sistema. Selecione *SUPORTE* > *Ferramentas* > *Topologia de grade*.  Em seguida, selecione *_Site_* > *_Nó_* > *SSM* > *Eventos*.
 a| 
Todos os nós



| /var/local/núcleo/  a| 
Contém todos os arquivos de despejo de memória criados caso o programa seja encerrado de forma anormal.  As causas possíveis incluem falhas de asserção, violações ou tempos limite de thread.

*Nota*: O arquivo ``/var/local/core/kexec_cmd` geralmente existe em nós de dispositivos e não indica um erro.
 a| 
Todos os nós

|===


== Registros relacionados à cifra

[cols="3a,3a,2a"]
|===
| Nome do arquivo | Notas | Encontrado em 


| /var/local/log/ssh-config-generation.log  a| 
Contém logs relacionados à geração de configurações SSH e ao recarregamento de serviços SSH.
 a| 
Todos os nós



| /var/local/log/nginx/config-generation.log  a| 
Contém logs relacionados à geração de configurações nginx e ao recarregamento de serviços nginx.
 a| 
Todos os nós



| /var/local/log/nginx-gw/config-generation.log  a| 
Contém logs relacionados à geração de configurações do nginx-gw (e ao recarregamento de serviços do nginx-gw).
 a| 
Nós de administração e gateway



| /var/local/log/atualizar-configurações-de-cifra.log  a| 
Contém logs relacionados à configuração de políticas TLS e SSH.
 a| 
Todos os nós

|===


== Registros de federação de grade

[cols="3a,3a,2a"]
|===
| Nome do arquivo | Notas | Encontrado em 


| /var/local/log/update_grid_federation_config.log  a| 
Contém logs relacionados à geração de configurações nginx e nginx-gw para conexões de federação de grade.
 a| 
Todos os nós

|===


== Registros NMS

[cols="3a,3a,2a"]
|===
| Nome do arquivo | Notas | Encontrado em 


| /var/local/log/nms.log  a| 
* Captura notificações do Grid Manager e do Tenant Manager.
* Captura eventos relacionados à operação do serviço NMS.  Por exemplo, notificações por e-mail e alterações de configuração.
* Contém atualizações de pacotes XML resultantes de alterações de configuração feitas no sistema.
* Contém mensagens de erro relacionadas à redução de amostragem de atributos feita uma vez por dia.
* Contém mensagens de erro do servidor web Java, por exemplo, erros de geração de página e erros HTTP Status 500.

 a| 
Nós de administração



| /var/local/log/nms.errlog  a| 
Contém mensagens de erro relacionadas a atualizações do banco de dados MySQL.

Contém o fluxo de erro padrão (stderr) dos serviços correspondentes.  Há um arquivo de log por serviço.  Esses arquivos geralmente estão vazios, a menos que haja problemas com o serviço.
 a| 
Nós de administração



| /var/local/log/nms.requestlog  a| 
Contém informações sobre conexões de saída da API de gerenciamento para serviços internos do StorageGRID .
 a| 
Nós de administração

|===


== Logs do Gerenciador de Servidores

[cols="3a,3a,2a"]
|===
| Nome do arquivo | Notas | Encontrado em 


| /var/local/log/servermanager.log  a| 
Arquivo de log do aplicativo Gerenciador do Servidor em execução no servidor.
 a| 
Todos os nós



| /var/local/log/GridstatBackend.errlog  a| 
Arquivo de log para o aplicativo de backend da GUI do Gerenciador do Servidor.
 a| 
Todos os nós



| /var/local/log/gridstat.errlog  a| 
Arquivo de log para a GUI do Gerenciador do Servidor.
 a| 
Todos os nós

|===


== Registros de serviços do StorageGRID

[cols="3a,3a,2a"]
|===
| Nome do arquivo | Notas | Encontrado em 


| /var/local/log/acct.errlog  a| 
 a| 
Nós de armazenamento executando o serviço ADC



| /var/local/log/adc.errlog  a| 
Contém o fluxo de erro padrão (stderr) dos serviços correspondentes.  Há um arquivo de log por serviço.  Esses arquivos geralmente estão vazios, a menos que haja problemas com o serviço.
 a| 
Nós de armazenamento executando o serviço ADC



| /var/local/log/ams.errlog  a| 
 a| 
Nós de administração



| /var/local/log/cassandra/system.log  a| 
Informações para o armazenamento de metadados (banco de dados Cassandra) que podem ser usadas se ocorrerem problemas ao adicionar novos nós de armazenamento ou se a tarefa de reparo do nodetool parar.
 a| 
Nós de armazenamento



| /var/local/log/cassandra-reaper.log  a| 
Informações para o serviço Cassandra Reaper, que realiza reparos dos dados no banco de dados Cassandra.
 a| 
Nós de armazenamento



| /var/local/log/cassandra-reaper.errlog  a| 
Informações de erro para o serviço Cassandra Reaper.
 a| 
Nós de armazenamento



| /var/local/log/chunk.errlog  a| 
 a| 
Nós de armazenamento



| /var/local/log/cmn.errlog  a| 
 a| 
Nós de administração



| /var/local/log/cms.errlog  a| 
Este arquivo de log pode estar presente em sistemas que foram atualizados de uma versão mais antiga do StorageGRID.  Ele contém informações legadas.
 a| 
Nós de armazenamento



| /var/local/log/dds.errlog  a| 
 a| 
Nós de armazenamento



| /var/local/log/dmv.errlog  a| 
 a| 
Nós de armazenamento



| /var/local/log/dynip*  a| 
Contém logs relacionados ao serviço dynip, que monitora a grade em busca de alterações dinâmicas de IP e atualiza a configuração local.
 a| 
Todos os nós



| /var/local/log/grafana.log  a| 
O log associado ao serviço Grafana, que é usado para visualização de métricas no Grid Manager.
 a| 
Nós de administração



| /var/local/log/hagroups.log  a| 
O log associado aos grupos de alta disponibilidade.
 a| 
Nós de administração e nós de gateway



| /var/local/log/hagroups_events.log  a| 
Rastreia mudanças de estado, como transição de BACKUP para MASTER ou FAULT.
 a| 
Nós de administração e nós de gateway



| /var/local/log/idnt.errlog  a| 
 a| 
Nós de armazenamento executando o serviço ADC



| /var/local/log/jaeger.log  a| 
O log associado ao serviço jaeger, que é usado para coleta de rastreamento.
 a| 
Todos os nós



| /var/local/log/kstn.errlog  a| 
 a| 
Nós de armazenamento executando o serviço ADC



| /var/local/log/lambda*  a| 
Contém logs para o serviço S3 Select.
 a| 
Nós de administração e gateway

Somente certos nós de administração e gateway contêm esse log. Veja olink:../admin/manage-s3-select-for-tenant-accounts.html["Requisitos e limitações do S3 Select para nós de administração e gateway"] .



| /var/local/log/ldr.errlog  a| 
 a| 
Nós de armazenamento



| /var/local/log/miscd/*.log  a| 
Contém logs para o serviço MISCd (Information Service Control Daemon), que fornece uma interface para consultar e gerenciar serviços em outros nós e para gerenciar configurações ambientais no nó, como consultar o estado de serviços em execução em outros nós.
 a| 
Todos os nós



| /var/local/log/nginx/*.log  a| 
Contém logs para o serviço nginx, que atua como um mecanismo de autenticação e comunicação segura para vários serviços de grade (como Prometheus e Dynip) para poder se comunicar com serviços em outros nós por meio de APIs HTTPS.
 a| 
Todos os nós



| /var/local/log/nginx-gw/*.log  a| 
Contém logs gerais relacionados ao serviço nginx-gw, incluindo logs de erros e logs para portas de administração restritas em nós de administração.
 a| 
Nós de administração e nós de gateway



| /var/local/log/nginx-gw/cgr-access.log.gz  a| 
Contém logs de acesso relacionados ao tráfego de replicação entre redes.
 a| 
Nós de administração, nós de gateway ou ambos, com base na configuração de federação da grade.  Encontrado somente na grade de destino para replicação entre grades.



| /var/local/log/nginx-gw/endpoint-access.log.gz  a| 
Contém logs de acesso para o serviço Load Balancer, que fornece balanceamento de carga do tráfego S3 de clientes para nós de armazenamento.
 a| 
Nós de administração e nós de gateway



| /var/local/log/persistence*  a| 
Contém logs para o serviço Persistência, que gerencia arquivos no disco raiz que precisam persistir após uma reinicialização.
 a| 
Todos os nós



| /var/local/log/prometheus.log  a| 
Para todos os nós, contém o log de serviço do exportador de nós e o log de serviço de métricas do ade-exporter.

Para nós de administração, também contém logs para os serviços Prometheus e Alert Manager.
 a| 
Todos os nós



| /var/local/log/raft.log  a| 
Contém a saída da biblioteca usada pelo serviço RSM para o protocolo Raft.
 a| 
Nós de armazenamento com serviço RSM



| /var/local/log/rms.errlog  a| 
Contém logs para o serviço Replicated State Machine Service (RSM), que é usado para serviços da plataforma S3.
 a| 
Nós de armazenamento com serviço RSM



| /var/local/log/ssm.errlog  a| 
 a| 
Todos os nós



| /var/local/log/atualização-s3vs-domains.log  a| 
Contém logs relacionados ao processamento de atualizações para a configuração de nomes de domínio hospedados virtuais do S3. Consulte as instruções para implementar aplicativos cliente do S3.
 a| 
Nós de administração e gateway



| /var/local/log/atualização-snmp-firewall.*  a| 
Contém logs relacionados às portas do firewall gerenciadas para SNMP.
 a| 
Todos os nós



| /var/local/log/atualização-sysl.log  a| 
Contém logs relacionados às alterações feitas na configuração do syslog do sistema.
 a| 
Todos os nós



| /var/local/log/atualizar-classes-de-trafego.log  a| 
Contém logs relacionados a alterações na configuração dos classificadores de tráfego.
 a| 
Nós de administração e gateway



| /var/local/log/update-utcn.log  a| 
Contém logs relacionados ao modo de rede de cliente não confiável neste nó.
 a| 
Todos os nós

|===
.Informações relacionadas
* link:about-bycast-log.html["Sobre o bycast.log"]
* link:../s3/index.html["Usar API REST do S3"]

