---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: Após recuperar um nó de armazenamento do dispositivo, você deve verificar se o estado desejado do nó de armazenamento do dispositivo está definido como online e garantir que o estado será online por padrão sempre que o servidor do nó de armazenamento for reiniciado. 
---
= Verifique o estado do armazenamento após recuperar o nó de armazenamento do dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após recuperar um nó de armazenamento do dispositivo, você deve verificar se o estado desejado do nó de armazenamento do dispositivo está definido como online e garantir que o estado será online por padrão sempre que o servidor do nó de armazenamento for reiniciado.

.Antes de começar
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* O nó de armazenamento foi recuperado e a recuperação de dados foi concluída.


.Passos
. Selecione *SUPORTE* > *Ferramentas* > *Topologia de grade*.
. Verifique os valores de *Nó de armazenamento recuperado* > *LDR* > *Armazenamento* > *Estado de armazenamento -- Desejado* e *Estado de armazenamento -- Atual*.
+
O valor de ambos os atributos deve ser Online.

. Se o Estado de armazenamento desejado estiver definido como Somente leitura, conclua as seguintes etapas:
+
.. Clique na aba *Configuração*.
.. Na lista suspensa *Estado de armazenamento -- Desejado*, selecione *Online*.
.. Clique em *Aplicar alterações*.
.. Clique na guia *Visão geral* e confirme se os valores de *Estado de armazenamento -- Desejado* e *Estado de armazenamento -- Atual* estão atualizados para Online.



