---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: 'Você pode adicionar, atualizar ou remover servidores Network Time Protocol (NTP) para garantir que os dados sejam sincronizados com precisão entre os nós da grade no seu sistema StorageGRID .' 
---
= Gerenciar servidores NTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar, atualizar ou remover servidores NTP (Network Time Protocol) para garantir que os dados sejam sincronizados com precisão entre os nós da grade no seu sistema StorageGRID .

.Antes de começar
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você tem olink:../admin/admin-group-permissions.html["Permissão de acesso de manutenção ou root"] .
* Você tem a senha de provisionamento.
* Você tem os endereços IPv4 dos servidores NTP para configurar.




== Como o StorageGRID usa o NTP

O sistema StorageGRID usa o Network Time Protocol (NTP) para sincronizar o tempo entre todos os nós da grade.

Em cada site, pelo menos dois nós no sistema StorageGRID recebem a função NTP principal.  Eles sincronizam com um mínimo sugerido de quatro e um máximo de seis fontes de tempo externas entre si.  Cada nó no sistema StorageGRID que não é um nó NTP primário atua como um cliente NTP e sincroniza com esses nós NTP primários.

Os servidores NTP externos se conectam aos nós aos quais você atribuiu anteriormente funções NTP primárias.  Por esse motivo, é recomendável especificar pelo menos dois nós com funções NTP primárias.



== Diretrizes do servidor NTP

Siga estas diretrizes para se proteger contra problemas de tempo:

* Os servidores NTP externos se conectam aos nós aos quais você atribuiu anteriormente funções NTP primárias.  Por esse motivo, é recomendável especificar pelo menos dois nós com funções NTP primárias.
* Certifique-se de que pelo menos dois nós em cada site possam acessar pelo menos quatro fontes NTP externas.  Se apenas um nó em um site puder alcançar as fontes NTP, ocorrerão problemas de tempo se esse nó ficar inativo.  Além disso, designar dois nós por site como fontes primárias de NTP garante um tempo preciso se um site estiver isolado do restante da rede.
* Os servidores NTP externos especificados devem usar o protocolo NTP.  Você deve especificar referências de servidor NTP do Stratum 3 ou superior para evitar problemas com desvio de tempo.



NOTE: Ao especificar a origem NTP externa para uma instalação do StorageGRID em nível de produção, não use o serviço Windows Time (W32Time) em uma versão do Windows anterior ao Windows Server 2016.  O serviço de tempo em versões anteriores do Windows não é suficientemente preciso e não é suportado pela Microsoft para uso em ambientes de alta precisão, incluindo StorageGRID.  Para mais detalhes, veja https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["Limite de suporte para configurar o serviço Windows Time para ambientes de alta precisão"^] .



== Configurar servidores NTP

Siga estas etapas para adicionar, atualizar ou remover servidores NTP.

.Passos
. Selecione *MANUTENÇÃO* > *Rede* > *Servidores NTP*.
. Na seção Servidores, adicione, atualize ou remova entradas do servidor NTP, conforme necessário.
+
Você deve incluir pelo menos quatro servidores NTP e pode especificar até seis servidores.

. Digite a senha de provisionamento do seu sistema StorageGRID e selecione *Salvar*.
+
A página ficará desativada até que as atualizações de configuração sejam concluídas.

+

NOTE: Se todos os seus servidores NTP falharem no teste de conexão depois que você salvar os novos servidores NTP, não prossiga. Entre em contato com o suporte técnico.





== Resolver problemas do servidor NTP

Se você encontrar problemas com a estabilidade ou disponibilidade dos servidores NTP especificados originalmente durante a instalação, poderá atualizar a lista de fontes NTP externas que o sistema StorageGRID usa adicionando servidores adicionais ou atualizando ou removendo servidores existentes.
