---
permalink: maintain/copying-audit-logs-from-failed-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, non-primary admin node, non primary admin node 
summary: Se você conseguir copiar os logs de auditoria do nó de administração com falha, deverá preservá-los para manter o registro da atividade e do uso do sistema na grade.  Você pode restaurar os logs de auditoria preservados para o nó administrativo não primário recuperado depois que ele estiver instalado e funcionando. 
---
= Copiar logs de auditoria do nó administrativo não primário com falha
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você conseguir copiar os logs de auditoria do nó de administração com falha, deverá preservá-los para manter o registro da atividade e do uso do sistema na grade.  Você pode restaurar os logs de auditoria preservados para o nó administrativo não primário recuperado depois que ele estiver instalado e funcionando.

Este procedimento copia os arquivos de log de auditoria do nó administrativo com falha para um local temporário em um nó de grade separado.  Esses logs de auditoria preservados podem então ser copiados para o nó de administração de substituição.  Os logs de auditoria não são copiados automaticamente para o novo nó de administração.

Dependendo do tipo de falha, talvez você não consiga copiar logs de auditoria de um nó de administração com falha.  Se a implantação tiver apenas um nó administrativo, o nó administrativo recuperado começará a registrar eventos no log de auditoria em um novo arquivo vazio e os dados registrados anteriormente serão perdidos.  Se a implantação incluir mais de um nó de administração, você poderá recuperar os logs de auditoria de outro nó de administração.


NOTE: Se os logs de auditoria não estiverem acessíveis no nó de administração com falha agora, você poderá acessá-los mais tarde, por exemplo, após a recuperação do host.

. Se possível, faça login no nó de administração com falha.  Caso contrário, efetue login no nó de administração principal ou em outro nó de administração, se disponível.
+
.. Digite o seguinte comando: `ssh admin@grid_node_IP`
.. Digite a senha listada no `Passwords.txt` arquivo.
.. Digite o seguinte comando para alternar para root: `su -`
.. Digite a senha listada no `Passwords.txt` arquivo.


+
Quando você está logado como root, o prompt muda de `$` para `#` .

. Pare o serviço AMS para evitar que ele crie um novo arquivo de log:``service ams stop``
. Navegue até o diretório de exportação de auditoria:
+
`cd /var/local/log`

. Renomeie o arquivo audit.log de origem para um nome de arquivo numerado exclusivo.  Por exemplo, renomeie o arquivo audit.log para `2023-10-25.txt.1` .
+
[listing]
----
ls -l
mv audit.log 2023-10-25.txt.1
----
. Reinicie o serviço AMS: `service ams start`
. Crie o diretório para copiar todos os arquivos de log de auditoria para um local temporário em um nó de grade separado: `ssh admin@grid_node_IP mkdir -p /var/local/tmp/saved-audit-logs`
+
Quando solicitado, digite a senha do administrador.

. Copie todos os arquivos de log de auditoria para o local temporário: `scp -p * admin@grid_node_IP:/var/local/tmp/saved-audit-logs`
+
Quando solicitado, digite a senha do administrador.

. Sair como root: `exit`

