---
permalink: maintain/grid-node-procedures.html 
sidebar: sidebar 
keywords: storagegrid, grid node procedure 
summary: Pode ser necessário executar procedimentos de manutenção relacionados a nós de grade ou serviços de nós específicos. 
---
= Procedimentos de manutenção de nós
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode ser necessário executar procedimentos de manutenção relacionados a nós de grade ou serviços de nós específicos.

Procedimentos do Gerenciador de Servidores:: O Gerenciador do Servidor é executado em cada nó da grade para supervisionar o início e a interrupção dos serviços e para garantir que os serviços entrem e saiam do sistema StorageGRID sem problemas.  O Gerenciador do Servidor também monitora os serviços em cada nó da grade e tentará reiniciar automaticamente quaisquer serviços que relatem falhas.
+
--
Para executar procedimentos do Gerenciador do Servidor, normalmente você precisa acessar a linha de comando do nó.


NOTE: Você deve acessar o Gerenciador do Servidor somente se o suporte técnico tiver instruído você a fazê-lo.


NOTE: Você deve fechar a sessão atual do shell de comando e fazer logout após terminar de usar o Gerenciador do Servidor.  Digitar: `exit`

--
Procedimentos de reinicialização, desligamento e energia do nó:: Use esses procedimentos para reinicializar um ou mais nós, desligar e reiniciar nós ou desligar e ligar novamente os nós.
Procedimentos de remapeamento de portas:: Você pode usar os procedimentos de remapeamento de porta para remover os remapeamentos de porta de um nó, por exemplo, se quiser configurar um ponto de extremidade do balanceador de carga usando uma porta que foi remapeada anteriormente.

