---
permalink: maintain/preparing-appliance-storage-node-for-reinstallation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: Ao recuperar um nó de armazenamento do dispositivo, você deve primeiro preparar o dispositivo para a reinstalação do software StorageGRID . 
---
= Preparar o nó de armazenamento do dispositivo para reinstalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao recuperar um nó de armazenamento do dispositivo, você deve primeiro preparar o dispositivo para a reinstalação do software StorageGRID .

.Passos
. Efetue login no nó de armazenamento com falha:
+
.. Digite o seguinte comando: `ssh admin@_grid_node_IP_`
.. Digite a senha listada no `Passwords.txt` arquivo.
.. Digite o seguinte comando para alternar para root: `su -`
.. Digite a senha listada no `Passwords.txt` arquivo.


+
Quando você está logado como root, o prompt muda de `$` para `#` .

. Prepare o nó de armazenamento do dispositivo para a instalação do software StorageGRID . `sgareinstall`
. Quando solicitado a continuar, digite: `y`
+
O dispositivo é reinicializado e sua sessão SSH termina.  Geralmente, leva cerca de 5 minutos para que o instalador do StorageGRID Appliance fique disponível, embora em alguns casos você possa precisar esperar até 30 minutos.

+

CAUTION: Não tente acelerar a reinicialização desligando e ligando novamente ou reiniciando o aparelho de qualquer outra forma.  Você pode interromper atualizações automáticas de BIOS, BMC ou outros firmwares.

+
O nó de armazenamento do dispositivo StorageGRID é redefinido e os dados no nó de armazenamento não ficam mais acessíveis.  Os endereços IP configurados durante o processo de instalação original devem permanecer intactos; no entanto, é recomendável que você confirme isso quando o procedimento for concluído.

+
Após executar o `sgareinstall` comando, todas as contas, senhas e chaves SSH provisionadas StorageGRID são removidas e novas chaves de host são geradas.


