---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: Você deve concluir uma série de tarefas para recuperar um nó de armazenamento baseado em software onde um ou mais volumes de armazenamento no nó de armazenamento falharam, mas a unidade do sistema está intacta.  Se apenas os volumes de armazenamento falharem, o nó de armazenamento ainda estará disponível para o sistema StorageGRID . 
---
= Recuperar de falha de volume de armazenamento onde a unidade do sistema está intacta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve concluir uma série de tarefas para recuperar um nó de armazenamento baseado em software onde um ou mais volumes de armazenamento no nó de armazenamento falharam, mas a unidade do sistema está intacta.  Se apenas os volumes de armazenamento falharem, o nó de armazenamento ainda estará disponível para o sistema StorageGRID .


NOTE: Este procedimento de recuperação se aplica somente a nós de armazenamento baseados em software.  Se os volumes de armazenamento falharem em um nó de armazenamento do dispositivo, use o procedimento do dispositivo:link:recovering-storagegrid-appliance-storage-node.html["Recuperar nó de armazenamento do dispositivo"] .

Este procedimento de recuperação inclui as seguintes tarefas:

* link:reviewing-warnings-about-storage-volume-recovery.html["Revisar avisos para recuperação de volume de armazenamento"]
* link:identifying-and-unmounting-failed-storage-volumes.html["Identificar e desmontar volumes de armazenamento com falha"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Recuperar os volumes e reconstruir o banco de dados Cassandra"]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Restaurar dados do objeto"]
* link:checking-storage-state-after-recovering-storage-volumes.html["Verifique o estado do armazenamento"]

