---
permalink: maintain/replacing-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace primary admin node, replacing primary admin node, primary admin node 
summary: Para recuperar um nó de administração primário, você deve primeiro substituir o hardware físico ou virtual. 
---
= Substituir nó de administração primário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para recuperar um nó de administração primário, você deve primeiro substituir o hardware físico ou virtual.

Você pode substituir um nó de administração primário com falha por um nó de administração primário em execução na mesma plataforma ou pode substituir um nó de administração primário em execução no VMware ou em um host Linux por um nó de administração primário hospedado em um dispositivo de serviços.

Use o procedimento que corresponde à plataforma de substituição selecionada para o nó.  Depois de concluir o procedimento de substituição do nó (que é adequado para todos os tipos de nó), esse procedimento o direcionará para a próxima etapa para recuperação do nó de administração primário.

[cols="1a,2a"]
|===
| Plataforma de substituição | Procedimento 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Substituir um nó VMware"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Substituir um nó Linux"]



 a| 
Aparelhos de serviços
 a| 
link:replacing-failed-node-with-services-appliance.html["Substituir um aparelho de serviços"]



 a| 
OpenStack
 a| 
Os arquivos de disco de máquina virtual e scripts fornecidos pela NetApp para OpenStack não são mais suportados para operações de recuperação.  Se você precisar recuperar um nó em execução em uma implantação do OpenStack, baixe os arquivos para seu sistema operacional Linux.  Em seguida, siga o procedimento paralink:all-node-types-replacing-linux-node.html["substituindo um nó Linux"] .

|===