---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node 
summary: Se quiser manter as informações históricas sobre atributos e alertas em um nó administrativo não primário que falhou, você pode restaurar o banco de dados do nó administrativo a partir do nó administrativo primário. 
---
= Restaurar o banco de dados do nó de administração ao recuperar o nó de administração não primário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se quiser manter as informações históricas sobre atributos e alertas em um nó administrativo não primário que falhou, você pode restaurar o banco de dados do nó administrativo a partir do nó administrativo primário.

.Antes de começar
* O nó de administração recuperado está instalado e em execução.
* O sistema StorageGRID inclui pelo menos dois nós de administração.
* Você tem o `Passwords.txt` arquivo.
* Você tem a senha de provisionamento.


.Sobre esta tarefa
Se um nó administrativo falhar, as informações históricas armazenadas no banco de dados do nó administrativo serão perdidas.  Este banco de dados inclui as seguintes informações:

* Histórico de alertas
* Dados de atributos históricos, que são usados em gráficos de estilo legado na página Nós


Quando você recupera um nó de administração, o processo de instalação do software cria um banco de dados de nó de administração vazio no nó recuperado.  No entanto, o novo banco de dados inclui apenas informações de servidores e serviços que atualmente fazem parte do sistema ou foram adicionados posteriormente.

Se você restaurou um nó administrativo não primário, poderá restaurar as informações históricas copiando o banco de dados do nó administrativo do nó administrativo primário (o _nó administrativo de origem_) para o nó recuperado.


NOTE: Copiar o banco de dados do nó de administração pode levar várias horas.  Alguns recursos do Grid Manager ficarão indisponíveis enquanto os serviços estiverem interrompidos no nó de origem.

.Passos
. Efetue login no nó de administração de origem:
+
.. Digite o seguinte comando: `ssh admin@_grid_node_IP_`
.. Digite a senha listada no `Passwords.txt` arquivo.
.. Digite o seguinte comando para alternar para root: `su -`
.. Digite a senha listada no `Passwords.txt` arquivo.


. Execute o seguinte comando no nó de administração de origem.  Em seguida, insira a senha de provisionamento, se solicitado. `recover-access-points`
. No nó de administração de origem, pare o serviço MI: `service mi stop`
. No nó de administração de origem, pare o serviço Management Application Program Interface (mgmt-api): `service mgmt-api stop`
. Conclua as seguintes etapas no nó de administração recuperado:
+
.. Efetue login no nó de administração recuperado:
+
... Digite o seguinte comando: `ssh admin@_grid_node_IP_`
... Digite a senha listada no `Passwords.txt` arquivo.
... Digite o seguinte comando para alternar para root: `su -`
... Digite a senha listada no `Passwords.txt` arquivo.


.. Pare o serviço MI: `service mi stop`
.. Pare o serviço mgmt-api: `service mgmt-api stop`
.. Adicione a chave privada SSH ao agente SSH.  Digitar:``ssh-add``
.. Digite a senha de acesso SSH listada no `Passwords.txt` arquivo.
.. Copie o banco de dados do nó de administração de origem para o nó de administração recuperado: `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. Quando solicitado, confirme que deseja substituir o banco de dados MI no nó de administração recuperado.
+
O banco de dados e seus dados históricos são copiados para o nó de administração recuperado.  Quando a operação de cópia estiver concluída, o script inicia o nó de administração recuperado.

.. Quando você não precisar mais de acesso sem senha a outros servidores, remova a chave privada do agente SSH.  Digitar:``ssh-add -D``


. Reinicie os serviços no nó de administração de origem: `service servermanager start`

