---
permalink: maintain/restoring-existing-nodes.html 
sidebar: sidebar 
keywords: recover, restore node to host, node configuration file, start host service 
summary: Para restaurar um nó de grade com falha em um novo host Linux, execute estas etapas para restaurar o arquivo de configuração do nó. 
---
= Restaurar nós de grade para o host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para restaurar um nó de grade com falha em um novo host Linux, execute estas etapas para restaurar o arquivo de configuração do nó.

. <<restore-validate-grid-nodes,Restaurar e validar o nó>>restaurando o arquivo de configuração do nó.  Para uma nova instalação, crie um arquivo de configuração de nó para cada nó de grade a ser instalado em um host.  Ao restaurar um nó de grade para um host de substituição, você restaura ou substitui o arquivo de configuração do nó para quaisquer nós de grade com falha.
. <<start-storagegrid-host-service,Inicie o serviço do host StorageGRID>> .
. Conforme necessário,<<recover-nodes-fail-start,recuperar todos os nós que não iniciam>> .


Se algum volume de armazenamento em bloco foi preservado do host anterior, talvez seja necessário executar procedimentos de recuperação adicionais.  Os comandos nesta seção ajudam a determinar quais procedimentos adicionais são necessários.



== Restaurar e validar nós de grade

Você deve restaurar os arquivos de configuração da grade para quaisquer nós de grade com falha e, em seguida, validar os arquivos de configuração da grade e resolver quaisquer erros.

.Sobre esta tarefa
Você pode importar qualquer nó de grade que deva estar presente no host, desde que seja `/var/local` o volume não foi perdido como resultado da falha do host anterior.  Por exemplo, o `/var/local` o volume ainda pode existir se você usou armazenamento compartilhado para volumes de dados do sistema StorageGRID , conforme descrito nas instruções de instalação do StorageGRID para seu sistema operacional Linux.  A importação do nó restaura seu arquivo de configuração do nó no host.

Se não for possível importar os nós ausentes, você deverá recriar os arquivos de configuração da grade.

Você deve então validar o arquivo de configuração da grade e resolver quaisquer problemas de rede ou armazenamento que possam ocorrer antes de reiniciar o StorageGRID.  Ao recriar o arquivo de configuração para um nó, você deve usar o mesmo nome para o nó de substituição que foi usado para o nó que você está recuperando.

Consulte as instruções de instalação para obter mais informações sobre a localização do `/var/local` volume para um nó.

* link:../rhel/index.html["Instalar o StorageGRID no Red Hat Enterprise Linux"]
* link:../ubuntu/index.html["Instalar o StorageGRID no Ubuntu ou Debian"]


.Passos
. Na linha de comando do host recuperado, liste todos os nós StorageGRID configurados atualmente:``sudo storagegrid node list``
+
Se nenhum nó de grade estiver configurado, não haverá saída.  Se alguns nós de grade estiverem configurados, espere uma saída no seguinte formato:

+
[listing]
----
Name               Metadata-Volume
================================================================
dc1-adm1           /dev/mapper/sgws-adm1-var-local
dc1-gw1            /dev/mapper/sgws-gw1-var-local
dc1-sn1            /dev/mapper/sgws-sn1-var-local
dc1-arc1           /dev/mapper/sgws-arc1-var-local
----
+
Se alguns ou todos os nós de grade que devem ser configurados no host não estiverem listados, você precisará restaurar os nós de grade ausentes.

. Para importar nós de grade que tenham um `/var/local` volume:
+
.. Execute o seguinte comando para cada nó que você deseja importar:``sudo storagegrid node import node-var-local-volume-path``
+
O `storagegrid node import` O comando será bem-sucedido somente se o nó de destino tiver sido desligado corretamente no host em que foi executado pela última vez.  Se esse não for o caso, você observará um erro semelhante ao seguinte:

+
`This node (_node-name_) appears to be owned by another host (UUID host-uuid).`

+
`Use the --force flag if you are sure import is safe.`

.. Se você vir o erro sobre o nó pertencer a outro host, execute o comando novamente com o `--force` sinalizador para concluir a importação:``sudo storagegrid --force node import node-var-local-volume-path``
+

NOTE: Todos os nós importados com o `--force` a bandeira exigirá etapas adicionais de recuperação antes de poder retornar à rede, conforme descrito emlink:whats-next-performing-additional-recovery-steps-if-required.html["Próximo passo: execute etapas adicionais de recuperação, se necessário"] .



. Para nós de grade que não têm um `/var/local` volume, recrie o arquivo de configuração do nó para restaurá-lo no host. Para obter instruções, consulte:
+
** link:../rhel/creating-node-configuration-files.html["Criar arquivos de configuração de nó para o Red Hat Enterprise Linux"]
** link:../ubuntu/creating-node-configuration-files.html["Crie arquivos de configuração de nó para Ubuntu ou Debian"]
+

NOTE: Ao recriar o arquivo de configuração para um nó, você deve usar o mesmo nome para o nó de substituição que foi usado para o nó que você está recuperando.  Para implantações do Linux, certifique-se de que o nome do arquivo de configuração contenha o nome do nó.  Você deve usar as mesmas interfaces de rede, mapeamentos de dispositivos de bloco e endereços IP sempre que possível.  Essa prática minimiza a quantidade de dados que precisam ser copiados para o nó durante a recuperação, o que pode tornar a recuperação significativamente mais rápida (em alguns casos, minutos em vez de semanas).

+

NOTE: Se você usar quaisquer novos dispositivos de bloco (dispositivos que o nó StorageGRID não usou anteriormente) como valores para qualquer uma das variáveis ​​de configuração que começam com `BLOCK_DEVICE_` ao recriar o arquivo de configuração para um nó, siga as diretrizes em<<fix-block-errors,Corrigir erros de dispositivos de bloco ausentes>> .



. Execute o seguinte comando no host recuperado para listar todos os nós do StorageGRID .
+
`sudo storagegrid node list`

. Valide o arquivo de configuração do nó para cada nó da grade cujo nome foi mostrado na saída da lista de nós do storagegrid:
+
`sudo storagegrid node validate _node-name_`

+
Você deve corrigir quaisquer erros ou avisos antes de iniciar o serviço de host do StorageGRID .  As seções a seguir fornecem mais detalhes sobre erros que podem ter significado especial durante a recuperação.





=== Corrigir erros de interface de rede ausentes

Se a rede do host não estiver configurada corretamente ou um nome estiver escrito incorretamente, ocorrerá um erro quando o StorageGRID verificar o mapeamento especificado no `/etc/storagegrid/nodes/_node-name_.conf` arquivo.

Você pode ver um erro ou aviso correspondente a este padrão:

[listing]
----
Checking configuration file /etc/storagegrid/nodes/<node-name>.conf for node <node-name>...
ERROR: <node-name>: GRID_NETWORK_TARGET = <host-interface-name>
       <node-name>: Interface <host-interface-name>' does not exist
----
O erro pode ser relatado para a Rede Grid, a Rede Admin ou a Rede Cliente.  Este erro significa que o `/etc/storagegrid/nodes/_node-name_.conf` arquivo mapeia a rede StorageGRID indicada para a interface do host chamada `_host-interface-name_` , mas não há nenhuma interface com esse nome no host atual.

Se você receber esse erro, verifique se concluiu as etapas emlink:deploying-new-linux-hosts.html["Implantar novos hosts Linux"] .  Use os mesmos nomes para todas as interfaces de host que foram usados no host original.

Se você não conseguir nomear as interfaces do host para corresponder ao arquivo de configuração do nó, poderá editar o arquivo de configuração do nó e alterar o valor de GRID_NETWORK_TARGET, ADMIN_NETWORK_TARGET ou CLIENT_NETWORK_TARGET para corresponder a uma interface do host existente.

Certifique-se de que a interface do host forneça acesso à porta de rede física ou VLAN apropriada e que a interface não faça referência direta a um dispositivo de ligação ou ponte.  Você deve configurar uma VLAN (ou outra interface virtual) sobre o dispositivo de ligação no host ou usar um par de ponte e Ethernet virtual (veth).



=== Corrigir erros de dispositivos de bloco ausentes

O sistema verifica se cada nó recuperado mapeia para um arquivo especial de dispositivo de bloco válido ou um softlink válido para um arquivo especial de dispositivo de bloco.  Se o StorageGRID encontrar um mapeamento inválido no `/etc/storagegrid/nodes/_node-name_.conf` arquivo, um erro de dispositivo de bloco ausente é exibido.

Se você observar um erro que corresponde a este padrão:

[listing]
----
Checking configuration file /etc/storagegrid/nodes/<node-name>.conf for node <node-name>...
ERROR: <node-name>: BLOCK_DEVICE_PURPOSE = <path-name>
       <node-name>: <path-name> does not exist
----
Isso significa que `/etc/storagegrid/nodes/_node-name_.conf` mapeia o dispositivo de bloco usado por _node-name_ para `PURPOSE` para o caminho fornecido no sistema de arquivos Linux, mas não há um arquivo especial de dispositivo de bloco válido, ou link simbólico para um arquivo especial de dispositivo de bloco, naquele local.

Verifique se você concluiu as etapas emlink:deploying-new-linux-hosts.html["Implantar novos hosts Linux"] .  Use os mesmos nomes de dispositivos persistentes para todos os dispositivos de bloco que foram usados no host original.

Se você não conseguir restaurar ou recriar o arquivo especial do dispositivo de bloco ausente, poderá alocar um novo dispositivo de bloco do tamanho e categoria de armazenamento apropriados e editar o arquivo de configuração do nó para alterar o valor de `BLOCK_DEVICE_PURPOSE` para apontar para o novo arquivo especial do dispositivo de bloco.

Determine o tamanho e a categoria de armazenamento apropriados usando as tabelas para seu sistema operacional Linux:

* link:../rhel/storage-and-performance-requirements.html["Requisitos de armazenamento e desempenho para o Red Hat Enterprise Linux"]
* link:../ubuntu/storage-and-performance-requirements.html["Requisitos de armazenamento e desempenho para Ubuntu ou Debian"]


Revise as recomendações para configurar o armazenamento do host antes de prosseguir com a substituição do dispositivo de bloco:

* link:../rhel/configuring-host-storage.html["Configurar armazenamento de host para Red Hat Enterprise Linux"]
* link:../ubuntu/configuring-host-storage.html["Configurar armazenamento de host para Ubuntu ou Debian"]



NOTE: Se você precisar fornecer um novo dispositivo de armazenamento em bloco para qualquer uma das variáveis do arquivo de configuração começando com `BLOCK_DEVICE_` como o dispositivo de bloco original foi perdido com o host com falha, certifique-se de que o novo dispositivo de bloco não esteja formatado antes de tentar procedimentos de recuperação adicionais.  O novo dispositivo de bloco não será formatado se você estiver usando armazenamento compartilhado e tiver criado um novo volume.  Se não tiver certeza, execute o seguinte comando em qualquer novo arquivo especial do dispositivo de armazenamento em bloco.

[CAUTION]
====
Execute o seguinte comando somente para novos dispositivos de armazenamento em bloco.  Não execute este comando se você acredita que o armazenamento em bloco ainda contém dados válidos para o nó que está sendo recuperado, pois todos os dados no dispositivo serão perdidos.

`sudo dd if=/dev/zero of=/dev/mapper/my-block-device-name bs=1G count=1`

====


== Iniciar serviço de host StorageGRID

Para iniciar seus nós StorageGRID e garantir que eles reiniciem após uma reinicialização do host, você deve habilitar e iniciar o serviço do host StorageGRID .

.Passos
. Execute os seguintes comandos em cada host:
+
[listing]
----
sudo systemctl enable storagegrid
sudo systemctl start storagegrid
----
. Execute o seguinte comando para garantir que a implantação esteja em andamento:
+
[listing]
----
sudo storagegrid node status node-name
----
. Se algum nó retornar o status "Não em execução" ou "Parado", execute o seguinte comando:
+
[listing]
----
sudo storagegrid node start node-name
----
. Se você habilitou e iniciou o serviço de host StorageGRID anteriormente (ou se não tiver certeza se o serviço foi habilitado e iniciado), execute também o seguinte comando:
+
[listing]
----
sudo systemctl reload-or-restart storagegrid
----




== Recuperar nós que não iniciam normalmente

Se um nó StorageGRID não se juntar novamente à grade normalmente e não aparecer como recuperável, ele pode estar corrompido.  Você pode forçar o nó a entrar no modo de recuperação.

.Passos
. Confirme se a configuração de rede do nó está correta.
+
O nó pode não ter conseguido se reintegrar à rede devido a mapeamentos incorretos da interface de rede ou a um endereço IP ou gateway incorreto da rede de rede.

. Se a configuração da rede estiver correta, emita o `force-recovery` comando:
+
`sudo storagegrid node force-recovery _node-name_`

. Execute as etapas adicionais de recuperação para o nó. Ver link:whats-next-performing-additional-recovery-steps-if-required.html["Próximo passo: execute etapas adicionais de recuperação, se necessário"] .

