---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: 'Na Etapa 3 \(Revisar políticas do ILM\) do assistente de descomissionamento do site, você pode determinar se o site é referenciado por alguma política do ILM.' 
---
= Etapa 3: Revisar as políticas do ILM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na Etapa 3 (Revisar políticas do ILM) do assistente de descomissionamento do site, você pode determinar se o site é referenciado por alguma política do ILM.

.Antes de começar
Você tem um bom entendimento de comolink:../ilm/index.html["gerenciar objetos com ILM"] .  Você está familiarizado com a criação de pools de armazenamento e regras de ILM e com a simulação e ativação de uma política de ILM.

.Sobre esta tarefa
O StorageGRID não pode desativar um site se qualquer regra do ILM em qualquer política (ativa ou inativa) fizer referência a esse site.

Se alguma política do ILM fizer referência ao site que você deseja desativar, você deverá remover essas políticas ou editá-las para que atendam a estes requisitos:

* Proteja totalmente todos os dados do objeto.
* Não faça referência ao local que você está desativando.
* Não use pools de armazenamento que se refiram ao site ou use a opção Todos os sites.
* Não use perfis de codificação de eliminação que façam referência ao site.
* Não use a regra Fazer 2 cópias do StorageGRID 11.6 ou instalações anteriores.



CAUTION: Nunca crie uma regra ILM de cópia única para acomodar a remoção de um site.  Uma regra de ILM que cria apenas uma cópia replicada para qualquer período de tempo coloca os dados em risco de perda permanente.  Se existir apenas uma cópia replicada de um objeto, esse objeto será perdido se um nó de armazenamento falhar ou tiver um erro significativo.  Você também perde temporariamente o acesso ao objeto durante procedimentos de manutenção, como atualizações.


TIP: Se você estiver executando uma _desativação de site conectado_, deverá considerar como o StorageGRID deve gerenciar os dados do objeto atualmente no site que você deseja remover.  Dependendo dos seus requisitos de proteção de dados, novas regras podem mover dados de objetos existentes para sites diferentes ou podem excluir quaisquer cópias extras de objetos que não sejam mais necessárias.

Entre em contato com o suporte técnico se precisar de assistência para criar uma nova política.

.Passos
. Na Etapa 3 (Revisar políticas do ILM), determine se alguma política do ILM se refere ao site que você selecionou para descomissionar.
. Se nenhuma política estiver listada, selecione *Avançar* para ir paralink:step-4-remove-ilm-references.html["Etapa 4: Remover referências ILM"] .
. Se uma ou mais políticas ILM _ativas_ estiverem listadas, clone cada política existente ou crie novas políticas que não façam referência ao site que está sendo desativado:
+
.. Selecione o link para a política na coluna Nome da política.
+
A página de detalhes da política do ILM aparece em uma nova guia do navegador.  A página do Site de Desativação permanecerá aberta na outra aba.

.. Siga estas diretrizes e instruções conforme necessário:
+
*** Trabalhar com regras ILM:
+
**** link:../ilm/creating-storage-pool.html["Crie um ou mais pools de armazenamento"]que não se referem ao site.
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["Editar ou substituir regras"]que se referem ao site.
+

NOTE: Não selecione a regra *Fazer 2 cópias* porque ela usa o pool de armazenamento *Todos os nós de armazenamento*, o que não é permitido.



*** Trabalhar com políticas de ILM:
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["Clonar uma política de ILM existente"]oulink:../ilm/creating-ilm-policy.html["criar uma nova política de ILM"] .
**** Certifique-se de que a regra padrão e outras regras não se refiram ao site.
+

CAUTION: Você deve confirmar se as regras do ILM estão na ordem correta.  Quando a política é ativada, objetos novos e existentes são avaliados pelas regras na ordem listada, começando pelo topo.





.. Ingira objetos de teste e simule a política para garantir que as regras corretas sejam aplicadas.
+

CAUTION: Erros em uma política de ILM podem causar perda irrecuperável de dados.  Revise e simule cuidadosamente a política antes de ativá-la para confirmar se ela funcionará conforme o esperado.

+

CAUTION: Quando você ativa uma nova política de ILM, o StorageGRID a usa para gerenciar todos os objetos, incluindo objetos existentes e objetos recém-ingeridos.  Antes de ativar uma nova política de ILM, revise quaisquer alterações no posicionamento de objetos replicados e codificados para eliminação existentes.  Alterar a localização de um objeto existente pode resultar em problemas temporários de recursos quando os novos posicionamentos são avaliados e implementados.

.. Ative as novas políticas e garanta que as antigas estejam inativas.
+
Se você deseja ativar várias políticas,link:../ilm/creating-ilm-policy.html#activate-ilm-policy["siga as etapas para criar tags de política do ILM"] .

+
Se você estiver executando o descomissionamento de um site conectado, o StorageGRID começará a remover dados de objeto do site selecionado assim que você ativar a nova política de ILM.  Mover ou excluir todas as cópias de objetos pode levar semanas.  Embora você possa iniciar com segurança a desativação de um site enquanto os dados do objeto ainda estiverem no site, o procedimento de desativação será concluído mais rapidamente e com menos interrupções e impactos no desempenho se você permitir que os dados sejam movidos do site antes de iniciar o procedimento de desativação real (selecionando *Iniciar desativação* na Etapa 5 do assistente).



. Para cada política _inativa_, edite-a ou remova-a selecionando primeiro o link para cada política, conforme descrito nas etapas anteriores.
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["Editar a política"]portanto não se refere ao local a ser desativado.
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["Remover uma política"] .


. Quando você terminar de fazer alterações nas regras e políticas do ILM, não deverá haver mais políticas listadas na Etapa 3 (Revisar políticas do ILM). Selecione *Avançar*.
+
A etapa 4 (Remover referências ILM) é exibida.


