---
permalink: maintain/using-donotstart-file.html 
sidebar: sidebar 
keywords: storagegrid, recover, donotstart, do not start, donotstart file, do not start file 
summary: Se você estiver executando vários procedimentos de manutenção ou configuração sob a direção do suporte técnico, poderá ser solicitado a usar um arquivo DoNotStart para impedir que os serviços sejam iniciados quando o Gerenciador do Servidor for iniciado ou reiniciado. 
---
= Use um arquivo DoNotStart
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver executando vários procedimentos de manutenção ou configuração sob a direção do suporte técnico, poderá ser solicitado a usar um arquivo DoNotStart para impedir que os serviços sejam iniciados quando o Gerenciador do Servidor for iniciado ou reiniciado.


CAUTION: Você deve adicionar ou remover um arquivo DoNotStart somente se o suporte técnico tiver instruído você a fazer isso.

Para impedir que um serviço seja iniciado, coloque um arquivo DoNotStart no diretório do serviço que você deseja impedir que seja iniciado.  Na inicialização, o Gerenciador do Servidor procura o arquivo DoNotStart.  Se o arquivo estiver presente, o serviço (e quaisquer serviços dependentes dele) será impedido de iniciar.  Quando o arquivo DoNotStart for removido, o serviço interrompido anteriormente será iniciado na próxima inicialização ou reinicialização do Gerenciador do Servidor.  Os serviços não são iniciados automaticamente quando o arquivo DoNotStart é removido.

A maneira mais eficiente de impedir que todos os serviços sejam reiniciados é impedir que o serviço NTP seja iniciado.  Todos os serviços dependem do serviço NTP e não podem ser executados se o serviço NTP não estiver em execução.



== Adicionar arquivo DoNotStart para serviço

Você pode impedir que um serviço individual seja iniciado adicionando um arquivo DoNotStart ao diretório desse serviço em um nó de grade.

.Antes de começar
Você tem o `Passwords.txt` arquivo.

.Passos
. Efetue login no nó da grade:
+
.. Digite o seguinte comando: `ssh admin@_grid_node_IP_`
.. Digite a senha listada no `Passwords.txt` arquivo.
.. Digite o seguinte comando para alternar para root: `su -`
.. Digite a senha listada no `Passwords.txt` arquivo.


+
Quando você está logado como root, o prompt muda de `$` para `#` .

. Adicione um arquivo DoNotStart: `touch /etc/sv/_service_/DoNotStart`
+
onde `service` é o nome do serviço cuja inicialização será impedida. Por exemplo,

+
[listing]
----
touch /etc/sv/ldr/DoNotStart
----
+
Um arquivo DoNotStart é criado.  Nenhum conteúdo de arquivo é necessário.

+
Quando o Gerenciador do Servidor ou o nó da grade é reiniciado, o Gerenciador do Servidor é reiniciado, mas o serviço não.

. Sair do shell de comando: `exit`




== Remover arquivo DoNotStart para serviço

Ao remover um arquivo DoNotStart que está impedindo a inicialização de um serviço, você deve iniciar esse serviço.

.Antes de começar
Você tem o `Passwords.txt` arquivo.

.Passos
. Efetue login no nó da grade:
+
.. Digite o seguinte comando: `ssh admin@_grid_node_IP_`
.. Digite a senha listada no `Passwords.txt` arquivo.
.. Digite o seguinte comando para alternar para root: `su -`
.. Digite a senha listada no `Passwords.txt` arquivo.


+
Quando você está logado como root, o prompt muda de `$` para `#` .

. Remova o arquivo DoNotStart do diretório de serviço: `rm /etc/sv/_service_/DoNotStart`
+
onde `service` é o nome do serviço. Por exemplo,

+
[listing]
----
rm /etc/sv/ldr/DoNotStart
----
. Iniciar o serviço: `service _servicename_ start`
. Sair do shell de comando: `exit`

