---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: Se um nó da grade falhar, você deve recuperá-lo o mais rápido possível.  Você deve revisar todos os avisos e considerações para recuperação de nós antes de começar. 
---
= Avisos e considerações para recuperação de nós de rede
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se um nó da grade falhar, você deve recuperá-lo o mais rápido possível.  Você deve revisar todos os avisos e considerações para recuperação de nós antes de começar.


CAUTION: StorageGRID é um sistema distribuído composto por vários nós trabalhando em conjunto.  Não use snapshots de disco para restaurar nós de grade.  Em vez disso, consulte os procedimentos de recuperação e manutenção para cada tipo de nó.


NOTE: Se um site StorageGRID inteiro falhar, entre em contato com o suporte técnico. O suporte técnico trabalhará com você para desenvolver e executar um plano de recuperação de site que maximize a quantidade de dados recuperados e atenda aos seus objetivos comerciais. Ver link:how-site-recovery-is-performed-by-technical-support.html["Como o suporte técnico recupera um site"] .

Alguns dos motivos para recuperar um nó de rede com falha o mais rápido possível incluem o seguinte:

* Um nó de grade com falha pode reduzir a redundância dos dados do sistema e do objeto, deixando você vulnerável ao risco de perda permanente de dados se outro nó falhar.
* Um nó de rede com falha pode afetar a eficiência das operações diárias.
* Um nó de grade com falha pode reduzir sua capacidade de monitorar as operações do sistema.
* Um nó de grade com falha pode causar um erro interno do servidor 500 se regras rígidas de ILM estiverem em vigor.
* Se um nó da grade não for recuperado prontamente, o tempo de recuperação poderá aumentar.  Por exemplo, podem surgir filas que precisam ser limpas antes que a recuperação seja concluída.


Siga sempre o procedimento de recuperação para o tipo específico de nó de grade que você está recuperando.  Os procedimentos de recuperação variam para nós de administração primários ou não primários, nós de gateway, nós de dispositivos e nós de armazenamento.



== Pré-condições para recuperação de nós de grade

Todas as seguintes condições são assumidas ao recuperar nós de grade:

* O hardware físico ou virtual com falha foi substituído e configurado.
* A versão do instalador do dispositivo StorageGRID no dispositivo de substituição corresponde à versão do software do seu sistema StorageGRID , conforme descrito em https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["Verifique e atualize a versão do instalador do StorageGRID Appliance"^] .
* Se você estiver recuperando um nó de grade diferente do nó de administração primário, haverá conectividade entre o nó de grade que está sendo recuperado e o nó de administração primário.
* Se estiver recuperando um nó de armazenamento do dispositivo, você deverá especificar o mesmo tipo de armazenamento do dispositivo original (combinado, somente metadados ou somente dados) durante a instalação do dispositivo. Se você especificar um tipo de armazenamento diferente, a recuperação falhará e exigirá a reinstalação do dispositivo com o tipo de armazenamento correto especificado.




== Ordem de recuperação do nó se um servidor que hospeda mais de um nó de grade falhar

Se um servidor que hospeda mais de um nó de grade falhar, você poderá recuperar os nós em qualquer ordem. Entretanto, se o servidor com falha estiver hospedando o nó de administração principal, você deverá recuperar esse nó primeiro. Recuperar primeiro o nó de administração primário evita que outras recuperações de nós sejam interrompidas enquanto aguardam para entrar em contato com o nó de administração primário.



== Endereços IP para nós recuperados

Não tente recuperar um nó usando um endereço IP que esteja atualmente atribuído a qualquer outro nó.  Ao implantar o novo nó, use o endereço IP atual do nó com falha ou um endereço IP não utilizado.

Se você usar um novo endereço IP para implantar o novo nó e depois recuperá-lo, o novo endereço IP continuará a ser usado para o nó recuperado.  Se você quiser reverter para o endereço IP original, use a ferramenta Alterar IP após a conclusão da recuperação.
