---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: Os nós de administração fornecem serviços de gerenciamento, como configuração do sistema, monitoramento e registro.  Os nós de administração também podem ser usados para balancear a carga do tráfego do cliente S3.  Cada grade deve ter um nó administrativo primário e pode ter qualquer número de nós administrativos não primários para redundância. 
---
= O que é um nó de administração?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os nós de administração fornecem serviços de gerenciamento, como configuração do sistema, monitoramento e registro.  Os nós de administração também podem ser usados para balancear a carga do tráfego do cliente S3.  Cada grade deve ter um nó administrativo primário e pode ter qualquer número de nós administrativos não primários para redundância.



== Diferenças entre nós administrativos primários e não primários

Ao fazer login no Grid Manager ou no Tenant Manager, você está se conectando a um nó de administração. Você pode se conectar a qualquer nó administrativo, e cada nó administrativo exibe uma visão semelhante do sistema StorageGRID . No entanto, o nó administrativo primário fornece mais funcionalidades do que os nós administrativos não primários. Por exemplo, a maioria dos procedimentos de manutenção deve ser executada nos nós de administração primários.

A tabela resume os recursos dos nós administrativos primários e não primários.

[cols="2a,1a,1a"]
|===
| Capacidades | Nó de administração primário | Nó de administração não primário 


 a| 
Inclui o<<ams,AMS>> serviço
 a| 
Sim
 a| 
Sim



 a| 
Inclui o<<cmn,CMN>> serviço
 a| 
Sim
 a| 
Não



 a| 
Inclui o<<nms,NMS>> serviço
 a| 
Sim
 a| 
Sim



 a| 
Inclui o<<prometheus,Prometeu>> serviço
 a| 
Sim
 a| 
Sim



 a| 
Inclui o<<ssm,SSM>> serviço
 a| 
Sim
 a| 
Sim



 a| 
Inclui o<<load-balancer,Balanceador de carga>> e<<high-availability,Alta disponibilidade>> serviços
 a| 
Sim
 a| 
Sim



 a| 
Suporta o<<mgmt-api,Interface de Programa de Aplicação de Gerenciamento>> (mgmt-api)
 a| 
Sim
 a| 
Sim



 a| 
Pode ser usado para todas as tarefas de manutenção relacionadas à rede, por exemplo, alteração de endereço IP e atualização de servidores NTP
 a| 
Sim
 a| 
Não



 a| 
Pode executar o rebalanceamento do EC após a expansão do nó de armazenamento
 a| 
Sim
 a| 
Não



 a| 
Pode ser usado para o procedimento de restauração de volume
 a| 
Sim
 a| 
Sim



 a| 
Pode coletar arquivos de log e dados do sistema de um ou mais nós
 a| 
Sim
 a| 
Não



 a| 
Envia notificações de alerta, pacotes AutoSupport e traps SNMP e informa
 a| 
Sim. Atua como o<<preferred-sender,remetente preferencial>> .
 a| 
Sim. Atua como um remetente de espera.

|===


== [[preferred-sender]]Nó de administração do remetente preferencial

Se sua implantação do StorageGRID incluir vários nós de administração, o nó de administração principal será o remetente preferencial para notificações de alerta, pacotes de AutoSupport e traps e informações SNMP.

Em operações normais do sistema, somente o remetente preferido envia notificações. Entretanto, todos os outros nós administrativos monitoram o remetente preferido. Se um problema for detectado, outros nós administrativos atuam como _remetentes em espera_.

Várias notificações podem ser enviadas nestes casos:

* Se os nós administrativos ficarem "ilhados" uns dos outros, tanto o remetente preferencial quanto os remetentes em espera tentarão enviar notificações, e várias cópias das notificações poderão ser recebidas.
* Se o remetente em espera detectar problemas com o remetente preferencial e começar a enviar notificações, o remetente preferencial poderá recuperar sua capacidade de enviar notificações. Se isso ocorrer, notificações duplicadas poderão ser enviadas. O remetente em espera deixará de enviar notificações quando não detectar mais erros no remetente preferido.
+

NOTE: Quando você testa pacotes do AutoSupport , todos os nós administrativos enviam o teste.  Ao testar notificações de alerta, você deve fazer login em cada nó de administração para verificar a conectividade.





== Serviços primários para nós de administração

A tabela a seguir mostra os principais serviços para nós de administração; no entanto, esta tabela não lista todos os serviços dos nós.

[cols="1a,2a"]
|===
| Serviço | Função principal 


 a| 
[[ams]]Sistema de Gestão de Auditoria (AMS)
 a| 
Rastreia atividades e eventos do sistema.



 a| 
[[cmn]]Nó de Gerenciamento de Configuração (CMN)
 a| 
Gerencia a configuração de todo o sistema.



 a| 
[[alta disponibilidade]]Alta disponibilidade
 a| 
Gerencia endereços IP virtuais de alta disponibilidade para grupos de nós de administração e nós de gateway.

*Observação:* Este serviço também é encontrado em nós de gateway.



 a| 
[[load-balancer]]Balanceador de carga
 a| 
Fornece balanceamento de carga do tráfego S3 de clientes para nós de armazenamento.

*Observação:* Este serviço também é encontrado em nós de gateway.



 a| 
[[mgmt-api]]Interface de Programa de Aplicativo de Gerenciamento (mgmt-api)
 a| 
Processa solicitações da API de gerenciamento de grade e da API de gerenciamento de locatários.



 a| 
[[nms]]Sistema de gerenciamento de rede (NMS)
 a| 
Fornece funcionalidade para o Grid Manager.



 a| 
[[prometheus]]Prometeu
 a| 
Coleta e armazena métricas de séries temporais dos serviços em todos os nós.



 a| 
[[ssm]]Monitor de status do servidor (SSM)
 a| 
Monitora o sistema operacional e o hardware subjacente.

|===