---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines 
summary: Você pode expandir seu sistema StorageGRID adicionando um novo site. 
---
= Adicionar um novo site
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode expandir seu sistema StorageGRID adicionando um novo site.



== Diretrizes para adicionar um site

Antes de adicionar um site, revise os seguintes requisitos e limitações:

* Você só pode adicionar um site por operação de expansão.
* Não é possível adicionar nós de grade a um site existente como parte da mesma expansão.
* Todos os sites devem incluir pelo menos três nós de armazenamento.
* Adicionar um novo site não aumenta automaticamente o número de objetos que você pode armazenar.  A capacidade total de objetos de uma grade depende da quantidade de armazenamento disponível, da política de ILM e da capacidade de metadados em cada site.
* Ao dimensionar um novo site, você deve garantir que ele inclua capacidade de metadados suficiente.
+
O StorageGRID mantém uma cópia de todos os metadados do objeto em cada site.  Ao adicionar um novo site, você deve garantir que ele inclua capacidade de metadados suficiente para os metadados do objeto existente e capacidade de metadados suficiente para o crescimento.

+
Para mais informações, consulte o seguinte:

+
** link:../admin/managing-object-metadata-storage.html["Gerenciar armazenamento de metadados de objetos"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["Monitorar a capacidade de metadados do objeto para cada nó de armazenamento"]


* Você deve considerar a largura de banda de rede disponível entre os sites e o nível de latência da rede.  As atualizações de metadados são continuamente replicadas entre sites, mesmo que todos os objetos sejam armazenados apenas no site onde são ingeridos.
* Como seu sistema StorageGRID permanece operacional durante a expansão, você deve revisar as regras do ILM antes de iniciar o procedimento de expansão.  Você deve garantir que cópias de objetos não sejam armazenadas no novo site até que o procedimento de expansão seja concluído.
+
Por exemplo, antes de iniciar a expansão, determine se alguma regra usa o pool de armazenamento padrão (Todos os nós de armazenamento).  Se isso acontecer, você deverá criar um novo pool de armazenamento que contenha os nós de armazenamento existentes e atualizar suas regras de ILM para usar o novo pool de armazenamento.  Caso contrário, os objetos serão copiados para o novo site assim que o primeiro nó naquele site se tornar ativo.

+
Para obter mais informações sobre como alterar o ILM ao adicionar um novo site, consulte olink:../ilm/example-6-changing-ilm-policy.html["exemplo de alteração de uma política de ILM"] .


