---
permalink: expand/linux-adding-direct-attached-or-san-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expansion, Linux, add storage volumes 
summary: Se um nó de armazenamento incluir menos de 48 volumes de armazenamento, você poderá aumentar sua capacidade adicionando novos dispositivos de armazenamento em bloco, tornando-os visíveis aos hosts Linux e adicionando os novos mapeamentos de dispositivos em bloco ao arquivo de configuração StorageGRID usado para o nó de armazenamento. 
---
= Linux: Adicionar volumes SAN ou de conexão direta ao nó de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se um nó de armazenamento incluir menos de 48 volumes de armazenamento, você poderá aumentar sua capacidade adicionando novos dispositivos de armazenamento em bloco, tornando-os visíveis aos hosts Linux e adicionando os novos mapeamentos de dispositivos em bloco ao arquivo de configuração StorageGRID usado para o nó de armazenamento.

.Antes de começar
* Você tem acesso às instruções para instalar o StorageGRID na sua plataforma Linux.
+
** link:../rhel/index.html["Instalar o StorageGRID no Red Hat Enterprise Linux"]
** link:../ubuntu/index.html["Instalar o StorageGRID no Ubuntu ou Debian"]


* Você tem o `Passwords.txt` arquivo.
* Você temlink:../admin/admin-group-permissions.html["permissões de acesso específicas"] .



CAUTION: Não tente adicionar volumes de armazenamento a um nó de armazenamento enquanto uma atualização de software, procedimento de recuperação ou outro procedimento de expansão estiver ativo.

.Sobre esta tarefa
O nó de armazenamento fica indisponível por um breve período quando você adiciona volumes de armazenamento.  Você deve executar este procedimento em um nó de armazenamento por vez para evitar impactar os serviços de grade voltados para o cliente.

.Passos
. Instale o novo hardware de armazenamento.
+
Para obter mais informações, consulte a documentação fornecida pelo seu fornecedor de hardware.

. Crie novos volumes de armazenamento em bloco dos tamanhos desejados.
+
** Conecte as novas unidades e atualize a configuração do controlador RAID conforme necessário, ou aloque os novos SAN LUNs nos arrays de armazenamento compartilhados e permita que o host Linux os acesse.
** Use o mesmo esquema de nomenclatura persistente usado para os volumes de armazenamento no nó de armazenamento existente.
** Se você usar o recurso de migração de nó StorageGRID , torne os novos volumes visíveis para outros hosts Linux que são destinos de migração para este nó de armazenamento.  Para obter mais informações, consulte as instruções para instalar o StorageGRID na sua plataforma Linux.


. Efetue login no host Linux que suporta o Nó de Armazenamento como root ou com uma conta que tenha permissão sudo.
. Confirme se os novos volumes de armazenamento estão visíveis no host Linux.
+
Talvez seja necessário verificar novamente os dispositivos.

. Execute o seguinte comando para desabilitar temporariamente o nó de armazenamento:
+
`sudo storagegrid node stop <node-name>`

. Usando um editor de texto como vim ou pico, edite o arquivo de configuração do nó para o nó de armazenamento, que pode ser encontrado em `/etc/storagegrid/nodes/<node-name>.conf` .
. Localize a seção do arquivo de configuração do nó que contém os mapeamentos de dispositivos de bloco de armazenamento de objetos existentes.
+
No exemplo, `BLOCK_DEVICE_RANGEDB_00` para `BLOCK_DEVICE_RANGEDB_03` são os mapeamentos de dispositivos de bloco de armazenamento de objetos existentes.

+
[listing, subs="specialcharacters,quotes"]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/sgws-sn1-var-local
*BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/sgws-sn1-rangedb-0*
*BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/sgws-sn1-rangedb-1*
*BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/sgws-sn1-rangedb-2*
*BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/sgws-sn1-rangedb-3*
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----
. Adicione novos mapeamentos de dispositivos de bloco de armazenamento de objetos correspondentes aos volumes de armazenamento em bloco que você adicionou para este Nó de Armazenamento.
+
Certifique-se de começar no próximo `BLOCK_DEVICE_RANGEDB_nn` .  Não deixe espaço.

+
** Com base no exemplo acima, comece em `BLOCK_DEVICE_RANGEDB_04` .
** No exemplo abaixo, quatro novos volumes de armazenamento em bloco foram adicionados ao nó: `BLOCK_DEVICE_RANGEDB_04` para `BLOCK_DEVICE_RANGEDB_07` .


+
[listing, subs="specialcharacters,quotes"]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/sgws-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/sgws-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/sgws-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/sgws-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/sgws-sn1-rangedb-3
*BLOCK_DEVICE_RANGEDB_04 = /dev/mapper/sgws-sn1-rangedb-4*
*BLOCK_DEVICE_RANGEDB_05 = /dev/mapper/sgws-sn1-rangedb-5*
*BLOCK_DEVICE_RANGEDB_06 = /dev/mapper/sgws-sn1-rangedb-6*
*BLOCK_DEVICE_RANGEDB_07 = /dev/mapper/sgws-sn1-rangedb-7*
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----
. Execute o seguinte comando para validar suas alterações no arquivo de configuração do nó para o nó de armazenamento:
+
`sudo storagegrid node validate <node-name>`

+
Resolva quaisquer erros ou avisos antes de prosseguir para a próxima etapa.

+
[NOTE]
====
Se você observar um erro semelhante ao seguinte, significa que o arquivo de configuração do nó está tentando mapear o dispositivo de bloco usado por `<node-name>` para `<PURPOSE>` para o dado `<path-name>` no sistema de arquivos Linux, mas não há um arquivo especial de dispositivo de bloco válido (ou link simbólico para um arquivo especial de dispositivo de bloco) naquele local.

[listing]
----
Checking configuration file for node <node-name>…
ERROR: BLOCK_DEVICE_<PURPOSE> = <path-name>
<path-name> is not a valid block device
----
Verifique se você inseriu o correto `<path-name>` .

====
. Execute o seguinte comando para reiniciar o nó com os novos mapeamentos de dispositivos de bloco em vigor:
+
`sudo storagegrid node start <node-name>`

. Efetue login no nó de armazenamento como administrador usando a senha listada no `Passwords.txt` arquivo.
. Verifique se os serviços iniciam corretamente:
+
.. Veja uma lista do status de todos os serviços no servidor: +
`sudo storagegrid-status`
+
O status é atualizado automaticamente.

.. Aguarde até que todos os serviços estejam em execução ou verificados.
.. Sair da tela de status:
+
`Ctrl+C`



. Configure o novo armazenamento para uso pelo nó de armazenamento:
+
.. Configure os novos volumes de armazenamento:
+
`sudo add_rangedbs.rb`

+
Este script encontra novos volumes de armazenamento e solicita que você os formate.

.. Digite *y* para formatar os volumes de armazenamento.
.. Se algum dos volumes tiver sido formatado anteriormente, decida se você deseja reformatá-lo.
+
*** Digite *y* para reformatar.
*** Digite *n* para pular a reformatação.




+
O `setup_rangedbs.sh` o script é executado automaticamente.

. Verifique se o estado de armazenamento do nó de armazenamento está online:
+
.. Sign in no Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
.. Selecione *SUPORTE* > *Ferramentas* > *Topologia de grade*.
.. Selecione *_site_* > *_Nó de armazenamento_* > *LDR* > *Armazenamento*.
.. Selecione a aba *Configuração* e depois a aba *Principal*.
.. Se a lista suspensa *Estado de armazenamento - Desejado* estiver definida como Somente leitura ou Offline, selecione *Online*.
.. Clique em *Aplicar alterações*.


. Para ver os novos armazenamentos de objetos:
+
.. Selecione *NÓS* > *_site_* > *_Nó de Armazenamento_* > *Armazenamento*.
.. Veja os detalhes na tabela *Object Stores*.




.Resultado
Agora você pode usar a capacidade expandida dos Nós de Armazenamento para salvar dados de objetos.
