---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active 
summary: Após a conclusão de uma operação de expansão que adiciona novos nós de armazenamento, o sistema StorageGRID deve começar a usar automaticamente os novos nós de armazenamento.  Você deve usar o sistema StorageGRID para verificar se o novo nó de armazenamento está ativo. 
---
= Verifique se o nó de armazenamento está ativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após a conclusão de uma operação de expansão que adiciona novos nós de armazenamento, o sistema StorageGRID deve começar a usar automaticamente os novos nós de armazenamento.  Você deve usar o sistema StorageGRID para verificar se o novo nó de armazenamento está ativo.

.Passos
. Sign in no Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
. Selecione *NÓS* > *_Nó de Armazenamento de Expansão_* > *Armazenamento*.
. Posicione o cursor sobre o gráfico *Armazenamento usado - Dados do objeto* para visualizar o valor de *Usado*, que é a quantidade de espaço total utilizável que foi usada para dados do objeto.
. Verifique se o valor de *Usado* está aumentando à medida que você move o cursor para a direita no gráfico.

