---
permalink: troubleshoot/troubleshooting-network-hardware-and-platform-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot network, how to troubleshoot hardware, how to troubleshoot platform 
summary: Há várias tarefas que você pode executar para ajudar a determinar a origem dos problemas relacionados à rede, hardware e plataforma do StorageGRID . 
---
= Solucionar problemas de rede, hardware e plataforma
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há várias tarefas que você pode executar para ajudar a determinar a origem dos problemas relacionados à rede, hardware e plataforma do StorageGRID .



== Erros "422: Entidade não processável"

O erro 422: Entidade não processável pode ocorrer por diferentes motivos.  Verifique a mensagem de erro para determinar o que causou o problema.

Se você vir uma das mensagens de erro listadas, tome a ação recomendada.

[cols="2a,3a"]
|===
| Mensagem de erro | Causa raiz e ação corretiva 


 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration. Unable to
authenticate, please verify
your username and password:
LDAP Result Code 8 "Strong
Auth Required": 00002028:
LdapErr: DSID-0C090256,
comment: The server requires
binds to turn on integrity
checking if SSL\TLS are not
already active on the
connection, data 0, v3839
---- a| 
Esta mensagem pode ocorrer se você selecionar a opção *Não usar TLS* para Segurança da Camada de Transporte (TLS) ao configurar a federação de identidade usando o Windows Active Directory (AD).

O uso da opção *Não usar TLS* não é suportado para uso com servidores AD que impõem assinatura LDAP.  Você deve selecionar a opção *Usar STARTTLS* ou a opção *Usar LDAPS* para TLS.



 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration.Unable to
begin TLS, verify your
certificate and TLS
configuration: LDAP Result
Code 200 "Network Error":
TLS handshake failed
    (EOF)
---- a| 
Esta mensagem aparece se você tentar usar uma cifra não suportada para fazer uma conexão TLS (Transport Layer Security) do StorageGRID para um sistema externo usado para identificar federações ou pools de armazenamento em nuvem.

Verifique as cifras oferecidas pelo sistema externo.  O sistema deve utilizar um doslink:../admin/supported-ciphers-for-outgoing-tls-connections.html["cifras suportadas pelo StorageGRID"] para conexões TLS de saída, conforme mostrado nas instruções para administrar o StorageGRID.

|===


== [[troubleshoot_MTU_alert]]Alerta de incompatibilidade de MTU da rede de grade

O alerta *Incompatibilidade de MTU da rede de grade* é acionado quando a configuração da unidade máxima de transmissão (MTU) para a interface da rede de grade (eth0) difere significativamente entre os nós da grade.

.Sobre esta tarefa
As diferenças nas configurações de MTU podem indicar que algumas, mas não todas, redes eth0 estão configuradas para quadros jumbo.  Uma incompatibilidade de tamanho de MTU maior que 1000 pode causar problemas de desempenho de rede.

.Passos
. Liste as configurações de MTU para eth0 em todos os nós.
+
** Use a consulta fornecida no Grid Manager.
** Navegar para `_primary Admin Node IP address_/metrics/graph` e insira a seguinte consulta: `node_network_mtu_bytes{device="eth0"}`


. https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["Modificar as configurações de MTU"^]conforme necessário para garantir que sejam os mesmos para a interface da rede Grid (eth0) em todos os nós.
+
** Para nós baseados em Linux e VMware, use o seguinte comando: `+/usr/sbin/change-ip.py [-h] [-n node] mtu network [network...]+`
+
*Exemplo*: `change-ip.py -n node 1500 grid admin`

+
*Observação*: Em nós baseados em Linux, se o valor de MTU desejado para a rede no contêiner exceder o valor já configurado na interface do host, você deve primeiro configurar a interface do host para ter o valor de MTU desejado e, em seguida, usar o `change-ip.py` script para alterar o valor de MTU da rede no contêiner.

+
Use os seguintes argumentos para modificar a MTU em nós baseados em Linux ou VMware.

+
[cols="1a,2a"]
|===
| Argumentos posicionais | Descrição 


 a| 
`mtu`
 a| 
A MTU a ser definida.  Deve estar no intervalo de 1280 a 9216.



 a| 
`network`
 a| 
As redes às quais a MTU será aplicada.  Inclua um ou mais dos seguintes tipos de rede:

*** grade
*** administrador
*** cliente


|===
+
[cols="2a,2a"]
|===
| Argumentos opcionais | Descrição 


 a| 
`-h, – help`
 a| 
Mostrar a mensagem de ajuda e sair.



 a| 
`-n node, --node node`
 a| 
O nó.  O padrão é o nó local.

|===






== Alerta de erro de quadro de recepção de rede de nó

Alertas de *Erro de quadro de recepção de rede de nó* podem ser causados ​​por problemas de conectividade entre o StorageGRID e seu hardware de rede.  Este alerta desaparece sozinho depois que o problema subjacente é resolvido.

.Sobre esta tarefa
Os alertas de *Erro de quadro de recepção de rede de nó* podem ser causados ​​pelos seguintes problemas com o hardware de rede que se conecta ao StorageGRID:

* A correção de erros antecipada (FEC) é necessária e não está em uso
* Incompatibilidade de porta do switch e MTU da placa de rede
* Altas taxas de erro de link
* Estouro do buffer de anel da placa de rede


.Passos
. Siga as etapas de solução de problemas para todas as possíveis causas desse alerta, de acordo com sua configuração de rede.
. Execute as seguintes etapas dependendo da causa do erro:
+
[role="tabbed-block"]
====
.Incompatibilidade de FEC
--

NOTE: Essas etapas são aplicáveis ​​somente para alertas de *Erro de quadro de recepção de rede de nó* causados ​​por incompatibilidade de FEC em dispositivos StorageGRID .

.. Verifique o status FEC da porta no switch conectado ao seu dispositivo StorageGRID .
.. Verifique a integridade física dos cabos do aparelho até o switch.
.. Se você quiser alterar as configurações do FEC para tentar resolver o alerta, primeiro certifique-se de que o dispositivo esteja configurado para o modo *Automático* na página Configuração de link do instalador do dispositivo StorageGRID (consulte as instruções para seu dispositivo:
+
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SG6160"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SGF6112"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/changing-link-configuration-of-sg6000-cn-controller.html["SG6000"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/changing-link-configuration-of-sg5800-controller.html["SG5800"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/changing-link-configuration-of-e5700sg-controller.html["SG5700"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/changing-link-configuration-of-sg110-and-sg1100-appliance.html["SG110 e SG1100"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/changing-link-configuration-of-services-appliance.html["SG100 e SG1000"^]


.. Altere as configurações de FEC nas portas do switch.  As portas do dispositivo StorageGRID ajustarão suas configurações de FEC para corresponder, se possível.
+
Não é possível configurar as definições do FEC em dispositivos StorageGRID .  Em vez disso, os dispositivos tentam descobrir e espelhar as configurações de FEC nas portas do switch às quais estão conectados.  Se os links forem forçados a velocidades de rede de 25 GbE ou 100 GbE, o switch e a NIC podem falhar ao negociar uma configuração FEC comum.  Sem uma configuração FEC comum, a rede retornará ao modo "sem FEC".  Quando o FEC não está habilitado, as conexões ficam mais suscetíveis a erros causados ​​por ruído elétrico.

+

NOTE: Os dispositivos StorageGRID são compatíveis com Firecode (FC) e Reed Solomon (RS) FEC, além de nenhum FEC.



--
.Incompatibilidade de porta do switch e MTU da placa de rede
--
Se o alerta for causado por uma incompatibilidade de MTU entre a porta do switch e a NIC, verifique se o tamanho da MTU configurado no nó é o mesmo que a configuração de MTU para a porta do switch.

O tamanho da MTU configurado no nó pode ser menor que a configuração na porta do switch à qual o nó está conectado.  Se um nó StorageGRID receber um quadro Ethernet maior que sua MTU, o que é possível com essa configuração, o alerta *Erro de quadro de recepção de rede do nó* poderá ser relatado.  Se você acredita que isso é o que está acontecendo, altere a MTU da porta do switch para corresponder à MTU da interface de rede StorageGRID ou altere a MTU da interface de rede StorageGRID para corresponder à porta do switch, dependendo de suas metas ou requisitos de MTU de ponta a ponta.


NOTE: Para obter o melhor desempenho da rede, todos os nós devem ser configurados com valores de MTU semelhantes em suas interfaces de rede de grade.  O alerta *Incompatibilidade de MTU da rede de grade* é acionado se houver uma diferença significativa nas configurações de MTU da rede de grade em nós individuais.  Os valores de MTU não precisam ser os mesmos para todos os tipos de rede. Ver <<troubleshoot_MTU_alert,Solucionar problemas de alerta de incompatibilidade de MTU da rede de grade>> para maiores informações.


NOTE: Veja também https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["Alterar configuração de MTU"^] .

--
.Altas taxas de erro de link
--
.. Habilite o FEC, caso ainda não esteja habilitado.
.. Verifique se o cabeamento da sua rede é de boa qualidade e não está danificado ou conectado incorretamente.
.. Se os cabos não parecerem ser o problema, entre em contato com o suporte técnico.
+

NOTE: Você pode notar altas taxas de erro em um ambiente com alto ruído elétrico.



--
.Estouro do buffer de anel da placa de rede
--
Se o erro for um estouro do buffer de anel da NIC, entre em contato com o suporte técnico.

O buffer de anel pode ser estourado quando o sistema StorageGRID está sobrecarregado e não consegue processar eventos de rede em tempo hábil.

--
====
. Monitore o problema e entre em contato com o suporte técnico se o alerta não for resolvido.




== Erros de sincronização de tempo

Você pode ver problemas com a sincronização de tempo na sua grade.

Se você encontrar problemas de sincronização de tempo, verifique se especificou pelo menos quatro fontes NTP externas, cada uma fornecendo uma referência Stratum 3 ou melhor, e se todas as fontes NTP externas estão operando normalmente e são acessíveis pelos seus nós StorageGRID .


NOTE: Quandolink:../maintain/configuring-ntp-servers.html["especificando a fonte NTP externa"] para uma instalação do StorageGRID em nível de produção, não use o serviço Windows Time (W32Time) em uma versão do Windows anterior ao Windows Server 2016.  O serviço de tempo em versões anteriores do Windows não é suficientemente preciso e não é suportado pela Microsoft para uso em ambientes de alta precisão, como o StorageGRID.



== Linux: Problemas de conectividade de rede

Você pode ver problemas com a conectividade de rede para nós do StorageGRID hospedados em hosts Linux.



=== Clonagem de endereço MAC

Em alguns casos, problemas de rede podem ser resolvidos usando clonagem de endereço MAC. Se você estiver usando hosts virtuais, defina o valor da chave de clonagem de endereço MAC para cada uma das suas redes como "true" no arquivo de configuração do nó. Esta configuração faz com que o endereço MAC do contêiner StorageGRID use o endereço MAC do host. Para criar arquivos de configuração de nó, consulte as instruções paralink:../rhel/creating-node-configuration-files.html["Red Hat Enterprise Linux"] oulink:../ubuntu/creating-node-configuration-files.html["Ubuntu ou Debian"] .


NOTE: Crie interfaces de rede virtuais separadas para uso pelo sistema operacional host Linux.  Usar as mesmas interfaces de rede para o sistema operacional host Linux e o contêiner StorageGRID pode fazer com que o sistema operacional host fique inacessível se o modo promíscuo não estiver habilitado no hipervisor.

Para obter mais informações sobre como habilitar a clonagem de MAC, consulte as instruções paralink:../rhel/configuring-host-network.html["Red Hat Enterprise Linux"] oulink:../ubuntu/configuring-host-network.html["Ubuntu ou Debian"] .



=== Modo promíscuo

Se você não quiser usar a clonagem de endereço MAC e preferir permitir que todas as interfaces recebam e transmitam dados para endereços MAC diferentes daqueles atribuídos pelo hipervisor, certifique-se de que as propriedades de segurança nos níveis de switch virtual e grupo de portas estejam definidas como *Aceitar* para Modo Promíscuo, Alterações de Endereço MAC e Transmissões Falsificadas.  Os valores definidos no switch virtual podem ser substituídos pelos valores no nível do grupo de portas, portanto, certifique-se de que as configurações sejam as mesmas em ambos os locais.

Para obter mais informações sobre o uso do Modo Promíscuo, consulte as instruções paralink:../rhel/configuring-host-network.html["Red Hat Enterprise Linux"] oulink:../ubuntu/configuring-host-network.html["Ubuntu ou Debian"] .



== Linux: o status do nó é "órfão"

Um nó Linux em estado órfão geralmente indica que o serviço storagegrid ou o daemon do nó StorageGRID que controla o contêiner do nó morreu inesperadamente.

.Sobre esta tarefa
Se um nó Linux relatar que está em um estado órfão, você deve:

* Verifique os logs em busca de erros e mensagens.
* Tente iniciar o nó novamente.
* Se necessário, use comandos do mecanismo de contêiner para parar o contêiner do nó existente.
* Reinicie o nó.


.Passos
. Verifique os logs do daemon de serviço e do nó órfão em busca de erros óbvios ou mensagens sobre saída inesperada.
. Efetue login no host como root ou use uma conta com permissão sudo.
. Tente iniciar o nó novamente executando o seguinte comando: `$ sudo storagegrid node start node-name`
+
 $ sudo storagegrid node start DC1-S1-172-16-1-172
+
Se o nó for órfão, a resposta é

+
[listing]
----
Not starting ORPHANED node DC1-S1-172-16-1-172
----
. No Linux, pare o mecanismo de contêiner e quaisquer processos de controle do storagegrid-node. Por exemplo: ``sudo docker stop --time secondscontainer-name``
+
Para `seconds` , insira o número de segundos que você deseja esperar para que o contêiner pare (normalmente 15 minutos ou menos). Por exemplo:

+
[listing]
----
sudo docker stop --time 900 storagegrid-DC1-S1-172-16-1-172
----
. Reinicie o nó: `storagegrid node start node-name`
+
[listing]
----
storagegrid node start DC1-S1-172-16-1-172
----




== Linux: Solucionar problemas de suporte a IPv6

Talvez seja necessário habilitar o suporte a IPv6 no kernel se você tiver instalado nós StorageGRID em hosts Linux e perceber que endereços IPv6 não foram atribuídos aos contêineres de nós conforme o esperado.

.Sobre esta tarefa
Para ver o endereço IPv6 que foi atribuído a um nó de grade:

. Selecione *NÓS* e selecione o nó.
. Selecione *Mostrar endereços IP adicionais* ao lado de *Endereços IP* na guia Visão geral.


Se o endereço IPv6 não for exibido e o nó estiver instalado em um host Linux, siga estas etapas para habilitar o suporte a IPv6 no kernel.

.Passos
. Efetue login no host como root ou use uma conta com permissão sudo.
. Execute o seguinte comando: `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@SG:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
O resultado deve ser 0.

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+

NOTE: Se o resultado não for 0, consulte a documentação do seu sistema operacional para alterar `sysctl` configurações.  Em seguida, altere o valor para 0 antes de continuar.

. Digite o contêiner do nó StorageGRID : `storagegrid node enter node-name`
. Execute o seguinte comando: `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@DC1-S1:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
O resultado deve ser 1.

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 1
----
+

NOTE: Se o resultado não for 1, este procedimento não se aplica. Entre em contato com o suporte técnico.

. Sair do contêiner: `exit`
+
[listing]
----
root@DC1-S1:~ # exit
----
. Como root, edite o seguinte arquivo: `/var/lib/storagegrid/settings/sysctl.d/net.conf` .
+
[listing]
----
sudo vi /var/lib/storagegrid/settings/sysctl.d/net.conf
----
. Localize as duas linhas a seguir e remova as tags de comentário.  Em seguida, salve e feche o arquivo.
+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+
[listing]
----
net.ipv6.conf.default.disable_ipv6 = 0
----
. Execute estes comandos para reiniciar o contêiner StorageGRID :
+
[listing]
----
storagegrid node stop node-name
----
+
[listing]
----
storagegrid node start node-name
----

