---
permalink: ilm/comparing-cloud-storage-pools-to-cloudmirror-replication.html 
sidebar: sidebar 
keywords: cloud storage pools, cloudmirror replication 
summary: Ao começar a usar os Cloud Storage Pools, pode ser útil entender as semelhanças e diferenças entre os Cloud Storage Pools e o serviço de replicação StorageGRID CloudMirror. 
---
= Comparar pools de armazenamento em nuvem e replicação do CloudMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao começar a usar os Cloud Storage Pools, pode ser útil entender as semelhanças e diferenças entre os Cloud Storage Pools e o serviço de replicação StorageGRID CloudMirror.

[cols="1a,3a,3a"]
|===
|  | Pool de armazenamento em nuvem | Serviço de replicação CloudMirror 


 a| 
Qual é o objetivo principal?
 a| 
Atua como um alvo de arquivo.  A cópia do objeto no Cloud Storage Pool pode ser a única cópia do objeto ou pode ser uma cópia adicional.  Ou seja, em vez de manter duas cópias no local, você pode manter uma cópia no StorageGRID e enviar uma cópia para o Cloud Storage Pool.
 a| 
Permite que um locatário replique automaticamente objetos de um bucket no StorageGRID (origem) para um bucket S3 externo (destino).  Cria uma cópia independente de um objeto em uma infraestrutura S3 independente.



 a| 
Como é configurado?
 a| 
Definido da mesma forma que os pools de armazenamento, usando o Grid Manager ou a Grid Management API.  Pode ser selecionado como o local de posicionamento em uma regra ILM.  Enquanto um pool de armazenamento consiste em um grupo de nós de armazenamento, um pool de armazenamento em nuvem é definido usando um ponto de extremidade remoto do S3 ou do Azure (endereço IP, credenciais e assim por diante).
 a| 
Um usuário locatáriolink:../tenant/configuring-cloudmirror-replication.html["configura a replicação do CloudMirror"] definindo um ponto de extremidade do CloudMirror (endereço IP, credenciais e assim por diante) usando o Tenant Manager ou a API do S3.  Após a configuração do ponto de extremidade do CloudMirror, qualquer bucket pertencente a essa conta de locatário pode ser configurado para apontar para o ponto de extremidade do CloudMirror.



 a| 
Quem é responsável por configurá-lo?
 a| 
Normalmente, um administrador de rede
 a| 
Normalmente, um usuário locatário



 a| 
Qual é o destino?
 a| 
* Qualquer infraestrutura S3 compatível (incluindo Amazon S3)
* Camada de arquivo de Blobs do Azure
* Plataforma de nuvem do Google (GCP)

 a| 
* Qualquer infraestrutura S3 compatível (incluindo Amazon S3)
* Plataforma de nuvem do Google (GCP)




 a| 
O que faz com que os objetos sejam movidos para o destino?
 a| 
Uma ou mais regras de ILM nas políticas de ILM ativas.  As regras do ILM definem quais objetos o StorageGRID move para o Cloud Storage Pool e quando os objetos são movidos.
 a| 
O ato de ingerir um novo objeto em um bucket de origem que foi configurado com um endpoint do CloudMirror.  Objetos que existiam no bucket de origem antes do bucket ser configurado com o endpoint do CloudMirror não são replicados, a menos que sejam modificados.



 a| 
Como os objetos são recuperados?
 a| 
Os aplicativos devem fazer solicitações ao StorageGRID para recuperar objetos que foram movidos para um pool de armazenamento em nuvem.  Se a única cópia de um objeto tiver sido transferida para armazenamento de arquivo, o StorageGRID gerencia o processo de restauração do objeto para que ele possa ser recuperado.
 a| 
Como a cópia espelhada no bucket de destino é uma cópia independente, os aplicativos podem recuperar o objeto fazendo solicitações ao StorageGRID ou ao destino S3.  Por exemplo, suponha que você use a replicação do CloudMirror para espelhar objetos para uma organização parceira.  O parceiro pode usar seus próprios aplicativos para ler ou atualizar objetos diretamente do destino S3.  Não é necessário usar o StorageGRID .



 a| 
Você pode ler diretamente do destino?
 a| 
Não. Os objetos movidos para um pool de armazenamento em nuvem são gerenciados pelo StorageGRID.  As solicitações de leitura devem ser direcionadas ao StorageGRID (e o StorageGRID será responsável pela recuperação do Cloud Storage Pool).
 a| 
Sim, porque a cópia espelhada é uma cópia independente.



 a| 
O que acontece se um objeto for excluído da fonte?
 a| 
O objeto também é excluído do Cloud Storage Pool.
 a| 
A ação de exclusão não é replicada.  Um objeto excluído não existe mais no bucket StorageGRID , mas continua existindo no bucket de destino.  Da mesma forma, objetos no bucket de destino podem ser excluídos sem afetar a origem.



 a| 
Como acessar objetos após um desastre (sistema StorageGRID não operacional)?
 a| 
Nós StorageGRID com falha devem ser recuperados.  Durante esse processo, cópias de objetos replicados podem ser restauradas usando as cópias no Cloud Storage Pool.
 a| 
As cópias de objetos no destino do CloudMirror são independentes do StorageGRID, portanto, podem ser acessadas diretamente antes que os nós do StorageGRID sejam recuperados.

|===