---
permalink: ilm/create-ilm-rule-select-ingest-behavior.html 
sidebar: sidebar 
keywords: ilm rule step 3, define ingest behavior 
summary: 'A etapa 3 \(Selecionar comportamento de ingestão\) do assistente Criar regra ILM permite que você escolha como os objetos filtrados por esta regra serão protegidos à medida que são ingeridos.' 
---
= Etapa 3 de 3: Selecione o comportamento de ingestão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A etapa *Selecionar comportamento de ingestão* do assistente Criar regra ILM permite que você escolha como os objetos filtrados por esta regra serão protegidos à medida que são ingeridos.

.Sobre esta tarefa
O StorageGRID pode fazer cópias provisórias e enfileirar os objetos para avaliação posterior do ILM, ou pode fazer cópias para atender às instruções de posicionamento da regra imediatamente.

.Passos
. Selecione olink:data-protection-options-for-ingest.html["comportamento de ingestão"] para usar.
+
Para obter mais informações, consulte link:advantages-disadvantages-of-ingest-options.html["Vantagens, desvantagens e limitações das opções de ingestão"] .

+
[NOTE]
====
Você não pode usar a opção Balanceado ou Estrito se a regra usar um destes posicionamentos:

** Um pool de armazenamento em nuvem no dia 0
** Um pool de armazenamento em nuvem quando a regra usa um horário de criação definido pelo usuário como horário de referência


Ver link:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.html["Exemplo 5: regras e política do ILM para comportamento de ingestão estrita"] .

====
. Selecione *Criar*.
+
A regra ILM é criada.  A regra não se torna ativa até que seja adicionada a umlink:creating-ilm-policy.html["Política de ILM"] e essa política é ativada.

+
Para visualizar os detalhes da regra, selecione o nome da regra na página de regras do ILM.


