---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: Configure e use pools de armazenamento para proteger contra perda de dados distribuindo dados entre vários sites.  Cópias replicadas e cópias codificadas para eliminação exigem configurações de pool de armazenamento diferentes. 
---
= Diretrizes para criação de pools de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configure e use pools de armazenamento para proteger contra perda de dados distribuindo dados entre vários sites.  Cópias replicadas e cópias codificadas para eliminação exigem configurações de pool de armazenamento diferentes.

Ver link:using-multiple-storage-pools-for-cross-site-replication.html["Exemplos de ativação da proteção contra perda de site usando replicação e codificação de eliminação"] .



== Diretrizes para todos os pools de armazenamento

* Mantenha as configurações do pool de armazenamento o mais simples possível.  Não crie mais pools de armazenamento do que o necessário.
* Crie pools de armazenamento com o maior número possível de nós.  Cada pool de armazenamento deve conter dois ou mais nós.  Um pool de armazenamento com nós insuficientes pode causar atrasos no ILM se um nó ficar indisponível.
* Evite criar ou usar pools de armazenamento que se sobreponham (contenham um ou mais nós iguais).  Se os pools de armazenamento se sobrepuserem, mais de uma cópia dos dados do objeto poderá ser salva no mesmo nó.
* Em geral, não use o pool de armazenamento All Storage Nodes (StorageGRID 11.6 e anteriores) ou o site All Sites.  Esses itens são atualizados automaticamente para incluir quaisquer novos sites que você adicionar em uma expansão, o que pode não ser o comportamento desejado.




== Diretrizes para pools de armazenamento usados para cópias replicadas

* Para proteção contra perda de site usandolink:what-replication-is.html["replicação"] , especifique um ou mais pools de armazenamento específicos do site nolink:create-ilm-rule-define-placements.html["instruções de posicionamento para cada regra ILM"] .
+
Um pool de armazenamento é criado automaticamente para cada site durante a instalação do StorageGRID .

+
Usar um pool de armazenamento para cada site garante que cópias de objetos replicadas sejam colocadas exatamente onde você espera (por exemplo, uma cópia de cada objeto em cada site para proteção contra perda de site).

* Se você adicionar um site em uma expansão, crie um novo pool de armazenamento que contenha somente o novo site.  Então,link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["atualizar regras do ILM"] para controlar quais objetos são armazenados no novo site.
* Se o número de cópias for menor que o número de pools de armazenamento, o sistema distribuirá as cópias para equilibrar o uso do disco entre os pools.
* Se os pools de armazenamento se sobrepuserem (contiverem os mesmos nós de armazenamento), todas as cópias do objeto poderão ser salvas em apenas um site.  Você deve garantir que os pools de armazenamento selecionados não contenham os mesmos nós de armazenamento.




== Diretrizes para pools de armazenamento usados para cópias codificadas por eliminação

* Para proteção contra perda de site usandolink:what-erasure-coding-is.html["codificação de apagamento"] , crie pools de armazenamento que consistam em pelo menos três sites.  Se um pool de armazenamento incluir apenas dois sites, você não poderá usá-lo para codificação de eliminação.  Não há esquemas de codificação de eliminação disponíveis para um pool de armazenamento com dois sites.
* O número de nós de armazenamento e sites contidos no pool de armazenamento determinam quaislink:what-erasure-coding-schemes-are.html["esquemas de codificação de apagamento"] estão disponíveis.
* Se possível, um pool de armazenamento deve incluir mais do que o número mínimo de nós de armazenamento necessários para o esquema de codificação de eliminação selecionado.  Por exemplo, se você usar um esquema de codificação de eliminação 6+3, deverá ter pelo menos nove nós de armazenamento.  No entanto, é recomendável ter pelo menos um nó de armazenamento adicional por site.
* Distribua os nós de armazenamento entre os sites da maneira mais uniforme possível.  Por exemplo, para dar suporte a um esquema de codificação de eliminação 6+3, configure um pool de armazenamento que inclua pelo menos três nós de armazenamento em três sites.
* Se você tiver requisitos de alta taxa de transferência, não é recomendável usar um pool de armazenamento que inclua vários sites se a latência da rede entre os sites for maior que 100 ms.  À medida que a latência aumenta, a taxa na qual o StorageGRID pode criar, posicionar e recuperar fragmentos de objetos diminui drasticamente devido à diminuição na taxa de transferência da rede TCP.
+
A redução na taxa de transferência afeta as taxas máximas alcançáveis de ingestão e recuperação de objetos (quando Balanceado ou Estrito são selecionados como comportamento de ingestão) ou pode levar a pendências na fila do ILM (quando Confirmação dupla é selecionado como comportamento de ingestão). Ver link:what-ilm-rule-is.html#ilm-rule-ingest-behavior["Comportamento de ingestão de regras do ILM"] .

+

NOTE: Se sua grade incluir apenas um site, você não poderá usar o pool de armazenamento Todos os nós de armazenamento (StorageGRID 11.6 e anteriores) ou o site Todos os sites em um perfil de codificação de eliminação.  Esse comportamento evita que o perfil se torne inválido se um segundo site for adicionado.


