---
permalink: ilm/how-object-retention-is-determined.html 
sidebar: sidebar 
keywords: how object retention is determined 
summary: O StorageGRID fornece opções para administradores de grade e usuários individuais de locatários para especificar por quanto tempo os objetos serão armazenados.  Em geral, quaisquer instruções de retenção fornecidas por um usuário locatário têm precedência sobre as instruções de retenção fornecidas pelo administrador da grade. 
---
= Como a retenção de objetos é determinada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID fornece opções para administradores de grade e usuários individuais de locatários para especificar por quanto tempo os objetos serão armazenados.  Em geral, quaisquer instruções de retenção fornecidas por um usuário locatário têm precedência sobre as instruções de retenção fornecidas pelo administrador da grade.



== Como os usuários locatários controlam a retenção de objetos

Os usuários locatários podem usar estes métodos para controlar por quanto tempo seus objetos são armazenados no StorageGRID:

* Se a configuração global do Bloqueio de Objeto S3 estiver habilitada para a grade, os usuários do locatário S3 poderão criar buckets com o Bloqueio de Objeto S3 habilitado e, em seguida, selecionar um *Período de retenção padrão* para cada bucket.
* Se a configuração global de Bloqueio de Objeto do S3 estiver habilitada para a grade, os usuários do locatário do S3 poderão criar buckets com o Bloqueio de Objeto do S3 habilitado e, em seguida, usar a API REST do S3 para especificar as configurações de retenção até a data e retenção legal para cada versão de objeto adicionada a esse bucket.
+
** Uma versão de objeto que está sob retenção legal não pode ser excluída por nenhum método.
** Antes que a data de retenção de uma versão do objeto seja atingida, essa versão não pode ser excluída por nenhum método.
** Objetos em buckets com o S3 Object Lock habilitado são retidos pelo ILM "para sempre".  No entanto, após atingir a data de retenção, uma versão do objeto pode ser excluída por uma solicitação do cliente ou pela expiração do ciclo de vida do bucket. Ver link:managing-objects-with-s3-object-lock.html["Gerenciar objetos com o S3 Object Lock"] .


* Os usuários do locatário do S3 podem adicionar uma configuração de ciclo de vida aos seus buckets que especifica uma ação de expiração.  Se houver um ciclo de vida de bucket, o StorageGRID armazenará um objeto até que a data ou o número de dias especificado na ação Expiração sejam atingidos, a menos que o cliente exclua o objeto primeiro. Ver link:../s3/create-s3-lifecycle-configuration.html["Criar configuração do ciclo de vida do S3"] .
* Um cliente S3 pode emitir uma solicitação de exclusão de objeto.  O StorageGRID sempre prioriza as solicitações de exclusão do cliente em relação ao ciclo de vida do bucket S3 ou ILM ao determinar se um objeto deve ser excluído ou mantido.




== Como os administradores de grade controlam a retenção de objetos

Os administradores de grade podem usar estes métodos para controlar a retenção de objetos:

* Defina um período máximo de retenção do bloqueio de objeto S3 para cada locatário.  Em seguida, os usuários locatários podem definir um período de retenção padrão para cada um de seus buckets.  O período máximo de retenção também é aplicado a quaisquer objetos recém-ingeridos para esse bucket (data de retenção do objeto).
* Crie instruções de posicionamento do ILM para controlar por quanto tempo os objetos são armazenados.  Quando objetos são correspondidos por uma regra ILM, o StorageGRID armazena esses objetos até que o último período de tempo na regra ILM tenha decorrido.  Os objetos são retidos indefinidamente se "para sempre" for especificado nas instruções de posicionamento.
* Independentemente de quem controla por quanto tempo os objetos são retidos, as configurações do ILM controlam quais tipos de cópias de objetos (replicadas ou codificadas para eliminação) são armazenadas e onde as cópias estão localizadas (nós de armazenamento ou pools de armazenamento em nuvem).




== Como o ciclo de vida do bucket S3 e o ILM interagem

Quando um ciclo de vida de bucket do S3 é configurado, as ações de expiração do ciclo de vida substituem a política do ILM para objetos que correspondem ao filtro do ciclo de vida.  Como resultado, um objeto pode ser retido na grade mesmo depois que quaisquer instruções do ILM para posicioná-lo tenham expirado.



== Exemplos de retenção de objetos

Para entender melhor as interações entre o bloqueio de objeto do S3, as configurações do ciclo de vida do bucket, as solicitações de exclusão do cliente e o ILM, considere os exemplos a seguir.



=== Exemplo 1: o ciclo de vida do bucket S3 mantém os objetos por mais tempo que o ILM

ILM:: Armazene duas cópias por 1 ano (365 dias)
Ciclo de vida do bucket:: Expira objetos em 2 anos (730 dias)
Resultado:: O StorageGRID armazena o objeto por 730 dias.  O StorageGRID usa as configurações do ciclo de vida do bucket para determinar se um objeto deve ser excluído ou mantido.



NOTE: Se o ciclo de vida do bucket especificar que os objetos devem ser mantidos por mais tempo do que o especificado pelo ILM, o StorageGRID continuará a usar as instruções de posicionamento do ILM ao determinar o número e o tipo de cópias a serem armazenadas.  Neste exemplo, duas cópias do objeto continuarão armazenadas no StorageGRID dos dias 366 a 730.



=== Exemplo 2: o ciclo de vida do bucket S3 expira objetos antes do ILM

ILM:: Armazene duas cópias por 2 anos (730 dias)
Ciclo de vida do bucket:: Expirar objetos em 1 ano (365 dias)
Resultado:: O StorageGRID exclui ambas as cópias do objeto após o dia 365.




=== Exemplo 3: A exclusão do cliente substitui o ciclo de vida do bucket e o ILM

ILM:: Armazene duas cópias nos nós de armazenamento "para sempre"
Ciclo de vida do bucket:: Expira objetos em 2 anos (730 dias)
Solicitação de exclusão de cliente:: Emitido no dia 400
Resultado:: O StorageGRID exclui ambas as cópias do objeto no dia 400 em resposta à solicitação de exclusão do cliente.




=== Exemplo 4: O bloqueio de objeto S3 substitui a solicitação de exclusão do cliente

Bloqueio de Objeto S3:: A data de retenção para uma versão de objeto é 31/03/2026.  Uma retenção legal não está em vigor.
Regra ILM compatível:: Armazene duas cópias nos nós de armazenamento "para sempre"
Solicitação de exclusão de cliente:: Emitido em 31/03/2024
Resultado:: O StorageGRID não excluirá a versão do objeto porque a data de retenção ainda está a 2 anos de distância.

