---
permalink: ilm/resolving-consistency-errors-when-updating-bucket-s3-object-lock-configuration.html 
sidebar: sidebar 
keywords: consistency error, s3 object lock and consistency 
summary: Se um site de data center ou vários nós de armazenamento em um site ficarem indisponíveis, talvez seja necessário ajudar os usuários do locatário do S3 a aplicar alterações no bloqueio de objeto do S3 ou na configuração de conformidade herdada. 
---
= Resolver erros de consistência ao atualizar o bloqueio de objeto S3 ou a configuração de conformidade herdada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se um site de data center ou vários nós de armazenamento em um site ficarem indisponíveis, talvez seja necessário ajudar os usuários do locatário do S3 a aplicar alterações no bloqueio de objeto do S3 ou na configuração de conformidade herdada.

Usuários locatários que têm buckets com o Bloqueio de Objeto S3 (ou Conformidade herdada) habilitado podem alterar determinadas configurações.  Por exemplo, um usuário locatário que utiliza o S3 Object Lock pode precisar colocar uma versão do objeto em retenção legal.

Quando um usuário locatário atualiza as configurações de um bucket do S3 ou uma versão de objeto, o StorageGRID tenta atualizar imediatamente os metadados do bucket ou do objeto na grade.  Se o sistema não conseguir atualizar os metadados porque um site de data center ou vários nós de armazenamento não estão disponíveis, ele retornará um erro:

[listing]
----
503: Service Unavailable
Unable to update compliance settings because the settings can't be consistently applied on enough storage services. Contact your grid administrator for assistance.
----
Para resolver esse erro, siga estas etapas:

. Tente tornar todos os nós de armazenamento ou sites disponíveis novamente o mais rápido possível.
. Se você não conseguir disponibilizar nós de armazenamento suficientes em cada site, entre em contato com o suporte técnico, que pode ajudar você a recuperar nós e garantir que as alterações sejam aplicadas de forma consistente em toda a grade.
. Depois que o problema subjacente for resolvido, lembre o usuário locatário de tentar novamente as alterações de configuração.


.Informações relacionadas
* link:../tenant/index.html["Use uma conta de inquilino"]
* link:../s3/index.html["Usar API REST do S3"]
* link:../maintain/index.html["Recuperar e manter"]

