---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: Use estas etapas de solução de problemas para ajudar a resolver erros que você pode encontrar ao criar, editar ou excluir um pool de armazenamento em nuvem. 
---
= Solucionar problemas de pools de armazenamento em nuvem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use estas etapas de solução de problemas para ajudar a resolver erros que você pode encontrar ao criar, editar ou excluir um pool de armazenamento em nuvem.



== Determinar se ocorreu um erro

O StorageGRID executa uma verificação de integridade simples em cada pool de armazenamento em nuvem lendo o objeto conhecido `x-ntap-sgws-cloud-pool-uuid` para garantir que o Cloud Storage Pool possa ser acessado e esteja funcionando corretamente.  Quando o StorageGRID encontra um erro no endpoint, ele executa uma verificação de integridade a cada minuto em cada nó de armazenamento.  Quando o erro for resolvido, as verificações de integridade serão interrompidas.  Se uma verificação de integridade detectar um problema, uma mensagem será exibida na coluna Último erro da tabela Pools de armazenamento em nuvem na página Pools de armazenamento.

A tabela mostra o erro mais recente detectado para cada pool de armazenamento em nuvem e indica há quanto tempo o erro ocorreu.

Além disso, um alerta de *erro de conectividade do Cloud Storage Pool* será acionado se a verificação de integridade detectar que um ou mais novos erros do Cloud Storage Pool ocorreram nos últimos 5 minutos.  Se você receber uma notificação por e-mail para este alerta, acesse a página Pools de armazenamento (selecione *ILM* > *Pools de armazenamento*), revise as mensagens de erro na coluna Último erro e consulte as diretrizes de solução de problemas abaixo.



== Verifique se um erro foi resolvido

Depois de resolver quaisquer problemas subjacentes, você pode determinar se o erro foi resolvido.  Na página Pool de armazenamento em nuvem, selecione o ponto de extremidade e selecione *Limpar erro*.  Uma mensagem de confirmação indica que o StorageGRID corrigiu o erro do Cloud Storage Pool.

Se o problema subjacente tiver sido resolvido, a mensagem de erro não será mais exibida.  Entretanto, se o problema subjacente não tiver sido corrigido (ou se um erro diferente for encontrado), a mensagem de erro será exibida na coluna Último erro dentro de alguns minutos.



== Erro: Falha na verificação de integridade.  Erro do ponto final

Você pode encontrar esse erro ao habilitar o S3 Object Lock com retenção padrão para seu bucket do Amazon S3 depois de começar a usar esse bucket para um Cloud Storage Pool.  Este erro ocorre quando a operação PUT não tem um cabeçalho HTTP com um valor de soma de verificação de carga útil, como `Content-MD5` .  Este valor de cabeçalho é exigido pela AWS para operações PUT em buckets com o S3 Object Lock habilitado.

Para corrigir esse problema, siga as etapas emlink:editing-cloud-storage-pool.html["Editar um pool de armazenamento em nuvem"] sem fazer nenhuma alteração.  Esta ação aciona a validação da configuração do Cloud Storage Pool que detecta e atualiza automaticamente o sinalizador de bloqueio de objeto do S3 em uma configuração de ponto de extremidade do Cloud Storage Pool.



== Erro: Este pool de armazenamento em nuvem contém conteúdo inesperado

Você pode encontrar esse erro ao tentar criar, editar ou excluir um pool de armazenamento em nuvem.  Este erro ocorre se o bucket ou contêiner incluir o `x-ntap-sgws-cloud-pool-uuid` arquivo marcador, mas esse arquivo não tem o campo de metadados com o UUID esperado.

Normalmente, você só verá esse erro se estiver criando um novo Cloud Storage Pool e outra instância do StorageGRID já estiver usando o mesmo Cloud Storage Pool.

Tente uma destas etapas para corrigir o problema:

* Se você estiver configurando um novo pool de armazenamento em nuvem e o bucket contiver o `x-ntap-sgws-cloud-pool-uuid` arquivo e chaves de objeto adicionais semelhantes ao exemplo a seguir, crie um novo bucket e use esse novo bucket.
+
Exemplo de uma chave de objeto adicional: `my-bucket.3E64CF2C-B74D-4B7D-AFE7-AD28BC18B2F6.1727326606730410`

* Se o `x-ntap-sgws-cloud-pool-uuid` o arquivo é o único objeto no bucket, exclua este arquivo.


Se essas etapas não se aplicarem ao seu cenário, entre em contato com o suporte.



== Erro: Não foi possível criar ou atualizar o Cloud Storage Pool.  Erro do ponto final

Você pode encontrar esse erro nas seguintes circunstâncias:

* Quando você tenta criar ou editar um pool de armazenamento em nuvem.
* Quando você seleciona uma plataforma, autenticação ou combinação de protocolo não suportada com o S3 Object Lock durante a configuração de um novo Cloud Storage Pool. Ver link:../ilm/considerations-for-cloud-storage-pools.html["Considerações sobre pools de armazenamento em nuvem"] .


Este erro indica que um problema de conectividade ou configuração está impedindo o StorageGRID de gravar no Cloud Storage Pool.

Para corrigir o problema, revise a mensagem de erro do endpoint.

* Se a mensagem de erro contiver `Get _url_: EOF` , verifique se o ponto de extremidade de serviço usado para o Cloud Storage Pool não usa HTTP para um contêiner ou bucket que requer HTTPS.
* Se a mensagem de erro contiver `Get _url_: net/http: request canceled while waiting for connection` , verifique se a configuração de rede permite que os nós de armazenamento acessem o ponto de extremidade de serviço usado para o pool de armazenamento em nuvem.
* Se o erro for devido a uma plataforma, autenticação ou protocolo não suportado, altere para uma configuração suportada com o S3 Object Lock e tente salvar o novo Cloud Storage Pool novamente.
* Para todas as outras mensagens de erro de endpoint, tente uma ou mais das seguintes opções:
+
** Crie um contêiner ou bucket externo com o mesmo nome que você inseriu para o Cloud Storage Pool e tente salvar o novo Cloud Storage Pool novamente.
** Corrija o nome do contêiner ou bucket especificado para o Cloud Storage Pool e tente salvar o novo Cloud Storage Pool novamente.






== Erro: Falha ao analisar o certificado CA

Você pode encontrar esse erro ao tentar criar ou editar um pool de armazenamento em nuvem.  O erro ocorre se o StorageGRID não puder analisar o certificado inserido ao configurar o Cloud Storage Pool.

Para corrigir o problema, verifique se há problemas no certificado da CA fornecido.



== Erro: Um pool de armazenamento em nuvem com este ID não foi encontrado

Você pode encontrar esse erro ao tentar editar ou excluir um pool de armazenamento em nuvem.  Esse erro ocorre se o endpoint retornar uma resposta 404, o que pode significar qualquer um dos seguintes:

* As credenciais usadas para o Cloud Storage Pool não têm permissão de leitura para o bucket.
* O bucket usado para o Cloud Storage Pool não inclui o `x-ntap-sgws-cloud-pool-uuid` arquivo marcador.


Tente uma ou mais destas etapas para corrigir o problema:

* Verifique se o usuário associado à Chave de Acesso configurada tem as permissões necessárias.
* Edite o Cloud Storage Pool com credenciais que tenham as permissões necessárias.
* Se as permissões estiverem corretas, entre em contato com o suporte.




== Erro: Não foi possível verificar o conteúdo do pool de armazenamento em nuvem.  Erro do ponto final

Você pode encontrar esse erro ao tentar excluir um pool de armazenamento em nuvem.  Este erro indica que algum tipo de problema de conectividade ou configuração está impedindo o StorageGRID de ler o conteúdo do bucket do Cloud Storage Pool.

Para corrigir o problema, revise a mensagem de erro do endpoint.



== Erro: Objetos já foram colocados neste bucket

Você pode encontrar esse erro ao tentar excluir um pool de armazenamento em nuvem.  Não é possível excluir um pool de armazenamento em nuvem se ele contiver dados que foram movidos para lá pelo ILM, dados que estavam no bucket antes de você configurar o pool de armazenamento em nuvem ou dados que foram colocados no bucket por alguma outra fonte depois que o pool de armazenamento em nuvem foi criado.

Tente uma ou mais destas etapas para corrigir o problema:

* Siga as instruções para mover objetos de volta para o StorageGRID em "Ciclo de vida de um objeto de pool de armazenamento em nuvem".
* Se você tiver certeza de que os objetos restantes não foram colocados no Cloud Storage Pool pelo ILM, exclua manualmente os objetos do bucket.
+

NOTE: Nunca exclua manualmente objetos de um pool de armazenamento em nuvem que possam ter sido colocados lá pelo ILM.  Se você tentar acessar posteriormente um objeto excluído manualmente do StorageGRID, o objeto excluído não será encontrado.





== Erro: O proxy encontrou um erro externo ao tentar acessar o Cloud Storage Pool

Você pode encontrar esse erro se tiver configurado um proxy de armazenamento não transparente entre os nós de armazenamento e o ponto de extremidade S3 externo usado para o pool de armazenamento em nuvem.  Este erro ocorre se o servidor proxy externo não conseguir acessar o ponto de extremidade do Cloud Storage Pool.  Por exemplo, o servidor DNS pode não conseguir resolver o nome do host ou pode haver um problema de rede externa.

Tente uma ou mais destas etapas para corrigir o problema:

* Verifique as configurações do Cloud Storage Pool (*ILM* > *Storage pools*).
* Verifique a configuração de rede do servidor proxy de armazenamento.




== Erro: O certificado X.509 está fora do período de validade

Você pode encontrar esse erro ao tentar excluir um pool de armazenamento em nuvem.  Este erro ocorre quando a autenticação requer um certificado X.509 para garantir que o pool de armazenamento em nuvem externo correto seja validado e que o pool externo esteja vazio antes que a configuração do pool de armazenamento em nuvem seja excluída.

Tente estas etapas para corrigir o problema:

* Atualize o certificado configurado para autenticação no Cloud Storage Pool.
* Certifique-se de que qualquer alerta de expiração de certificado neste pool de armazenamento em nuvem seja resolvido.


.Informações relacionadas
link:lifecycle-of-cloud-storage-pool-object.html["Ciclo de vida de um objeto de pool de armazenamento em nuvem"]
