---
permalink: ilm/when-to-use-cloud-storage-pools.html 
sidebar: sidebar 
keywords: use cloud storage pool, benefits of cloud storage pools 
summary: Usando pools de armazenamento em nuvem, você pode fazer backup ou hierarquizar dados em um local externo.  Além disso, você pode fazer backup ou hierarquizar dados em mais de uma nuvem. 
---
= Quando usar pools de armazenamento em nuvem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Usando pools de armazenamento em nuvem, você pode fazer backup ou hierarquizar dados em um local externo.  Além disso, você pode fazer backup ou hierarquizar dados em mais de uma nuvem.



== Faça backup dos dados do StorageGRID em um local externo

Você pode usar um Cloud Storage Pool para fazer backup de objetos do StorageGRID em um local externo.

Se as cópias no StorageGRID estiverem inacessíveis, os dados do objeto no Cloud Storage Pool poderão ser usados ​​para atender às solicitações do cliente.  No entanto, talvez seja necessário emitir uma solicitação S3 RestoreObject para acessar a cópia do objeto de backup no Cloud Storage Pool.

Os dados do objeto em um Cloud Storage Pool também podem ser usados ​​para recuperar dados perdidos do StorageGRID devido a uma falha no volume de armazenamento ou no nó de armazenamento.  Se a única cópia restante de um objeto estiver em um pool de armazenamento em nuvem, o StorageGRID restaurará temporariamente o objeto e criará uma nova cópia no nó de armazenamento recuperado.

Para implementar uma solução de backup:

. Crie um único pool de armazenamento em nuvem.
. Configure uma regra de ILM que armazene simultaneamente cópias de objetos em nós de armazenamento (como cópias replicadas ou codificadas para eliminação) e uma única cópia de objeto no pool de armazenamento em nuvem.
. Adicione a regra à sua política de ILM.  Em seguida, simule e ative a política.




== Dados em camadas do StorageGRID para local externo

Você pode usar um Cloud Storage Pool para armazenar objetos fora do sistema StorageGRID .  Por exemplo, suponha que você tenha um grande número de objetos que precisa manter, mas espera acessá-los raramente, ou nunca.  Você pode usar um pool de armazenamento em nuvem para hierarquizar os objetos em armazenamentos de menor custo e liberar espaço no StorageGRID.

Para implementar uma solução em camadas:

. Crie um único pool de armazenamento em nuvem.
. Configure uma regra de ILM que mova objetos raramente usados dos nós de armazenamento para o pool de armazenamento em nuvem.
. Adicione a regra à sua política de ILM.  Em seguida, simule e ative a política.




== Manter vários endpoints de nuvem

Você pode configurar vários pontos de extremidade do Cloud Storage Pool se quiser hierarquizar ou fazer backup de dados de objetos em mais de uma nuvem.  Os filtros nas suas regras do ILM permitem que você especifique quais objetos são armazenados em cada pool do Cloud Storage.  Por exemplo, você pode querer armazenar objetos de alguns locatários ou buckets no Amazon S3 Glacier e objetos de outros locatários ou buckets no armazenamento de Blobs do Azure.  Ou você pode querer mover dados entre o Amazon S3 Glacier e o armazenamento de Blobs do Azure.


NOTE: Ao usar vários pontos de extremidade do Cloud Storage Pool, lembre-se de que um objeto pode ser armazenado em apenas um Cloud Storage Pool por vez.

Para implementar vários endpoints de nuvem:

. Crie até 10 pools de armazenamento em nuvem.
. Configure regras de ILM para armazenar os dados de objeto apropriados no momento apropriado em cada pool de armazenamento em nuvem.  Por exemplo, armazene objetos do bucket A no Cloud Storage Pool A e armazene objetos do bucket B no Cloud Storage Pool B. Ou armazene objetos no Cloud Storage Pool A por um determinado período e depois mova-os para o Cloud Storage Pool B.
. Adicione as regras à sua política de ILM.  Em seguida, simule e ative a política.

