---
permalink: fabricpool/configure-ontap.html 
sidebar: sidebar 
keywords: fabricPool, system manager, ONTAP CLI, add cloud tier 
summary: Depois de obter as informações necessárias do StorageGRID , você pode acessar o ONTAP para adicionar o StorageGRID como uma camada de nuvem. 
---
= Configurar o ONTAP System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de obter as informações necessárias do StorageGRID , você pode acessar o ONTAP para adicionar o StorageGRID como uma camada de nuvem.

.Antes de começar
* Se você concluiu o assistente de configuração do FabricPool , você tem o `ONTAP_FabricPool_settings___bucketname__.txt` arquivo que você baixou.
* Se você configurou o StorageGRID manualmente, terá o nome de domínio totalmente qualificado (FQDN) que está usando para o StorageGRID ou o endereço IP virtual (VIP) para o grupo HA do StorageGRID , o número da porta para o ponto de extremidade do balanceador de carga, o certificado do balanceador de carga, o ID da chave de acesso e a chave secreta para o usuário raiz da conta do locatário e o nome do bucket que o ONTAP usará nesse locatário.




== Gerenciador de Sistema Access ONTAP

Estas instruções descrevem como usar o ONTAP System Manager para adicionar o StorageGRID como uma camada de nuvem.  Você pode concluir a mesma configuração usando o ONTAP CLI.  Para obter instruções, acesse https://docs.netapp.com/us-en/ontap/fabricpool/index.html["Documentação ONTAP para FabricPool"^] .

.Passos
. Acesse o System Manager para o cluster ONTAP que você deseja hierarquizar no StorageGRID.
. Sign in como administrador do cluster.
. Navegue até *ARMAZENAMENTO* > *Níveis* > *Adicionar nível de nuvem*.
. Selecione * StorageGRID* na lista de provedores de armazenamento de objetos.




== Insira os valores do StorageGRID

Ver https://docs.netapp.com/us-en/ontap/fabricpool/index.html["Documentação ONTAP para FabricPool"^] para maiores informações.

.Passos
. Preencha o formulário Adicionar nível de nuvem usando o `ONTAP_FabricPool_settings___bucketname__.txt` arquivo ou os valores que você obteve manualmente.
+
[cols="1a,3a"]
|===
| Campo | Descrição 


 a| 
Nome
 a| 
Insira um nome exclusivo para esta camada de nuvem.  Você pode aceitar o valor padrão.



 a| 
Estilo de URL
 a| 
Se vocêlink:../admin/configuring-s3-api-endpoint-domain-names.html["nomes de domínio de endpoint S3 configurados"] , selecione *URL de estilo de hospedagem virtual*.

*URL no estilo de caminho* é o padrão para ONTAP, mas usar solicitações no estilo de hospedagem virtual é recomendado para StorageGRID.  Você deve usar *URL no estilo de caminho* se fornecer um endereço IP em vez de um nome de domínio para o campo *Nome do servidor (FQDN)*.



 a| 
Nome do servidor (FQDN)
 a| 
Insira o nome de domínio totalmente qualificado (FQDN) que você está usando para o StorageGRID ou o endereço IP virtual (VIP) para o grupo StorageGRID HA. Por exemplo,  `s3.storagegrid.__company__.com` .

Observe o seguinte:

** O endereço IP ou nome de domínio que você especificar aqui deve corresponder ao certificado que você carregou ou gerou para o ponto de extremidade do balanceador de carga StorageGRID .
** Se você fornecer um nome de domínio, o registro DNS deverá mapear cada endereço IP que você usará para se conectar ao StorageGRID. Ver link:configure-dns-server.html["Configurar o servidor DNS"] .




 a| 
SSL
 a| 
Ativado (padrão).



 a| 
Certificado de armazenamento de objetos
 a| 
Cole o certificado PEM que você está usando para o ponto de extremidade do balanceador de carga StorageGRID , incluindo:
`-----BEGIN CERTIFICATE-----` e `-----END CERTIFICATE-----` .

*Observação:* Se uma CA intermediária emitiu o certificado StorageGRID , você deve fornecer o certificado da CA intermediária.  Se o certificado StorageGRID foi emitido diretamente pela CA raiz, você deve fornecer o certificado da CA raiz.



 a| 
Porta
 a| 
Insira a porta usada pelo ponto de extremidade do balanceador de carga StorageGRID .  O ONTAP usará esta porta quando se conectar ao StorageGRID. Por exemplo, 10433.



 a| 
Chave de acesso e chave secreta
 a| 
Insira o ID da chave de acesso e a chave de acesso secreta para o usuário raiz da conta de locatário do StorageGRID .

*Dica*: Se você gerar uma nova chave de acesso e uma chave de acesso secreta no StorageGRID no futuro, insira as novas chaves no ONTAP antes de excluir os valores antigos do StorageGRID.  Caso contrário, o ONTAP poderá perder temporariamente o acesso ao StorageGRID.



 a| 
Nome do contêiner
 a| 
Insira o nome do bucket StorageGRID que você criou para uso com esta camada ONTAP .

|===
. Conclua a configuração final do FabricPool no ONTAP.
+
.. Anexe um ou mais agregados à camada de nuvem.
.. Opcionalmente, crie uma política de níveis de volume.



