---
permalink: fabricpool/creating-load-balancer-endpoint-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, create, creating, certificate 
summary: O StorageGRID usa um balanceador de carga para gerenciar a carga de trabalho de aplicativos clientes, como o FabricPool.  O balanceamento de carga maximiza a velocidade e a capacidade de conexão entre vários nós de armazenamento. 
---
= Crie um ponto de extremidade do balanceador de carga para o FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID usa um balanceador de carga para gerenciar a carga de trabalho de aplicativos clientes, como o FabricPool.  O balanceamento de carga maximiza a velocidade e a capacidade de conexão entre vários nós de armazenamento.

Ao configurar o StorageGRID para uso com o FabricPool, você deve configurar um ponto de extremidade do balanceador de carga e carregar ou gerar um certificado de ponto de extremidade do balanceador de carga, que é usado para proteger a conexão entre o ONTAP e o StorageGRID.

Para usar o assistente de configuração do FabricPool para concluir esta tarefa, vá paralink:use-fabricpool-setup-wizard-steps.html["Acesse e conclua o assistente de configuração do FabricPool"] .

.Antes de começar
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você tem olink:../admin/admin-group-permissions.html["Permissão de acesso root"] .
* Você revisou o gerallink:../admin/managing-load-balancing.html["considerações para balanceamento de carga"] assim como olink:best-practices-for-load-balancing.html["melhores práticas para balanceamento de carga para FabricPool"] .


.Passos
. Selecione *CONFIGURAÇÃO* > *Rede* > *Pontos de extremidade do balanceador de carga*.
. Selecione *Criar*.
. Para a etapa *Inserir detalhes do ponto de extremidade*, preencha os seguintes campos.
+
[cols="1a,2a"]
|===
| Campo | Descrição 


 a| 
Nome
 a| 
Um nome descritivo para o ponto de extremidade.



 a| 
Porta
 a| 
A porta StorageGRID que você deseja usar para balanceamento de carga.  Este campo assume como padrão 10433 para o primeiro ponto de extremidade criado, mas você pode inserir qualquer porta externa não utilizada.  Se você digitar 80 ou 443, o ponto de extremidade será configurado somente em nós de gateway.  Essas portas são reservadas em nós de administração.

*Observação:* Portas usadas por outros serviços de rede não são permitidas. Veja olink:../network/internal-grid-node-communications.html["Referência de porta de rede"] .

Você fornecerá esse número ao ONTAP ao anexar o StorageGRID como uma camada de nuvem do FabricPool .



 a| 
Tipo de cliente
 a| 
Selecione *S3*.



 a| 
Protocolo de rede
 a| 
Selecione *HTTPS*.

*Observação*: a comunicação com o StorageGRID sem criptografia TLS é suportada, mas não é recomendada.

|===
. Para a etapa *Selecionar modo de vinculação*, especifique o modo de vinculação.  O modo de vinculação controla como o ponto de extremidade é acessado usando qualquer endereço IP ou usando endereços IP e interfaces de rede específicos.
+
[cols="1a,3a"]
|===
| Modo | Descrição 


 a| 
Global (padrão)
 a| 
Os clientes podem acessar o ponto de extremidade usando o endereço IP de qualquer nó de gateway ou nó de administração, o endereço IP virtual (VIP) de qualquer grupo de HA em qualquer rede ou um FQDN correspondente.

Use a configuração *Global* (padrão), a menos que você precise restringir a acessibilidade deste ponto de extremidade.



 a| 
IPs virtuais de grupos HA
 a| 
Os clientes devem usar um endereço IP virtual (ou FQDN correspondente) de um grupo HA para acessar este ponto de extremidade.

Os endpoints com esse modo de vinculação podem usar o mesmo número de porta, desde que os grupos de HA selecionados para os endpoints não se sobreponham.



 a| 
Interfaces de nó
 a| 
Os clientes devem usar os endereços IP (ou FQDNs correspondentes) das interfaces de nó selecionadas para acessar este ponto de extremidade.



 a| 
Tipo de nó
 a| 
Com base no tipo de nó selecionado, os clientes devem usar o endereço IP (ou FQDN correspondente) de qualquer nó de administração ou o endereço IP (ou FQDN correspondente) de qualquer nó de gateway para acessar esse ponto de extremidade.

|===
. Para a etapa *Acesso do locatário*, selecione uma das seguintes opções:
+
[cols="1a,2a"]
|===
| Campo | Descrição 


 a| 
Permitir todos os inquilinos (padrão)
 a| 
Todas as contas de locatários podem usar esse endpoint para acessar seus buckets.

*Permitir todos os locatários* é quase sempre a opção apropriada para o ponto de extremidade do balanceador de carga usado para FabricPool.

Você deve selecionar esta opção se ainda não tiver criado nenhuma conta de locatário.



 a| 
Permitir inquilinos selecionados
 a| 
Somente as contas de locatários selecionadas podem usar este ponto de extremidade para acessar seus buckets.



 a| 
Bloquear inquilinos selecionados
 a| 
As contas de locatários selecionadas não podem usar este ponto de extremidade para acessar seus buckets.  Todos os outros inquilinos podem usar este ponto de extremidade.

|===
. Para a etapa *Anexar certificado*, selecione uma das seguintes opções:
+
[cols="1a,2a"]
|===
| Campo | Descrição 


 a| 
Carregar certificado (recomendado)
 a| 
Use esta opção para carregar um certificado de servidor assinado pela CA, uma chave privada de certificado e um pacote de CA opcional.



 a| 
Gerar certificado
 a| 
Use esta opção para gerar um certificado autoassinado.  Verlink:../admin/configuring-load-balancer-endpoints.html["Configurar pontos de extremidade do balanceador de carga"] para obter detalhes sobre o que inserir.



 a| 
Usar certificado StorageGRID S3
 a| 
Esta opção estará disponível somente se você já tiver carregado ou gerado uma versão personalizada do certificado global StorageGRID . Verlink:../admin/configuring-custom-server-certificate-for-storage-node.html["Configurar certificados da API S3"] para mais detalhes.

|===
. Selecione *Criar*.



NOTE: Alterações em um certificado de ponto de extremidade podem levar até 15 minutos para serem aplicadas a todos os nós.
