---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, active interface, backup interface 
summary: 'Ao configurar o StorageGRID para uso com o FabricPool, você pode, opcionalmente, criar um ou mais grupos de alta disponibilidade (HA).  Um grupo HA é uma coleção de nós que contêm o serviço StorageGRID Load Balancer.  Um grupo HA pode conter nós de gateway, nós de administração ou ambos.' 
---
= Crie um grupo de alta disponibilidade (HA) para o FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao configurar o StorageGRID para uso com o FabricPool, você pode, opcionalmente, criar um ou mais grupos de alta disponibilidade (HA).  Um grupo HA é uma coleção de nós que contêm o serviço StorageGRID Load Balancer.  Um grupo HA pode conter nós de gateway, nós de administração ou ambos.

Você pode usar um grupo HA para ajudar a manter as conexões de dados do FabricPool disponíveis.  Um grupo HA usa endereços IP virtuais (VIPs) para fornecer acesso de alta disponibilidade ao serviço Load Balancer.  Se a interface ativa no grupo HA falhar, uma interface de backup poderá gerenciar a carga de trabalho com pouco impacto nas operações do FabricPool .

Para obter detalhes sobre esta tarefa, consultelink:../admin/managing-high-availability-groups.html["Gerenciar grupos de alta disponibilidade"] .  Para usar o assistente de configuração do FabricPool para concluir esta tarefa, vá paralink:use-fabricpool-setup-wizard-steps.html["Acesse e conclua o assistente de configuração do FabricPool"] .

.Antes de começar
* Você revisou olink:best-practices-for-high-availability-groups.html["melhores práticas para grupos de alta disponibilidade"] .
* Você está conectado ao Grid Manager usando umlink:../admin/web-browser-requirements.html["navegador da web compatível"] .
* Você tem olink:../admin/admin-group-permissions.html["Permissão de acesso root"] .
* Se você planeja usar uma VLAN, você criou a interface VLAN. Ver link:../admin/configure-vlan-interfaces.html["Configurar interfaces VLAN"] .


.Passos
. Selecione *CONFIGURAÇÃO* > *Rede* > *Grupos de alta disponibilidade*.
. Selecione *Criar*.
. Para a etapa *Inserir detalhes*, preencha os seguintes campos.
+
[cols="1a,2a"]
|===
| Campo | Descrição 


 a| 
Nome do grupo HA
 a| 
Um nome de exibição exclusivo para este grupo HA.



 a| 
Descrição (opcional)
 a| 
A descrição deste grupo HA.

|===
. Para a etapa *Adicionar interfaces*, selecione as interfaces de nó que deseja usar neste grupo de HA.
+
Use os cabeçalhos das colunas para classificar as linhas ou insira um termo de pesquisa para localizar interfaces mais rapidamente.

+
Você pode selecionar um ou mais nós, mas pode selecionar apenas uma interface para cada nó.

. Para a etapa *Priorizar interfaces*, determine a interface primária e quaisquer interfaces de backup para este grupo de HA.
+
Arraste as linhas para alterar os valores na coluna *Ordem de prioridade*.

+
A primeira interface na lista é a interface primária.  A interface primária é a interface ativa, a menos que ocorra uma falha.

+
Se o grupo HA incluir mais de uma interface e a interface ativa falhar, os endereços IP virtuais (VIP) serão movidos para a primeira interface de backup na ordem de prioridade.  Se essa interface falhar, os endereços VIP serão movidos para a próxima interface de backup e assim por diante.  Quando as falhas são resolvidas, os endereços VIP retornam para a interface de maior prioridade disponível.

. Para a etapa *Inserir endereços IP*, preencha os seguintes campos.
+
[cols="1a,2a"]
|===
| Campo | Descrição 


 a| 
CIDR de sub-rede
 a| 
O endereço da sub-rede VIP na notação CIDR: um endereço IPv4 seguido por uma barra e o comprimento da sub-rede (0-32).

O endereço de rede não deve ter nenhum bit de host definido. Por exemplo,  `192.16.0.0/22` .



 a| 
Endereço IP do gateway (opcional)
 a| 
Opcional.  Se os endereços IP do ONTAP usados ​​para acessar o StorageGRID não estiverem na mesma sub-rede que os endereços VIP do StorageGRID , insira o endereço IP do gateway local VIP do StorageGRID .  O endereço IP do gateway local deve estar dentro da sub-rede VIP.



 a| 
Endereço IP virtual
 a| 
Insira pelo menos um e no máximo dez endereços VIP para a interface ativa no grupo HA.  Todos os endereços VIP devem estar dentro da sub-rede VIP.

Pelo menos um endereço deve ser IPv4.  Opcionalmente, você pode especificar endereços IPv4 e IPv6 adicionais.

|===
. Selecione *Criar grupo HA* e depois selecione *Concluir*.

