---
permalink: fabricpool/use-fabricpool-setup-wizard.html 
sidebar: sidebar 
keywords: fabricPool, FabricPool setup wizard, ontap system manager 
summary: Você pode usar o assistente de configuração do FabricPool para configurar o StorageGRID como o sistema de armazenamento de objetos para uma camada de nuvem do FabricPool .  Após concluir o assistente de configuração, você pode inserir os detalhes necessários no ONTAP System Manager. 
---
= Usar o assistente de configuração do FabricPool : considerações e requisitos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o assistente de configuração do FabricPool para configurar o StorageGRID como o sistema de armazenamento de objetos para uma camada de nuvem do FabricPool .  Após concluir o assistente de configuração, você pode inserir os detalhes necessários no ONTAP System Manager.



== Quando usar o assistente de configuração do FabricPool

O assistente de configuração do FabricPool orienta você em cada etapa da configuração do StorageGRID para uso com o FabricPool e configura automaticamente determinadas entidades para você, como o ILM e as políticas de classificação de tráfego.  Como parte da conclusão do assistente, você baixa um arquivo que pode ser usado para inserir valores no ONTAP System Manager.  Use o assistente para configurar seu sistema mais rapidamente e garantir que suas configurações estejam em conformidade com as práticas recomendadas do StorageGRID e do FabricPool .

Supondo que você tenha permissão de acesso Root, você pode concluir o assistente de configuração do FabricPool quando começar a usar o StorageGRID Grid Manager ou pode acessar e concluir o assistente posteriormente.  Dependendo dos seus requisitos, você também pode configurar alguns ou todos os itens necessários manualmente e, em seguida, usar o assistente para reunir os valores que o ONTAP precisa em um único arquivo.


TIP: Use o assistente de configuração do FabricPool , a menos que você saiba que tem requisitos especiais ou que sua implementação exija personalização significativa.



== Antes de usar o assistente

Confirme se você concluiu estas etapas de pré-requisito.



=== Revisar as melhores práticas

* Você tem uma compreensão geral dolink:information-needed-to-attach-storagegrid-as-cloud-tier.html["informações necessárias para anexar o StorageGRID como uma camada de nuvem"] .
* Você revisou as práticas recomendadas do FabricPool para:
+
** link:best-practices-for-high-availability-groups.html["Grupos de alta disponibilidade (HA)"]
** link:best-practices-for-load-balancing.html["Balanceamento de carga"]
** link:best-practices-ilm.html["Regras e políticas do ILM"]






=== Obter endereços IP e configurar interfaces VLAN

Se você configurar um grupo HA, saberá a quais nós o ONTAP se conectará e qual rede StorageGRID será usada.  Você também sabe quais valores inserir para o CIDR de sub-rede, endereço IP do gateway e endereços IP virtuais (VIP).

Se você planeja usar uma LAN virtual para segregar o tráfego do FabricPool , você já configurou a interface VLAN. Ver link:../admin/configure-vlan-interfaces.html["Configurar interfaces VLAN"] .



=== Configurar federação de identidade e SSO

Se você planeja usar federação de identidade ou logon único (SSO) para seu sistema StorageGRID , você habilitou esses recursos. Você também sabe qual grupo federado deve ter acesso root para a conta de locatário que o ONTAP usará. Verlink:../admin/using-identity-federation.html["Usar federação de identidade"] elink:../admin/configuring-sso.html["Configurar logon único"] .



=== Obter e configurar nomes de domínio

* Você sabe qual nome de domínio totalmente qualificado (FQDN) usar para StorageGRID.  As entradas do servidor de nomes de domínio (DNS) mapearão esse FQDN para os endereços IP virtuais (VIP) do grupo HA que você criar usando o assistente. Ver link:../fabricpool/configure-dns-server.html["Configurar servidor DNS"] .
* Se você planeja usar solicitações de estilo de hospedagem virtual S3, você temlink:../admin/configuring-s3-api-endpoint-domain-names.html["nomes de domínio de endpoint S3 configurados"] .  O ONTAP usa URLs no estilo de caminho por padrão, mas é recomendado usar solicitações no estilo de hospedagem virtual.




=== Revisar os requisitos do balanceador de carga e do certificado de segurança

Se você planeja usar o balanceador de carga StorageGRID , você revisou o gerallink:../admin/managing-load-balancing.html["considerações para balanceamento de carga"] .  Você tem os certificados que irá enviar ou os valores necessários para gerar um certificado.

Se você planeja usar um ponto de extremidade de balanceador de carga externo (de terceiros), você tem o nome de domínio totalmente qualificado (FQDN), a porta e o certificado para esse balanceador de carga.



=== Confirmar configuração do pool de armazenamento ILM

se você instalou inicialmente o StorageGRID 11.6 ou anterior, você configurou o pool de armazenamento que usará.  Em geral, você deve criar um pool de armazenamento para cada site StorageGRID que usará para armazenar dados ONTAP .


NOTE: Este pré-requisito não se aplica se você instalou inicialmente o StorageGRID 11.7 ou 11.8.  Quando você instala inicialmente qualquer uma dessas versões, os pools de armazenamento são criados automaticamente para cada site.



== Relação entre o ONTAP e a camada de nuvem StorageGRID

O assistente FabricPool orienta você no processo de criação de uma única camada de nuvem StorageGRID que inclui um locatário do StorageGRID , um conjunto de chaves de acesso e um bucket do StorageGRID .  Você pode anexar esta camada de nuvem StorageGRID a uma ou mais camadas locais do ONTAP .

Anexar uma única camada de nuvem a várias camadas locais em um cluster é a melhor prática geral.  No entanto, dependendo dos seus requisitos, talvez você queira usar mais de um bucket ou até mesmo mais de um locatário do StorageGRID para as camadas locais em um único cluster.  Usar diferentes buckets e locatários permite isolar dados e acesso a dados entre camadas locais do ONTAP , mas é um pouco mais complexo de configurar e gerenciar.

A NetApp não recomenda anexar uma única camada de nuvem a camadas locais em vários clusters.


NOTE: Para obter as práticas recomendadas para usar o StorageGRID com o NetApp MetroCluster™ e o FabricPool Mirror, consulte https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598: Melhores práticas do FabricPool no ONTAP"^] .



=== Opcional: use um bucket diferente para cada nível local

Para usar mais de um bucket para as camadas locais em um cluster ONTAP , adicione mais de uma camada de nuvem StorageGRID no ONTAP.  Cada camada de nuvem compartilha o mesmo grupo HA, ponto de extremidade do balanceador de carga, locatário e chaves de acesso, mas usa um contêiner diferente (bucket StorageGRID ).  Siga estas etapas gerais:

. No StorageGRID Grid Manager, conclua o assistente de configuração do FabricPool para a primeira camada de nuvem.
. No ONTAP System Manager, adicione uma camada de nuvem e use o arquivo que você baixou do StorageGRID para fornecer os valores necessários.
. No StorageGRID Tenant Manager, faça login no locatário criado pelo assistente e crie um segundo bucket.
. Conclua o assistente do FabricPool novamente.  Selecione o grupo HA existente, o ponto de extremidade do balanceador de carga e o locatário.  Em seguida, selecione o novo bucket que você criou manualmente.  Crie uma nova regra de ILM para o novo bucket e ative uma política de ILM para incluir essa regra.
. No ONTAP, adicione uma segunda camada de nuvem, mas forneça o novo nome do bucket.




=== Opcional: use um locatário e um bucket diferentes para cada nível local

Para usar mais de um locatário e diferentes conjuntos de chaves de acesso para as camadas locais em um cluster ONTAP , adicione mais de uma camada de nuvem StorageGRID no ONTAP.  Cada camada de nuvem compartilha o mesmo grupo de HA, ponto de extremidade do balanceador de carga, mas usa um locatário, chaves de acesso e contêiner diferentes (bucket StorageGRID ).  Siga estas etapas gerais:

. No StorageGRID Grid Manager, conclua o assistente de configuração do FabricPool para a primeira camada de nuvem.
. No ONTAP System Manager, adicione uma camada de nuvem e use o arquivo que você baixou do StorageGRID para fornecer os valores necessários.
. Conclua o assistente do FabricPool novamente.  Selecione o grupo HA existente e o ponto de extremidade do balanceador de carga.  Crie um novo inquilino e bucket.  Crie uma nova regra de ILM para o novo bucket e ative uma política de ILM para incluir essa regra.
. No ONTAP, adicione uma segunda camada de nuvem, mas forneça a nova chave de acesso, a chave secreta e o nome do bucket.

